### 获取所有分类
POST {{host}}/admin/category/loadCategory
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "convert2Tree": true
}

### 保存分类
POST {{host}}/admin/category/saveCategory
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "categoryCode": "TEST301",
  "categoryName": "测试分类301"
}

### 删除分类
POST {{host}}/admin/category/delCategory
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "categoryId": "227885455327399936"
}
