### 获取所有分类
POST {{host}}/admin/category/loadCategory
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "convert2Tree": false
}

### 保存分类
POST {{host}}/admin/category/saveCategory
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "categoryId": "227760163027783680",
  "pCategoryId": 0,
  "categoryCode": "TEST",
  "categoryName": "测试分类"
}
