flowchart TB

    N1["CompatibleVideoCommentController.postComment"]
    class N1 controllermethod;

    C1["PostCommentCmd"]
    class C1 command;
    A1["VideoComment.onCreate"]
    class A1 entitymethod;
    E1["CommentPostedDomainEvent"]
    class E1 domainevent;

    CC1["UpdateVideoStatisticsCmd"]
    class CC1 command;
    AV1["Video.applyStatisticsDelta"]
    class AV1 entitymethod;
    EV1["VideoStatisticsDeltaAppliedDomainEvent"]
    class EV1 domainevent;

    CC2["SendCommentMessageCmd"]
    class CC2 command;
    CC3["SendReplyMessageCmd"]
    class CC3 command;
    AM1["CustomerMessageFactory.create"]
    class AM1 entitymethod;
    EM1["CustomerMessageCommentMentionCreatedDomainEvent"]
    class EM1 domainevent;
    EM2["CustomerMessageCommentReplyCreatedDomainEvent"]
    class EM2 domainevent;

    %% Relationships
    N1 -->|sends| C1
    C1 -->|executes| A1
    A1 -->|publishes| E1

    E1 -->|sends| CC1
    E1 -->|sends| CC2
    E1 -->|sends| CC3

    CC1 -->|executes| AV1
    AV1 -->|publishes| EV1

    CC2 -->|executes| AM1
    CC3 -->|executes| AM1

    AM1 -->|publishes| EM1
    AM1 -->|publishes| EM2

    %% Styles
    classDef controller fill:#e3f2fd,stroke:#1565c0,stroke-width:2px,font-weight:bold;
    classDef controllermethod fill:#e3f2fd,stroke:#1976d2,stroke-width:2px;
    classDef endpoint fill:#e3f2fd,stroke:#42a5f5,stroke-width:2px;
    classDef commandsender fill:#e3f2fd,stroke:#1565c0,stroke-width:2px,font-style:italic;
    classDef commandsendermethod fill:#e3f2fd,stroke:#1976d2,stroke-width:2px,font-style:italic;
    classDef command fill:#e8f5e8,stroke:#2e7d32,stroke-width:2px,font-weight:bold;
    classDef commandhandler fill:#e8f5e8,stroke:#388e3c,stroke-width:2px,font-weight:bold;
    classDef aggregate fill:#fff8e1,stroke:#ff8f00,stroke-width:3px,font-weight:bold;
    classDef entitymethod fill:#f3e5f5,stroke:#7b1fa2,stroke-width:2px;
    classDef domainevent fill:#fff3e0,stroke:#e65100,stroke-width:2px,font-style:italic;
    classDef domaineventhandler fill:#fff3e0,stroke:#ef6c00,stroke-width:2px,font-weight:bold;
    classDef integrationevent fill:#fce4ec,stroke:#880e4f,stroke-width:2px;
    classDef integrationeventhandler fill:#fce4ec,stroke:#ad1457,stroke-width:2px,font-weight:bold;
    classDef integrationeventconverter fill:#e3f2fd,stroke:#0277bd,stroke-width:2px;
    classDef repo fill:#d6dbdf,stroke:#85929e,stroke-width:2px;
    classDef uow fill:#f2f4f4,stroke:#7f8c8d,stroke-width:2px;
