flowchart TD
  N1[/&lt;anonymous&gt;/]
  class N1 querysendermethod
  N2[[CleanTempFilesCliHandler]]
  class N2 clihandler
  N3[[DeleteVideoFileResourcesCliHandler]]
  class N3 clihandler
  N4[[RefreshLoginSessionCliHandler]]
  class N4 clihandler
  N5[[RemoveVideoSearchIndexCliHandler]]
  class N5 clihandler
  N6[[CreateUploadSessionTempDirCliHandler]]
  class N6 clihandler
  N7[[DeleteUploadSessionTempDirCliHandler]]
  class N7 clihandler
  N8[[EncryptHlsVariantWithKeyCliHandler]]
  class N8 clihandler
  N9[[GenerateEncryptedMasterByVariantsCliHandler]]
  class N9 clihandler
  N10[[GenerateVideoAbrMasterCliHandler]]
  class N10 clihandler
  N11[[MergeUploadToMp4ByPathCliHandler]]
  class N11 clihandler
  N12[[TranscodeVideoFileToAbrByPathCliHandler]]
  class N12 clihandler
  N13[[UploadVideoAbrOutputCliHandler]]
  class N13 clihandler
  N14[[UniqueCategoryCodeQryHandler]]
  class N14 queryhandler
  N15[[UniqueCustomerActionTypeQryHandler]]
  class N15 queryhandler
  N16[[CheckFocusStatusQryHandler]]
  class N16 queryhandler
  N17[[GetCustomerProfileQryHandler]]
  class N17 queryhandler
  N18[[UniqueCustomerProfileEmailQryHandler]]
  class N18 queryhandler
  N19[[UniqueCustomerProfileNickNameQryHandler]]
  class N19 queryhandler
  N20[[UniqueCustomerProfilePhoneQryHandler]]
  class N20 queryhandler
  N21[[GetCustomerVideoSeriesInfoQryHandler]]
  class N21 queryhandler
  N22[[CheckNicknameExistsQryHandler]]
  class N22 queryhandler
  N23[[CheckUserExistsQryHandler]]
  class N23 queryhandler
  N24[[UniqueUserEmailQryHandler]]
  class N24 queryhandler
  N25[[UniqueUserPhoneQryHandler]]
  class N25 queryhandler
  N26[[GetRecentPasswordFailureCountQryHandler]]
  class N26 queryhandler
  N27[[GetVideoInfoQryHandler]]
  class N27 queryhandler
  N28[[UniqueVideoFileVariantQryHandler]]
  class N28 queryhandler
  N29[[GetCommentByIdQryHandler]]
  class N29 queryhandler
  N30[[CheckDanmukuExistsQryHandler]]
  class N30 queryhandler
  N31[[GetDanmukuOwnerQryHandler]]
  class N31 queryhandler
  N32[[GetVideoPostInfoQryHandler]]
  class N32 queryhandler
  N33[[UniqueVideoHlsEncryptKeyQryHandler]]
  class N33 queryhandler
  N34[[UniqueVideoHlsKeyTokenQryHandler]]
  class N34 queryhandler
  N35[[UniqueVideoFilePostQryHandler]]
  class N35 queryhandler
  N36[[UniqueVideoFilePostUploadIdQryHandler]]
  class N36 queryhandler
  N37[[UniqueVideoFilePostVariantQryHandler]]
  class N37 queryhandler
  N38[[GetVideoPostProcessingEncryptContextQryHandler]]
  class N38 queryhandler
  N39[[UniqueVideoPostProcessingFileQryHandler]]
  class N39 queryhandler
  N40[[UniqueVideoPostProcessingQryHandler]]
  class N40 queryhandler
  N41[[UniqueVideoPostProcessingVariantQryHandler]]
  class N41 queryhandler
  N42[[UniqueVideoQualityPolicyQryHandler]]
  class N42 queryhandler
  N43[[GetUploadSessionTempPathQryHandler]]
  class N43 queryhandler
  N44[[FinalizeCategoryAfterCreateCmd.Handler]]
  class N44 commandhandler
  N45{{FinalizeCategoryAfterCreateCmd.Request}}
  class N45 command
  N46[[SendCollectMessageCmd.Handler]]
  class N46 commandhandler
  N47{{SendCollectMessageCmd.Request}}
  class N47 command
  N48[[SendCommentMessageCmd.Handler]]
  class N48 commandhandler
  N49{{SendCommentMessageCmd.Request}}
  class N49 command
  N50[[SendLikeMessageCmd.Handler]]
  class N50 commandhandler
  N51{{SendLikeMessageCmd.Request}}
  class N51 command
  N52[[SendReplyMessageCmd.Handler]]
  class N52 commandhandler
  N53{{SendReplyMessageCmd.Request}}
  class N53 command
  N54[[SendVideoAuditFailedMessageCmd.Handler]]
  class N54 commandhandler
  N55{{SendVideoAuditFailedMessageCmd.Request}}
  class N55 command
  N56[[SendVideoAuditPassedMessageCmd.Handler]]
  class N56 commandhandler
  N57{{SendVideoAuditPassedMessageCmd.Request}}
  class N57 command
  N58[[AdjustAuthorCoinAfterDeleteCmd.Handler]]
  class N58 commandhandler
  N59{{AdjustAuthorCoinAfterDeleteCmd.Request}}
  class N59 command
  N60[[CreateCustomerProfileCmd.Handler]]
  class N60 commandhandler
  N61{{CreateCustomerProfileCmd.Request}}
  class N61 command
  N62[[RewardUserForVideoCmd.Handler]]
  class N62 commandhandler
  N63{{RewardUserForVideoCmd.Request}}
  class N63 command
  N64{{SpendCoinsForNicknameChangeCmd.Request}}
  class N64 command
  N65[[TransferCoinCmd.Handler]]
  class N65 commandhandler
  N66{{TransferCoinCmd.Request}}
  class N66 command
  N67{{UpdateStatisticsInfoCmd.Request}}
  class N67 command
  N68[[ChangeUserPhoneCmd.Handler]]
  class N68 commandhandler
  N69{{ChangeUserPhoneCmd.Request}}
  class N69 command
  N70{{RelationProfileCmd.Request}}
  class N70 command
  N71[[RecordAbnormalOperationCmd.Handler]]
  class N71 commandhandler
  N72{{RecordAbnormalOperationCmd.Request}}
  class N72 command
  N73[[ApplyVideoCoinCountDeltaCmd.Handler]]
  class N73 commandhandler
  N74{{ApplyVideoCoinCountDeltaCmd.Request}}
  class N74 command
  N75[[ApplyVideoCollectCountDeltaCmd.Handler]]
  class N75 commandhandler
  N76{{ApplyVideoCollectCountDeltaCmd.Request}}
  class N76 command
  N77[[ApplyVideoCommentCountDeltaCmd.Handler]]
  class N77 commandhandler
  N78{{ApplyVideoCommentCountDeltaCmd.Request}}
  class N78 command
  N79[[ApplyVideoDanmukuCountDeltaCmd.Handler]]
  class N79 commandhandler
  N80{{ApplyVideoDanmukuCountDeltaCmd.Request}}
  class N80 command
  N81[[ApplyVideoLikeCountDeltaCmd.Handler]]
  class N81 commandhandler
  N82{{ApplyVideoLikeCountDeltaCmd.Request}}
  class N82 command
  N83[[ApplyVideoPlayCountDeltaCmd.Handler]]
  class N83 commandhandler
  N84{{ApplyVideoPlayCountDeltaCmd.Request}}
  class N84 command
  N85{{ChangeVideoInteractionCmd.Request}}
  class N85 command
  N86{{DeleteVideoCmd.Request}}
  class N86 command
  N87[[TransferVideoToProductionCmd.Handler]]
  class N87 commandhandler
  N88{{TransferVideoToProductionCmd.Request}}
  class N88 command
  N89[[ApplyCustomerDislikedCommentCmd.Handler]]
  class N89 commandhandler
  N90{{ApplyCustomerDislikedCommentCmd.Request}}
  class N90 command
  N91[[ApplyCustomerLikedCommentCmd.Handler]]
  class N91 commandhandler
  N92{{ApplyCustomerLikedCommentCmd.Request}}
  class N92 command
  N93[[ApplyCustomerUndislikedCommentCmd.Handler]]
  class N93 commandhandler
  N94{{ApplyCustomerUndislikedCommentCmd.Request}}
  class N94 command
  N95[[ApplyCustomerUnlikedCommentCmd.Handler]]
  class N95 commandhandler
  N96{{ApplyCustomerUnlikedCommentCmd.Request}}
  class N96 command
  N97[[BatchDeleteCommentCmd.Handler]]
  class N97 commandhandler
  N98{{BatchDeleteCommentCmd.Request}}
  class N98 command
  N99[[BatchDeleteDanmukuCmd.Handler]]
  class N99 commandhandler
  N100{{BatchDeleteDanmukuCmd.Request}}
  class N100 command
  N101[[BindVideoHlsEncryptKeyToVideoCmd.Handler]]
  class N101 commandhandler
  N102{{BindVideoHlsEncryptKeyToVideoCmd.Request}}
  class N102 command
  N103[[BindVideoHlsKeyTokenToVideoCmd.Handler]]
  class N103 commandhandler
  N104{{BindVideoHlsKeyTokenToVideoCmd.Request}}
  class N104 command
  N105[[GenerateVideoPostQualityKeyCmd.Handler]]
  class N105 commandhandler
  N106{{GenerateVideoPostQualityKeyCmd.Request}}
  class N106 command
  N107[[InitTempAndStartUploadingCmd.Handler]]
  class N107 commandhandler
  N108{{InitTempAndStartUploadingCmd.Request}}
  class N108 command
  N109{{AddPlayHistoryCmd.Request}}
  class N109 command
  N110{{AuditVideoPostCmd.Request}}
  class N110 command
  N111[[SyncVideoPostProcessStatusCmd.Handler]]
  class N111 commandhandler
  N112{{SyncVideoPostProcessStatusCmd.Request}}
  class N112 command
  N113[[ApplyVideoPostProcessingEncryptResultCmd.Handler]]
  class N113 commandhandler
  N114{{ApplyVideoPostProcessingEncryptResultCmd.Request}}
  class N114 command
  N115[[ApplyVideoPostProcessingTranscodeResultCmd.Handler]]
  class N115 commandhandler
  N116{{ApplyVideoPostProcessingTranscodeResultCmd.Request}}
  class N116 command
  N117[[ApplyVideoPostProcessingVariantEncryptResultCmd.Handler]]
  class N117 commandhandler
  N118{{ApplyVideoPostProcessingVariantEncryptResultCmd.Request}}
  class N118 command
  N119[[PrepareVideoPostProcessingEncryptContextCmd.Handler]]
  class N119 commandhandler
  N120{{PrepareVideoPostProcessingEncryptContextCmd.Request}}
  class N120 command
  N121[[StartVideoPostProcessingCmd.Handler]]
  class N121 commandhandler
  N122{{StartVideoPostProcessingCmd.Request}}
  class N122 command
  N123[[SetVideoQualityPolicyCmd.Handler]]
  class N123 commandhandler
  N124{{SetVideoQualityPolicyCmd.Request}}
  class N124 command
  N125{{CleanTempFilesCli.Request}}
  class N125 cli
  N126{{DeleteVideoFileResourcesCli.Request}}
  class N126 cli
  N127{{RefreshLoginSessionCli.Request}}
  class N127 cli
  N128{{RemoveVideoSearchIndexCli.Request}}
  class N128 cli
  N129{{CreateUploadSessionTempDirCli.Request}}
  class N129 cli
  N130{{DeleteUploadSessionTempDirCli.Request}}
  class N130 cli
  N131{{EncryptHlsVariantWithKeyCli.Request}}
  class N131 cli
  N132{{GenerateEncryptedMasterByVariantsCli.Request}}
  class N132 cli
  N133{{GenerateVideoAbrMasterCli.Request}}
  class N133 cli
  N134{{MergeUploadToMp4ByPathCli.Request}}
  class N134 cli
  N135{{TranscodeVideoFileToAbrByPathCli.Request}}
  class N135 cli
  N136{{UploadVideoAbrOutputCli.Request}}
  class N136 cli
  N137{{UniqueCategoryCodeQry.Request}}
  class N137 query
  N138{{UniqueCustomerActionTypeQry.Request}}
  class N138 query
  N139{{CheckFocusStatusQry.Request}}
  class N139 query
  N140{{GetCustomerProfileQry.Request}}
  class N140 query
  N141{{UniqueCustomerProfileEmailQry.Request}}
  class N141 query
  N142{{UniqueCustomerProfileNickNameQry.Request}}
  class N142 query
  N143{{UniqueCustomerProfilePhoneQry.Request}}
  class N143 query
  N144{{GetCustomerVideoSeriesInfoQry.Request}}
  class N144 query
  N145{{CheckNicknameExistsQry.Request}}
  class N145 query
  N146{{CheckUserExistsQry.Request}}
  class N146 query
  N147{{UniqueUserEmailQry.Request}}
  class N147 query
  N148{{UniqueUserPhoneQry.Request}}
  class N148 query
  N149{{GetRecentPasswordFailureCountQry.Request}}
  class N149 query
  N150{{GetVideoInfoQry.Request}}
  class N150 query
  N151{{UniqueVideoFileVariantQry.Request}}
  class N151 query
  N152{{GetCommentByIdQry.Request}}
  class N152 query
  N153{{CheckDanmukuExistsQry.Request}}
  class N153 query
  N154{{GetDanmukuOwnerQry.Request}}
  class N154 query
  N155{{GetVideoPostInfoQry.Request}}
  class N155 query
  N156{{UniqueVideoHlsEncryptKeyQry.Request}}
  class N156 query
  N157{{UniqueVideoHlsKeyTokenQry.Request}}
  class N157 query
  N158{{UniqueVideoFilePostQry.Request}}
  class N158 query
  N159{{UniqueVideoFilePostUploadIdQry.Request}}
  class N159 query
  N160{{UniqueVideoFilePostVariantQry.Request}}
  class N160 query
  N161{{GetVideoPostProcessingEncryptContextQry.Request}}
  class N161 query
  N162{{UniqueVideoPostProcessingFileQry.Request}}
  class N162 query
  N163{{UniqueVideoPostProcessingQry.Request}}
  class N163 query
  N164{{UniqueVideoPostProcessingVariantQry.Request}}
  class N164 query
  N165{{UniqueVideoQualityPolicyQry.Request}}
  class N165 query
  N166{{GetUploadSessionTempPathQry.Request}}
  class N166 query
  N167[[CategoryBasicInfoUpdatedDomainEventSubscriber::on]]
  class N167 domaineventhandler
  N168[[CategoryCodeChangedDomainEventSubscriber::on]]
  class N168 domaineventhandler
  N169[[CategoryCreatedDomainEventSubscriber::on1]]
  class N169 domaineventhandler
  N170[[CategoryDeletedDomainEventSubscriber::on]]
  class N170 domaineventhandler
  N171[[CategoryNodePathUpdatedDomainEventSubscriber::on]]
  class N171 domaineventhandler
  N172[[CategoryParentChangedDomainEventSubscriber::on]]
  class N172 domaineventhandler
  N173[[CategorySortChangedDomainEventSubscriber::on]]
  class N173 domaineventhandler
  N174[[CustomerCoinGivenDomainEventSubscriber::on1]]
  class N174 domaineventhandler
  N175[[CustomerCoinGivenDomainEventSubscriber::on2]]
  class N175 domaineventhandler
  N176[[CustomerCollectedVideoDomainEventSubscriber::on]]
  class N176 domaineventhandler
  N177[[CustomerCollectedVideoDomainEventSubscriber::onSendMessage]]
  class N177 domaineventhandler
  N178[[CustomerDislikedCommentDomainEventSubscriber::on]]
  class N178 domaineventhandler
  N179[[CustomerLikedCommentDomainEventSubscriber::on]]
  class N179 domaineventhandler
  N180[[CustomerLikedVideoDomainEventSubscriber::on]]
  class N180 domaineventhandler
  N181[[CustomerLikedVideoDomainEventSubscriber::onSendMessage]]
  class N181 domaineventhandler
  N182[[CustomerUncollectedVideoDomainEventSubscriber::on]]
  class N182 domaineventhandler
  N183[[CustomerUndislikedCommentDomainEventSubscriber::on]]
  class N183 domaineventhandler
  N184[[CustomerUnlikedCommentDomainEventSubscriber::on]]
  class N184 domaineventhandler
  N185[[CustomerUnlikedVideoDomainEventSubscriber::on]]
  class N185 domaineventhandler
  N186[[UserFocusedDomainEventSubscriber::on]]
  class N186 domaineventhandler
  N187[[UserUnfocusedDomainEventSubscriber::on]]
  class N187 domaineventhandler
  N188[[CustomerMessageCollectionCreatedDomainEventSubscriber::on]]
  class N188 domaineventhandler
  N189[[CustomerMessageCommentMentionCreatedDomainEventSubscriber::on]]
  class N189 domaineventhandler
  N190[[CustomerMessageLikeCreatedDomainEventSubscriber::on]]
  class N190 domaineventhandler
  N191[[CustomerMessagePrivateCreatedDomainEventSubscriber::on]]
  class N191 domaineventhandler
  N192[[CustomerMessageSystemCreatedDomainEventSubscriber::on]]
  class N192 domaineventhandler
  N193[[CustomerAvatarUpdatedDomainEventSubscriber::on]]
  class N193 domaineventhandler
  N194[[CustomerNicknameUpdatedDomainEventSubscriber::on]]
  class N194 domaineventhandler
  N195[[CustomerProfileCoinsRewardedDomainEventSubscriber::on]]
  class N195 domaineventhandler
  N196[[CustomerProfileCreatedDomainEventSubscriber::on1]]
  class N196 domaineventhandler
  N197[[CustomerProfilePhoneChangedDomainEventSubscriber::on]]
  class N197 domaineventhandler
  N198[[CustomerProfileRewardCoinsReclaimedDomainEventSubscriber::on]]
  class N198 domaineventhandler
  N199[[CustomerProfileUpdatedDomainEventSubscriber::on]]
  class N199 domaineventhandler
  N200[[StatisticsCountUpdatedDomainEventSubscriber::on]]
  class N200 domaineventhandler
  N201[[AccountDisabledDomainEventSubscriber::on]]
  class N201 domaineventhandler
  N202[[AccountEnabledDomainEventSubscriber::on]]
  class N202 domaineventhandler
  N203[[LoginInfoUpdatedDomainEventSubscriber::on]]
  class N203 domaineventhandler
  N204[[PasswordChangedDomainEventSubscriber::on]]
  class N204 domaineventhandler
  N205[[RelationshipBoundDomainEventSubscriber::on]]
  class N205 domaineventhandler
  N206[[UserCreatedDomainEventSubscriber::on]]
  class N206 domaineventhandler
  N207[[UserPhoneChangedDomainEventSubscriber::on]]
  class N207 domaineventhandler
  N208[[PasswordInputFailedDomainEventSubscriber::on]]
  class N208 domaineventhandler
  N209[[VideoBasicsSyncedDomainEventSubscriber::on]]
  class N209 domaineventhandler
  N210[[VideoCoinCountDeltaAppliedDomainEventSubscriber::on]]
  class N210 domaineventhandler
  N211[[VideoCollectCountDeltaAppliedDomainEventSubscriber::on]]
  class N211 domaineventhandler
  N212[[VideoCommentCountDeltaAppliedDomainEventSubscriber::on]]
  class N212 domaineventhandler
  N213[[VideoCreatedDomainEventSubscriber::on]]
  class N213 domaineventhandler
  N214[[VideoDanmukuCountDeltaAppliedDomainEventSubscriber::on]]
  class N214 domaineventhandler
  N215[[VideoDeletedDomainEventSubscriber::cleanupComments]]
  class N215 domaineventhandler
  N216[[VideoDeletedDomainEventSubscriber::cleanupDanmaku]]
  class N216 domaineventhandler
  N217[[VideoDeletedDomainEventSubscriber::removeSearchIndex]]
  class N217 domaineventhandler
  N218[[VideoInteractionChangedDomainEventSubscriber::on]]
  class N218 domaineventhandler
  N219[[VideoLastPlayTimeAttachedDomainEventSubscriber::on]]
  class N219 domaineventhandler
  N220[[VideoLikeCountDeltaAppliedDomainEventSubscriber::on]]
  class N220 domaineventhandler
  N221[[VideoPlayCountDeltaAppliedDomainEventSubscriber::on]]
  class N221 domaineventhandler
  N222[[VideoPostDeletedDomainEventSubscriber::adjustAuthorCoin]]
  class N222 domaineventhandler
  N223[[VideoPostDeletedDomainEventSubscriber::deletePhysicalFiles]]
  class N223 domaineventhandler
  N224[[VideoPostDeletedDomainEventSubscriber::removeVideo]]
  class N224 domaineventhandler
  N225[[VideoRecommendedDomainEventSubscriber::on]]
  class N225 domaineventhandler
  N226[[VideoUnrecommendedDomainEventSubscriber::on]]
  class N226 domaineventhandler
  N227[[VideoAuditTraceRecordedDomainEventSubscriber::sendAuditMessage]]
  class N227 domaineventhandler
  N228[[VideoAuditTraceRecordedDomainEventSubscriber::updateVideoStatus]]
  class N228 domaineventhandler
  N229[[CommentDeletedDomainEventSubscriber::on]]
  class N229 domaineventhandler
  N230[[CommentDeletedDomainEventSubscriber::on1]]
  class N230 domaineventhandler
  N231[[CommentPostedDomainEventSubscriber::on]]
  class N231 domaineventhandler
  N232[[CommentPostedDomainEventSubscriber::on1]]
  class N232 domaineventhandler
  N233[[CommentPostedDomainEventSubscriber::on2]]
  class N233 domaineventhandler
  N234[[CommentToppedDomainEventSubscriber::on]]
  class N234 domaineventhandler
  N235[[CommentUntoppedDomainEventSubscriber::on]]
  class N235 domaineventhandler
  N236[[DanmukuDeletedDomainEventSubscriber::on]]
  class N236 domaineventhandler
  N237[[DanmukuPostedDomainEventSubscriber::on]]
  class N237 domaineventhandler
  N238[[VideoPostQualityKeyGeneratedDomainEventSubscriber::on]]
  class N238 domaineventhandler
  N239[[UploadSessionAbortedDomainEventSubscriber::on]]
  class N239 domaineventhandler
  N240[[UploadSessionCreatedDomainEventSubscriber::on]]
  class N240 domaineventhandler
  N241[[VideoFileUploadSessionChunkUploadedDomainEventSubscriber::on]]
  class N241 domaineventhandler
  N242[[VideoFileUploadSessionMarkedDoneDomainEventSubscriber::on]]
  class N242 domaineventhandler
  N243[[VideoHlsKeyTokenIssuedDomainEventSubscriber::addPlayHistoryCmd]]
  class N243 domaineventhandler
  N244[[VideoHlsKeyTokenIssuedDomainEventSubscriber::applyVideoPlayCountDelta]]
  class N244 domaineventhandler
  N245[[VideoPlayHistoryCreatedDomainEventSubscriber::on]]
  class N245 domaineventhandler
  N246[[VideoPlayHistoryProgressUpdatedDomainEventSubscriber::on]]
  class N246 domaineventhandler
  N247[[VideoAuditFailedDomainEventSubscriber::on]]
  class N247 domaineventhandler
  N248[[VideoAuditPassedDomainEventSubscriber::on]]
  class N248 domaineventhandler
  N249[[VideoAuditPassedDomainEventSubscriber::on1]]
  class N249 domaineventhandler
  N250[[VideoAuditPassedDomainEventSubscriber::on2]]
  class N250 domaineventhandler
  N251[[VideoAuditPassedDomainEventSubscriber::on3]]
  class N251 domaineventhandler
  N252[[VideoPostCreatedDomainEventSubscriber::on]]
  class N252 domaineventhandler
  N253[[VideoPostInteractionChangedDomainEventSubscriber::on]]
  class N253 domaineventhandler
  N254[[VideoPostTranscodingRequestedDomainEventSubscriber::on]]
  class N254 domaineventhandler
  N255[[VideoPostProcessingCompletedDomainEventSubscriber::on]]
  class N255 domaineventhandler
  N256[[VideoPostProcessingEncryptContextPreparedDomainEventSubscriber::on]]
  class N256 domaineventhandler
  N257[[VideoPostProcessingFileEncryptCompletedDomainEventSubscriber::on]]
  class N257 domaineventhandler
  N258[[VideoPostProcessingStartedDomainEventSubscriber::on]]
  class N258 domaineventhandler
  N259[[VideoPostProcessingTranscodeCompletedDomainEventSubscriber::on]]
  class N259 domaineventhandler
  N260(Category::&lt;get-id&gt;)
  class N260 entitymethod
  N261(Category::&lt;get-nodePath&gt;)
  class N261 entitymethod
  N262(Category::&lt;get-parentId&gt;)
  class N262 entitymethod
  N263(Category::&lt;get-sort&gt;)
  class N263 entitymethod
  N264(Category::addSort)
  class N264 entitymethod
  N265(Category::changeSort)
  class N265 entitymethod
  N266(Category::updateNodePath)
  class N266 entitymethod
  N267((CategoryBasicInfoUpdatedDomainEvent))
  class N267 domainevent
  N268((CategoryCodeChangedDomainEvent))
  class N268 domainevent
  N269((CategoryCreatedDomainEvent))
  class N269 domainevent
  N270((CategoryDeletedDomainEvent))
  class N270 domainevent
  N271((CategoryNodePathUpdatedDomainEvent))
  class N271 domainevent
  N272((CategoryParentChangedDomainEvent))
  class N272 domainevent
  N273((CategorySortChangedDomainEvent))
  class N273 domainevent
  N274((CustomerCoinGivenDomainEvent))
  class N274 domainevent
  N275((CustomerCollectedVideoDomainEvent))
  class N275 domainevent
  N276((CustomerDislikedCommentDomainEvent))
  class N276 domainevent
  N277((CustomerLikedCommentDomainEvent))
  class N277 domainevent
  N278((CustomerLikedVideoDomainEvent))
  class N278 domainevent
  N279((CustomerUncollectedVideoDomainEvent))
  class N279 domainevent
  N280((CustomerUndislikedCommentDomainEvent))
  class N280 domainevent
  N281((CustomerUnlikedCommentDomainEvent))
  class N281 domainevent
  N282((CustomerUnlikedVideoDomainEvent))
  class N282 domainevent
  N283((UserFocusedDomainEvent))
  class N283 domainevent
  N284((UserUnfocusedDomainEvent))
  class N284 domainevent
  N285(CustomerMessage::onCreate)
  class N285 entitymethod
  N286((CustomerMessageCollectionCreatedDomainEvent))
  class N286 domainevent
  N287((CustomerMessageCommentMentionCreatedDomainEvent))
  class N287 domainevent
  N288((CustomerMessageLikeCreatedDomainEvent))
  class N288 domainevent
  N289((CustomerMessagePrivateCreatedDomainEvent))
  class N289 domainevent
  N290((CustomerMessageSystemCreatedDomainEvent))
  class N290 domainevent
  N291(CustomerProfile::onCreate)
  class N291 entitymethod
  N292(CustomerProfile::reclaimRewardCoins)
  class N292 entitymethod
  N293(CustomerProfile::rewardCoins)
  class N293 entitymethod
  N294(CustomerProfile::transferCoin)
  class N294 entitymethod
  N295((CustomerAvatarUpdatedDomainEvent))
  class N295 domainevent
  N296((CustomerNicknameUpdatedDomainEvent))
  class N296 domainevent
  N297((CustomerProfileCoinsRewardedDomainEvent))
  class N297 domainevent
  N298((CustomerProfileCreatedDomainEvent))
  class N298 domainevent
  N299((CustomerProfilePhoneChangedDomainEvent))
  class N299 domainevent
  N300((CustomerProfileRewardCoinsReclaimedDomainEvent))
  class N300 domainevent
  N301((CustomerProfileUpdatedDomainEvent))
  class N301 domainevent
  N302((StatisticsCountUpdatedDomainEvent))
  class N302 domainevent
  N303(User::bindPhone)
  class N303 entitymethod
  N304((AccountDisabledDomainEvent))
  class N304 domainevent
  N305((AccountEnabledDomainEvent))
  class N305 domainevent
  N306((LoginInfoUpdatedDomainEvent))
  class N306 domainevent
  N307((PasswordChangedDomainEvent))
  class N307 domainevent
  N308((RelationshipBoundDomainEvent))
  class N308 domainevent
  N309((UserCreatedDomainEvent))
  class N309 domainevent
  N310((UserPhoneChangedDomainEvent))
  class N310 domainevent
  N311(UserAbnormalOperationLog::&lt;get-id&gt;)
  class N311 entitymethod
  N312(UserAbnormalOperationLog::onCreate)
  class N312 entitymethod
  N313((PasswordInputFailedDomainEvent))
  class N313 domainevent
  N314(Video::&lt;get-coinCount&gt;)
  class N314 entitymethod
  N315(Video::&lt;get-collectCount&gt;)
  class N315 entitymethod
  N316(Video::&lt;get-commentCount&gt;)
  class N316 entitymethod
  N317(Video::&lt;get-customerId&gt;)
  class N317 entitymethod
  N318(Video::&lt;get-danmukuCount&gt;)
  class N318 entitymethod
  N319(Video::&lt;get-id&gt;)
  class N319 entitymethod
  N320(Video::&lt;get-likeCount&gt;)
  class N320 entitymethod
  N321(Video::&lt;get-playCount&gt;)
  class N321 entitymethod
  N322(Video::applyCoinCountDelta)
  class N322 entitymethod
  N323(Video::applyCollectCountDelta)
  class N323 entitymethod
  N324(Video::applyCommentCountDelta)
  class N324 entitymethod
  N325(Video::applyDanmukuCountDelta)
  class N325 entitymethod
  N326(Video::applyLikeCountDelta)
  class N326 entitymethod
  N327(Video::applyPlayCountDelta)
  class N327 entitymethod
  N328(Video::onCreate)
  class N328 entitymethod
  N329(Video::syncFromBasics)
  class N329 entitymethod
  N330((VideoBasicsSyncedDomainEvent))
  class N330 domainevent
  N331((VideoCoinCountDeltaAppliedDomainEvent))
  class N331 domainevent
  N332((VideoCollectCountDeltaAppliedDomainEvent))
  class N332 domainevent
  N333((VideoCommentCountDeltaAppliedDomainEvent))
  class N333 domainevent
  N334((VideoCreatedDomainEvent))
  class N334 domainevent
  N335((VideoDanmukuCountDeltaAppliedDomainEvent))
  class N335 domainevent
  N336((VideoDeletedDomainEvent))
  class N336 domainevent
  N337((VideoInteractionChangedDomainEvent))
  class N337 domainevent
  N338((VideoLastPlayTimeAttachedDomainEvent))
  class N338 domainevent
  N339((VideoLikeCountDeltaAppliedDomainEvent))
  class N339 domainevent
  N340((VideoPlayCountDeltaAppliedDomainEvent))
  class N340 domainevent
  N341((VideoRecommendedDomainEvent))
  class N341 domainevent
  N342((VideoUnrecommendedDomainEvent))
  class N342 domainevent
  N343((VideoAuditTraceRecordedDomainEvent))
  class N343 domainevent
  N344(VideoComment::&lt;get-customerId&gt;)
  class N344 entitymethod
  N345(VideoComment::onDelete)
  class N345 entitymethod
  N346(VideoComment::updateStatistics)
  class N346 entitymethod
  N347((CommentDeletedDomainEvent))
  class N347 domainevent
  N348((CommentPostedDomainEvent))
  class N348 domainevent
  N349((CommentToppedDomainEvent))
  class N349 domainevent
  N350((CommentUntoppedDomainEvent))
  class N350 domainevent
  N351(VideoDanmuku::onDelete)
  class N351 entitymethod
  N352((DanmukuDeletedDomainEvent))
  class N352 domainevent
  N353((DanmukuPostedDomainEvent))
  class N353 domainevent
  N354(VideoFileUploadSession::initTempAndStartUploading)
  class N354 entitymethod
  N355((UploadSessionAbortedDomainEvent))
  class N355 domainevent
  N356((UploadSessionCreatedDomainEvent))
  class N356 domainevent
  N357((VideoFileUploadSessionChunkUploadedDomainEvent))
  class N357 domainevent
  N358((VideoFileUploadSessionMarkedDoneDomainEvent))
  class N358 domainevent
  N359(VideoHlsEncryptKey::bindVideoId)
  class N359 entitymethod
  N360(VideoHlsEncryptKey::onCreate)
  class N360 entitymethod
  N361((VideoHlsEncryptKeyCreatedDomainEvent))
  class N361 domainevent
  N362(VideoHlsKeyToken::bindVideoId)
  class N362 entitymethod
  N363((VideoHlsKeyTokenIssuedDomainEvent))
  class N363 domainevent
  N364((VideoPlayHistoryCreatedDomainEvent))
  class N364 domainevent
  N365((VideoPlayHistoryProgressUpdatedDomainEvent))
  class N365 domainevent
  N366(VideoFilePost::&lt;get-customerId&gt;)
  class N366 entitymethod
  N367(VideoFilePost::&lt;get-duration&gt;)
  class N367 entitymethod
  N368(VideoFilePost::&lt;get-fileIndex&gt;)
  class N368 entitymethod
  N369(VideoFilePost::&lt;get-fileName&gt;)
  class N369 entitymethod
  N370(VideoFilePost::&lt;get-fileSize&gt;)
  class N370 entitymethod
  N371(VideoFilePost::&lt;get-id&gt;)
  class N371 entitymethod
  N372(VideoFilePost::&lt;get-videoFilePostVariants&gt;)
  class N372 entitymethod
  N373(VideoFilePost::applyEncryptResult)
  class N373 entitymethod
  N374(VideoFilePost::applyTranscodeResult)
  class N374 entitymethod
  N375(VideoFilePost::syncVariants)
  class N375 entitymethod
  N376(VideoFilePostVariant::&lt;get-audioBitrateKbps&gt;)
  class N376 entitymethod
  N377(VideoFilePostVariant::&lt;get-bandwidthBps&gt;)
  class N377 entitymethod
  N378(VideoFilePostVariant::&lt;get-height&gt;)
  class N378 entitymethod
  N379(VideoFilePostVariant::&lt;get-playlistPath&gt;)
  class N379 entitymethod
  N380(VideoFilePostVariant::&lt;get-quality&gt;)
  class N380 entitymethod
  N381(VideoFilePostVariant::&lt;get-segmentDuration&gt;)
  class N381 entitymethod
  N382(VideoFilePostVariant::&lt;get-segmentPrefix&gt;)
  class N382 entitymethod
  N383(VideoFilePostVariant::&lt;get-videoBitrateKbps&gt;)
  class N383 entitymethod
  N384(VideoFilePostVariant::&lt;get-width&gt;)
  class N384 entitymethod
  N385(VideoPost::&lt;get-customerId&gt;)
  class N385 entitymethod
  N386(VideoPost::&lt;get-videoFilePosts&gt;)
  class N386 entitymethod
  N387(VideoPost::applyProcessStatus)
  class N387 entitymethod
  N388(VideoPost::updateDuration)
  class N388 entitymethod
  N389((VideoAuditFailedDomainEvent))
  class N389 domainevent
  N390((VideoAuditPassedDomainEvent))
  class N390 domainevent
  N391((VideoPostCreatedDomainEvent))
  class N391 domainevent
  N392((VideoPostDeletedDomainEvent))
  class N392 domainevent
  N393((VideoPostInteractionChangedDomainEvent))
  class N393 domainevent
  N394((VideoPostTranscodingRequestedDomainEvent))
  class N394 domainevent
  N395(VideoPostProcessing::&lt;get-videoPostProcessingFiles&gt;)
  class N395 entitymethod
  N396(VideoPostProcessing::appendFiles)
  class N396 entitymethod
  N397(VideoPostProcessing::applyEncryptResult)
  class N397 entitymethod
  N398(VideoPostProcessing::applyTranscodeResult)
  class N398 entitymethod
  N399(VideoPostProcessing::applyVariantEncryptResult)
  class N399 entitymethod
  N400(VideoPostProcessing::onCreate)
  class N400 entitymethod
  N401(VideoPostProcessing::prepareEncryptContext)
  class N401 entitymethod
  N402(VideoPostProcessingFile::&lt;get-encryptKeyVersion&gt;)
  class N402 entitymethod
  N403(VideoPostProcessingFile::&lt;get-fileIndex&gt;)
  class N403 entitymethod
  N404((VideoPostProcessingCompletedDomainEvent))
  class N404 domainevent
  N405((VideoPostProcessingEncryptContextPreparedDomainEvent))
  class N405 domainevent
  N406((VideoPostProcessingFileEncryptCompletedDomainEvent))
  class N406 domainevent
  N407((VideoPostProcessingStartedDomainEvent))
  class N407 domainevent
  N408((VideoPostProcessingTranscodeCompletedDomainEvent))
  class N408 domainevent
  N409(VideoQualityPolicy::applyPolicy)
  class N409 entitymethod
  N410(VideoQualityPolicy::onCreate)
  class N410 entitymethod
  N1 -->|CommandSenderMethodToCommand| N102
  N1 -->|CommandSenderMethodToCommand| N104
  N1 -->|CommandSenderMethodToCommand| N106
  N1 -->|CommandSenderMethodToCommand| N116
  N1 -->|CommandSenderMethodToCommand| N124
  N1 -->|CliSenderMethodToCli| N130
  N1 -->|CliSenderMethodToCli| N133
  N1 -->|CliSenderMethodToCli| N134
  N1 -->|CliSenderMethodToCli| N135
  N1 -->|CliSenderMethodToCli| N136
  N1 -->|QuerySenderMethodToQuery| N137
  N1 -->|QuerySenderMethodToQuery| N138
  N1 -->|QuerySenderMethodToQuery| N139
  N1 -->|QuerySenderMethodToQuery| N140
  N1 -->|QuerySenderMethodToQuery| N141
  N1 -->|QuerySenderMethodToQuery| N142
  N1 -->|QuerySenderMethodToQuery| N143
  N1 -->|QuerySenderMethodToQuery| N144
  N1 -->|QuerySenderMethodToQuery| N145
  N1 -->|QuerySenderMethodToQuery| N146
  N1 -->|QuerySenderMethodToQuery| N147
  N1 -->|QuerySenderMethodToQuery| N148
  N1 -->|QuerySenderMethodToQuery| N150
  N1 -->|QuerySenderMethodToQuery| N151
  N1 -->|QuerySenderMethodToQuery| N152
  N1 -->|QuerySenderMethodToQuery| N153
  N1 -->|QuerySenderMethodToQuery| N154
  N1 -->|QuerySenderMethodToQuery| N155
  N1 -->|QuerySenderMethodToQuery| N156
  N1 -->|QuerySenderMethodToQuery| N157
  N1 -->|QuerySenderMethodToQuery| N158
  N1 -->|QuerySenderMethodToQuery| N159
  N1 -->|QuerySenderMethodToQuery| N160
  N1 -->|QuerySenderMethodToQuery| N162
  N1 -->|QuerySenderMethodToQuery| N163
  N1 -->|QuerySenderMethodToQuery| N164
  N1 -->|QuerySenderMethodToQuery| N165
  N1 -->|QuerySenderMethodToQuery| N166
  N1 -->|EntityMethodToDomainEvent| N267
  N1 -->|EntityMethodToDomainEvent| N268
  N1 -->|EntityMethodToDomainEvent| N269
  N1 -->|EntityMethodToDomainEvent| N270
  N1 -->|EntityMethodToDomainEvent| N271
  N1 -->|EntityMethodToDomainEvent| N272
  N1 -->|EntityMethodToDomainEvent| N273
  N1 -->|EntityMethodToDomainEvent| N274
  N1 -->|EntityMethodToDomainEvent| N275
  N1 -->|EntityMethodToDomainEvent| N276
  N1 -->|EntityMethodToDomainEvent| N277
  N1 -->|EntityMethodToDomainEvent| N278
  N1 -->|EntityMethodToDomainEvent| N279
  N1 -->|EntityMethodToDomainEvent| N280
  N1 -->|EntityMethodToDomainEvent| N281
  N1 -->|EntityMethodToDomainEvent| N282
  N1 -->|EntityMethodToDomainEvent| N283
  N1 -->|EntityMethodToDomainEvent| N284
  N1 -->|EntityMethodToDomainEvent| N286
  N1 -->|EntityMethodToDomainEvent| N287
  N1 -->|EntityMethodToDomainEvent| N288
  N1 -->|EntityMethodToDomainEvent| N289
  N1 -->|EntityMethodToDomainEvent| N290
  N1 -->|EntityMethodToDomainEvent| N295
  N1 -->|EntityMethodToDomainEvent| N296
  N1 -->|EntityMethodToDomainEvent| N297
  N1 -->|EntityMethodToDomainEvent| N298
  N1 -->|EntityMethodToDomainEvent| N299
  N1 -->|EntityMethodToDomainEvent| N300
  N1 -->|EntityMethodToDomainEvent| N301
  N1 -->|EntityMethodToDomainEvent| N302
  N1 -->|EntityMethodToDomainEvent| N304
  N1 -->|EntityMethodToDomainEvent| N305
  N1 -->|EntityMethodToDomainEvent| N306
  N1 -->|EntityMethodToDomainEvent| N307
  N1 -->|EntityMethodToDomainEvent| N308
  N1 -->|EntityMethodToDomainEvent| N309
  N1 -->|EntityMethodToDomainEvent| N310
  N1 -->|EntityMethodToDomainEvent| N313
  N1 -->|EntityMethodToDomainEvent| N330
  N1 -->|EntityMethodToDomainEvent| N331
  N1 -->|EntityMethodToDomainEvent| N332
  N1 -->|EntityMethodToDomainEvent| N333
  N1 -->|EntityMethodToDomainEvent| N334
  N1 -->|EntityMethodToDomainEvent| N335
  N1 -->|EntityMethodToDomainEvent| N336
  N1 -->|EntityMethodToDomainEvent| N337
  N1 -->|EntityMethodToDomainEvent| N338
  N1 -->|EntityMethodToDomainEvent| N339
  N1 -->|EntityMethodToDomainEvent| N340
  N1 -->|EntityMethodToDomainEvent| N341
  N1 -->|EntityMethodToDomainEvent| N342
  N1 -->|EntityMethodToDomainEvent| N343
  N1 -->|EntityMethodToDomainEvent| N347
  N1 -->|EntityMethodToDomainEvent| N348
  N1 -->|EntityMethodToDomainEvent| N349
  N1 -->|EntityMethodToDomainEvent| N350
  N1 -->|EntityMethodToDomainEvent| N352
  N1 -->|EntityMethodToDomainEvent| N353
  N1 -->|EntityMethodToDomainEvent| N355
  N1 -->|EntityMethodToDomainEvent| N356
  N1 -->|EntityMethodToDomainEvent| N357
  N1 -->|EntityMethodToDomainEvent| N358
  N1 -->|EntityMethodToDomainEvent| N361
  N1 -->|EntityMethodToDomainEvent| N363
  N1 -->|EntityMethodToDomainEvent| N364
  N1 -->|EntityMethodToDomainEvent| N365
  N1 -->|EntityMethodToDomainEvent| N389
  N1 -->|EntityMethodToDomainEvent| N390
  N1 -->|EntityMethodToDomainEvent| N391
  N1 -->|EntityMethodToDomainEvent| N392
  N1 -->|EntityMethodToDomainEvent| N393
  N1 -->|EntityMethodToDomainEvent| N394
  N1 -->|EntityMethodToDomainEvent| N404
  N1 -->|EntityMethodToDomainEvent| N405
  N1 -->|EntityMethodToDomainEvent| N406
  N1 -->|EntityMethodToDomainEvent| N407
  N1 -->|EntityMethodToDomainEvent| N408
  N44 -->|CommandHandlerToEntityMethod| N260
  N44 -->|CommandHandlerToEntityMethod| N261
  N44 -->|CommandHandlerToEntityMethod| N262
  N44 -->|CommandHandlerToEntityMethod| N263
  N44 -->|CommandHandlerToEntityMethod| N264
  N44 -->|CommandHandlerToEntityMethod| N265
  N44 -->|CommandHandlerToEntityMethod| N266
  N45 -->|CommandToCommandHandler| N44
  N46 -->|CommandHandlerToEntityMethod| N285
  N46 -->|CommandHandlerToEntityMethod| N317
  N47 -->|CommandToCommandHandler| N46
  N48 -->|CommandHandlerToEntityMethod| N285
  N48 -->|CommandHandlerToEntityMethod| N317
  N49 -->|CommandToCommandHandler| N48
  N50 -->|CommandHandlerToEntityMethod| N285
  N50 -->|CommandHandlerToEntityMethod| N317
  N51 -->|CommandToCommandHandler| N50
  N52 -->|CommandHandlerToEntityMethod| N285
  N52 -->|CommandHandlerToEntityMethod| N344
  N53 -->|CommandToCommandHandler| N52
  N54 -->|CommandHandlerToEntityMethod| N285
  N54 -->|CommandHandlerToEntityMethod| N385
  N55 -->|CommandToCommandHandler| N54
  N56 -->|CommandHandlerToEntityMethod| N285
  N56 -->|CommandHandlerToEntityMethod| N385
  N57 -->|CommandToCommandHandler| N56
  N58 -->|CommandHandlerToEntityMethod| N292
  N59 -->|CommandToCommandHandler| N58
  N60 -->|CommandHandlerToEntityMethod| N291
  N61 -->|CommandToCommandHandler| N60
  N62 -->|CommandHandlerToEntityMethod| N293
  N63 -->|CommandToCommandHandler| N62
  N65 -->|CommandHandlerToEntityMethod| N294
  N66 -->|CommandToCommandHandler| N65
  N68 -->|CommandHandlerToEntityMethod| N303
  N69 -->|CommandToCommandHandler| N68
  N71 -->|CommandHandlerToEntityMethod| N311
  N71 -->|CommandHandlerToEntityMethod| N312
  N72 -->|CommandToCommandHandler| N71
  N73 -->|CommandHandlerToEntityMethod| N314
  N73 -->|CommandHandlerToEntityMethod| N319
  N73 -->|CommandHandlerToEntityMethod| N322
  N74 -->|CommandToCommandHandler| N73
  N75 -->|CommandHandlerToEntityMethod| N315
  N75 -->|CommandHandlerToEntityMethod| N319
  N75 -->|CommandHandlerToEntityMethod| N323
  N76 -->|CommandToCommandHandler| N75
  N77 -->|CommandHandlerToEntityMethod| N316
  N77 -->|CommandHandlerToEntityMethod| N319
  N77 -->|CommandHandlerToEntityMethod| N324
  N78 -->|CommandToCommandHandler| N77
  N79 -->|CommandHandlerToEntityMethod| N318
  N79 -->|CommandHandlerToEntityMethod| N319
  N79 -->|CommandHandlerToEntityMethod| N325
  N80 -->|CommandToCommandHandler| N79
  N81 -->|CommandHandlerToEntityMethod| N319
  N81 -->|CommandHandlerToEntityMethod| N320
  N81 -->|CommandHandlerToEntityMethod| N326
  N82 -->|CommandToCommandHandler| N81
  N83 -->|CommandHandlerToEntityMethod| N319
  N83 -->|CommandHandlerToEntityMethod| N321
  N83 -->|CommandHandlerToEntityMethod| N327
  N84 -->|CommandToCommandHandler| N83
  N87 -->|CommandHandlerToEntityMethod| N319
  N87 -->|CommandHandlerToEntityMethod| N328
  N87 -->|CommandHandlerToEntityMethod| N329
  N87 -->|CommandHandlerToEntityMethod| N366
  N87 -->|CommandHandlerToEntityMethod| N367
  N87 -->|CommandHandlerToEntityMethod| N368
  N87 -->|CommandHandlerToEntityMethod| N369
  N87 -->|CommandHandlerToEntityMethod| N370
  N87 -->|CommandHandlerToEntityMethod| N371
  N87 -->|CommandHandlerToEntityMethod| N372
  N87 -->|CommandHandlerToEntityMethod| N376
  N87 -->|CommandHandlerToEntityMethod| N377
  N87 -->|CommandHandlerToEntityMethod| N378
  N87 -->|CommandHandlerToEntityMethod| N379
  N87 -->|CommandHandlerToEntityMethod| N380
  N87 -->|CommandHandlerToEntityMethod| N381
  N87 -->|CommandHandlerToEntityMethod| N382
  N87 -->|CommandHandlerToEntityMethod| N383
  N87 -->|CommandHandlerToEntityMethod| N384
  N87 -->|CommandHandlerToEntityMethod| N386
  N88 -->|CommandToCommandHandler| N87
  N89 -->|CommandHandlerToEntityMethod| N346
  N90 -->|CommandToCommandHandler| N89
  N91 -->|CommandHandlerToEntityMethod| N346
  N92 -->|CommandToCommandHandler| N91
  N93 -->|CommandHandlerToEntityMethod| N346
  N94 -->|CommandToCommandHandler| N93
  N95 -->|CommandHandlerToEntityMethod| N346
  N96 -->|CommandToCommandHandler| N95
  N97 -->|CommandHandlerToEntityMethod| N345
  N98 -->|CommandToCommandHandler| N97
  N99 -->|CommandHandlerToEntityMethod| N351
  N100 -->|CommandToCommandHandler| N99
  N101 -->|CommandHandlerToEntityMethod| N359
  N102 -->|CommandToCommandHandler| N101
  N103 -->|CommandHandlerToEntityMethod| N362
  N104 -->|CommandToCommandHandler| N103
  N105 -->|CommandHandlerToEntityMethod| N360
  N106 -->|CommandToCommandHandler| N105
  N107 -->|CommandHandlerToEntityMethod| N354
  N108 -->|CommandToCommandHandler| N107
  N111 -->|CommandHandlerToEntityMethod| N368
  N111 -->|CommandHandlerToEntityMethod| N373
  N111 -->|CommandHandlerToEntityMethod| N374
  N111 -->|CommandHandlerToEntityMethod| N375
  N111 -->|CommandHandlerToEntityMethod| N386
  N111 -->|CommandHandlerToEntityMethod| N387
  N111 -->|CommandHandlerToEntityMethod| N388
  N112 -->|CommandToCommandHandler| N111
  N113 -->|CommandHandlerToEntityMethod| N397
  N114 -->|CommandToCommandHandler| N113
  N115 -->|CommandHandlerToEntityMethod| N398
  N116 -->|CommandToCommandHandler| N115
  N117 -->|CommandHandlerToEntityMethod| N399
  N118 -->|CommandToCommandHandler| N117
  N119 -->|CommandHandlerToEntityMethod| N395
  N119 -->|CommandHandlerToEntityMethod| N401
  N119 -->|CommandHandlerToEntityMethod| N402
  N119 -->|CommandHandlerToEntityMethod| N403
  N120 -->|CommandToCommandHandler| N119
  N121 -->|CommandHandlerToEntityMethod| N396
  N121 -->|CommandHandlerToEntityMethod| N400
  N122 -->|CommandToCommandHandler| N121
  N123 -->|CommandHandlerToEntityMethod| N409
  N123 -->|CommandHandlerToEntityMethod| N410
  N124 -->|CommandToCommandHandler| N123
  N125 -->|CliToCliHandler| N2
  N126 -->|CliToCliHandler| N3
  N127 -->|CliToCliHandler| N4
  N128 -->|CliToCliHandler| N5
  N129 -->|CliToCliHandler| N6
  N130 -->|CliToCliHandler| N7
  N131 -->|CliToCliHandler| N8
  N132 -->|CliToCliHandler| N9
  N133 -->|CliToCliHandler| N10
  N134 -->|CliToCliHandler| N11
  N135 -->|CliToCliHandler| N12
  N136 -->|CliToCliHandler| N13
  N137 -->|QueryToQueryHandler| N14
  N138 -->|QueryToQueryHandler| N15
  N139 -->|QueryToQueryHandler| N16
  N140 -->|QueryToQueryHandler| N17
  N141 -->|QueryToQueryHandler| N18
  N142 -->|QueryToQueryHandler| N19
  N143 -->|QueryToQueryHandler| N20
  N144 -->|QueryToQueryHandler| N21
  N145 -->|QueryToQueryHandler| N22
  N146 -->|QueryToQueryHandler| N23
  N147 -->|QueryToQueryHandler| N24
  N148 -->|QueryToQueryHandler| N25
  N149 -->|QueryToQueryHandler| N26
  N150 -->|QueryToQueryHandler| N27
  N151 -->|QueryToQueryHandler| N28
  N152 -->|QueryToQueryHandler| N29
  N153 -->|QueryToQueryHandler| N30
  N154 -->|QueryToQueryHandler| N31
  N155 -->|QueryToQueryHandler| N32
  N156 -->|QueryToQueryHandler| N33
  N157 -->|QueryToQueryHandler| N34
  N158 -->|QueryToQueryHandler| N35
  N159 -->|QueryToQueryHandler| N36
  N160 -->|QueryToQueryHandler| N37
  N161 -->|QueryToQueryHandler| N38
  N162 -->|QueryToQueryHandler| N39
  N163 -->|QueryToQueryHandler| N40
  N164 -->|QueryToQueryHandler| N41
  N165 -->|QueryToQueryHandler| N42
  N166 -->|QueryToQueryHandler| N43
  N169 -->|DomainEventHandlerToCommand| N45
  N174 -->|DomainEventHandlerToCommand| N66
  N175 -->|DomainEventHandlerToCommand| N74
  N176 -->|DomainEventHandlerToCommand| N76
  N177 -->|DomainEventHandlerToCommand| N47
  N178 -->|DomainEventHandlerToCommand| N90
  N179 -->|DomainEventHandlerToCommand| N92
  N180 -->|DomainEventHandlerToCommand| N82
  N181 -->|DomainEventHandlerToCommand| N51
  N182 -->|DomainEventHandlerToCommand| N76
  N183 -->|DomainEventHandlerToCommand| N94
  N184 -->|DomainEventHandlerToCommand| N96
  N185 -->|DomainEventHandlerToCommand| N82
  N186 -->|DomainEventHandlerToCommand| N67
  N187 -->|DomainEventHandlerToCommand| N67
  N193 -->|DomainEventHandlerToCli| N127
  N194 -->|DomainEventHandlerToCommand| N64
  N194 -->|DomainEventHandlerToCli| N127
  N196 -->|DomainEventHandlerToCommand| N70
  N197 -->|DomainEventHandlerToCommand| N69
  N206 -->|DomainEventHandlerToCommand| N61
  N208 -->|DomainEventHandlerToCommand| N72
  N208 -->|DomainEventHandlerToQuery| N149
  N210 -->|DomainEventHandlerToCommand| N67
  N211 -->|DomainEventHandlerToCommand| N67
  N212 -->|DomainEventHandlerToCommand| N67
  N214 -->|DomainEventHandlerToCommand| N67
  N215 -->|DomainEventHandlerToCommand| N98
  N216 -->|DomainEventHandlerToCommand| N100
  N217 -->|DomainEventHandlerToCli| N128
  N220 -->|DomainEventHandlerToCommand| N67
  N221 -->|DomainEventHandlerToCommand| N67
  N222 -->|DomainEventHandlerToCommand| N59
  N223 -->|DomainEventHandlerToCli| N126
  N224 -->|DomainEventHandlerToCommand| N86
  N227 -->|DomainEventHandlerToCommand| N55
  N227 -->|DomainEventHandlerToCommand| N57
  N228 -->|DomainEventHandlerToCommand| N110
  N229 -->|DomainEventHandlerToCommand| N78
  N231 -->|DomainEventHandlerToCommand| N78
  N232 -->|DomainEventHandlerToCommand| N49
  N233 -->|DomainEventHandlerToCommand| N53
  N233 -->|DomainEventHandlerToQuery| N152
  N236 -->|DomainEventHandlerToCommand| N80
  N237 -->|DomainEventHandlerToCommand| N80
  N238 -->|DomainEventHandlerToCommand| N118
  N238 -->|DomainEventHandlerToCli| N131
  N238 -->|DomainEventHandlerToQuery| N161
  N239 -->|DomainEventHandlerToCli| N130
  N240 -->|DomainEventHandlerToCommand| N108
  N240 -->|DomainEventHandlerToCli| N129
  N243 -->|DomainEventHandlerToCommand| N109
  N244 -->|DomainEventHandlerToCommand| N84
  N248 -->|DomainEventHandlerToCommand| N63
  N249 -->|DomainEventHandlerToCommand| N88
  N250 -->|DomainEventHandlerToCli| N125
  N251 -->|DomainEventHandlerToCommand| N102
  N251 -->|DomainEventHandlerToCommand| N104
  N251 -->|DomainEventHandlerToCommand| N124
  N253 -->|DomainEventHandlerToCommand| N85
  N254 -->|DomainEventHandlerToCommand| N122
  N255 -->|DomainEventHandlerToCommand| N112
  N256 -->|DomainEventHandlerToCommand| N106
  N256 -->|DomainEventHandlerToCommand| N114
  N257 -->|DomainEventHandlerToCommand| N114
  N257 -->|DomainEventHandlerToCli| N132
  N257 -->|DomainEventHandlerToQuery| N161
  N258 -->|DomainEventHandlerToCommand| N116
  N258 -->|DomainEventHandlerToCli| N133
  N258 -->|DomainEventHandlerToCli| N134
  N258 -->|DomainEventHandlerToCli| N135
  N258 -->|DomainEventHandlerToCli| N136
  N258 -->|DomainEventHandlerToQuery| N166
  N259 -->|DomainEventHandlerToCommand| N120
  N265 -->|EntityMethodToDomainEvent| N273
  N266 -->|EntityMethodToDomainEvent| N271
  N267 -->|DomainEventToHandler| N167
  N268 -->|DomainEventToHandler| N168
  N269 -->|DomainEventToHandler| N169
  N270 -->|DomainEventToHandler| N170
  N271 -->|DomainEventToHandler| N171
  N272 -->|DomainEventToHandler| N172
  N273 -->|DomainEventToHandler| N173
  N274 -->|DomainEventToHandler| N174
  N274 -->|DomainEventToHandler| N175
  N275 -->|DomainEventToHandler| N176
  N275 -->|DomainEventToHandler| N177
  N276 -->|DomainEventToHandler| N178
  N277 -->|DomainEventToHandler| N179
  N278 -->|DomainEventToHandler| N180
  N278 -->|DomainEventToHandler| N181
  N279 -->|DomainEventToHandler| N182
  N280 -->|DomainEventToHandler| N183
  N281 -->|DomainEventToHandler| N184
  N282 -->|DomainEventToHandler| N185
  N283 -->|DomainEventToHandler| N186
  N284 -->|DomainEventToHandler| N187
  N285 -->|EntityMethodToDomainEvent| N286
  N285 -->|EntityMethodToDomainEvent| N287
  N285 -->|EntityMethodToDomainEvent| N288
  N285 -->|EntityMethodToDomainEvent| N289
  N285 -->|EntityMethodToDomainEvent| N290
  N286 -->|DomainEventToHandler| N188
  N287 -->|DomainEventToHandler| N189
  N288 -->|DomainEventToHandler| N190
  N289 -->|DomainEventToHandler| N191
  N290 -->|DomainEventToHandler| N192
  N291 -->|EntityMethodToDomainEvent| N298
  N292 -->|EntityMethodToDomainEvent| N300
  N293 -->|EntityMethodToDomainEvent| N297
  N295 -->|DomainEventToHandler| N193
  N296 -->|DomainEventToHandler| N194
  N297 -->|DomainEventToHandler| N195
  N298 -->|DomainEventToHandler| N196
  N299 -->|DomainEventToHandler| N197
  N300 -->|DomainEventToHandler| N198
  N301 -->|DomainEventToHandler| N199
  N302 -->|DomainEventToHandler| N200
  N303 -->|EntityMethodToDomainEvent| N310
  N304 -->|DomainEventToHandler| N201
  N305 -->|DomainEventToHandler| N202
  N306 -->|DomainEventToHandler| N203
  N307 -->|DomainEventToHandler| N204
  N308 -->|DomainEventToHandler| N205
  N309 -->|DomainEventToHandler| N206
  N310 -->|DomainEventToHandler| N207
  N313 -->|DomainEventToHandler| N208
  N322 -->|EntityMethodToDomainEvent| N331
  N323 -->|EntityMethodToDomainEvent| N332
  N324 -->|EntityMethodToDomainEvent| N333
  N325 -->|EntityMethodToDomainEvent| N335
  N326 -->|EntityMethodToDomainEvent| N339
  N327 -->|EntityMethodToDomainEvent| N340
  N328 -->|EntityMethodToDomainEvent| N334
  N329 -->|EntityMethodToDomainEvent| N330
  N330 -->|DomainEventToHandler| N209
  N331 -->|DomainEventToHandler| N210
  N332 -->|DomainEventToHandler| N211
  N333 -->|DomainEventToHandler| N212
  N334 -->|DomainEventToHandler| N213
  N335 -->|DomainEventToHandler| N214
  N336 -->|DomainEventToHandler| N215
  N336 -->|DomainEventToHandler| N216
  N336 -->|DomainEventToHandler| N217
  N337 -->|DomainEventToHandler| N218
  N338 -->|DomainEventToHandler| N219
  N339 -->|DomainEventToHandler| N220
  N340 -->|DomainEventToHandler| N221
  N341 -->|DomainEventToHandler| N225
  N342 -->|DomainEventToHandler| N226
  N343 -->|DomainEventToHandler| N227
  N343 -->|DomainEventToHandler| N228
  N345 -->|EntityMethodToDomainEvent| N347
  N347 -->|DomainEventToHandler| N229
  N347 -->|DomainEventToHandler| N230
  N348 -->|DomainEventToHandler| N231
  N348 -->|DomainEventToHandler| N232
  N348 -->|DomainEventToHandler| N233
  N349 -->|DomainEventToHandler| N234
  N350 -->|DomainEventToHandler| N235
  N351 -->|EntityMethodToDomainEvent| N352
  N352 -->|DomainEventToHandler| N236
  N353 -->|DomainEventToHandler| N237
  N355 -->|DomainEventToHandler| N239
  N356 -->|DomainEventToHandler| N240
  N357 -->|DomainEventToHandler| N241
  N358 -->|DomainEventToHandler| N242
  N360 -->|EntityMethodToDomainEvent| N361
  N361 -->|DomainEventToHandler| N238
  N363 -->|DomainEventToHandler| N243
  N363 -->|DomainEventToHandler| N244
  N364 -->|DomainEventToHandler| N245
  N365 -->|DomainEventToHandler| N246
  N389 -->|DomainEventToHandler| N247
  N390 -->|DomainEventToHandler| N248
  N390 -->|DomainEventToHandler| N249
  N390 -->|DomainEventToHandler| N250
  N390 -->|DomainEventToHandler| N251
  N391 -->|DomainEventToHandler| N252
  N392 -->|DomainEventToHandler| N222
  N392 -->|DomainEventToHandler| N223
  N392 -->|DomainEventToHandler| N224
  N393 -->|DomainEventToHandler| N253
  N394 -->|DomainEventToHandler| N254
  N396 -->|EntityMethodToDomainEvent| N407
  N397 -->|EntityMethodToDomainEvent| N404
  N398 -->|EntityMethodToDomainEvent| N408
  N399 -->|EntityMethodToDomainEvent| N406
  N401 -->|EntityMethodToDomainEvent| N405
  N404 -->|DomainEventToHandler| N255
  N405 -->|DomainEventToHandler| N256
  N406 -->|DomainEventToHandler| N257
  N407 -->|DomainEventToHandler| N258
  N408 -->|DomainEventToHandler| N259
  classDef cli fill:#86EFAC,stroke:#15803D,color:#0F172A
  classDef clihandler fill:#22C55E,stroke:#166534,color:#F0FDF4
  classDef command fill:#FDBA74,stroke:#C2410C,color:#111827
  classDef commandhandler fill:#F97316,stroke:#9A3412,color:#111827
  classDef domainevent fill:#FECACA,stroke:#B91C1C,color:#111827
  classDef domaineventhandler fill:#F87171,stroke:#991B1B,color:#111827
  classDef entitymethod fill:#F3F4F6,stroke:#6B7280,color:#111827
  classDef query fill:#93C5FD,stroke:#1D4ED8,color:#0F172A
  classDef queryhandler fill:#3B82F6,stroke:#1E40AF,color:#F8FAFC
  classDef querysendermethod fill:#BFDBFE,stroke:#1D4ED8,color:#0F172A
