flowchart TD
  N1[/&lt;anonymous&gt;/]
  class N1 querysendermethod
  N2[[CleanTempFilesCliHandler]]
  class N2 clihandler
  N3[[DeleteVideoFileResourcesCliHandler]]
  class N3 clihandler
  N4[[RefreshLoginSessionCliHandler]]
  class N4 clihandler
  N5[[RemoveVideoSearchIndexCliHandler]]
  class N5 clihandler
  N6[[CreateUploadSessionTempDirCliHandler]]
  class N6 clihandler
  N7[[DeleteUploadSessionTempDirCliHandler]]
  class N7 clihandler
  N8[[EncryptHlsVariantWithKeyCliHandler]]
  class N8 clihandler
  N9[[GenerateEncryptedMasterByVariantsCliHandler]]
  class N9 clihandler
  N10[[GenerateVideoAbrMasterCliHandler]]
  class N10 clihandler
  N11[[MergeUploadToMp4ByPathCliHandler]]
  class N11 clihandler
  N12[[TranscodeVideoFileToAbrByPathCliHandler]]
  class N12 clihandler
  N13[[UploadVideoAbrOutputCliHandler]]
  class N13 clihandler
  N14[[UniqueCategoryCodeQryHandler]]
  class N14 queryhandler
  N15[[GetUserActionsByVideoIdQryHandler]]
  class N15 queryhandler
  N16[[UniqueCustomerActionTypeQryHandler]]
  class N16 queryhandler
  N17[[CheckFocusStatusQryHandler]]
  class N17 queryhandler
  N18[[GetCustomerProfileQryHandler]]
  class N18 queryhandler
  N19[[UniqueCustomerProfileEmailQryHandler]]
  class N19 queryhandler
  N20[[UniqueCustomerProfileNickNameQryHandler]]
  class N20 queryhandler
  N21[[UniqueCustomerProfilePhoneQryHandler]]
  class N21 queryhandler
  N22[[GetCustomerVideoSeriesInfoQryHandler]]
  class N22 queryhandler
  N23[[CheckNicknameExistsQryHandler]]
  class N23 queryhandler
  N24[[CheckUserExistsQryHandler]]
  class N24 queryhandler
  N25[[UniqueUserEmailQryHandler]]
  class N25 queryhandler
  N26[[UniqueUserPhoneQryHandler]]
  class N26 queryhandler
  N27[[GetRecentPasswordFailureCountQryHandler]]
  class N27 queryhandler
  N28[[GetVideoInfoQryHandler]]
  class N28 queryhandler
  N29[[UniqueVideoFileVariantQryHandler]]
  class N29 queryhandler
  N30[[GetCommentByIdQryHandler]]
  class N30 queryhandler
  N31[[CheckDanmukuExistsQryHandler]]
  class N31 queryhandler
  N32[[GetDanmukuOwnerQryHandler]]
  class N32 queryhandler
  N33[[GetVideoPostInfoQryHandler]]
  class N33 queryhandler
  N34[[ListVideoHlsEncryptKeysByPostFileQryHandler]]
  class N34 queryhandler
  N35[[ListVideoHlsKeyTokensByPostFileQryHandler]]
  class N35 queryhandler
  N36[[GetUploadedTempPathsQryHandler]]
  class N36 queryhandler
  N37[[UniqueVideoHlsEncryptKeyQryHandler]]
  class N37 queryhandler
  N38[[UniqueVideoHlsKeyTokenQryHandler]]
  class N38 queryhandler
  N39[[UniqueVideoFilePostQryHandler]]
  class N39 queryhandler
  N40[[UniqueVideoFilePostUploadIdQryHandler]]
  class N40 queryhandler
  N41[[UniqueVideoFilePostVariantQryHandler]]
  class N41 queryhandler
  N42[[GetVideoPostProcessingEncryptContextQryHandler]]
  class N42 queryhandler
  N43[[ListVideoPostProcessingFilesForSyncQryHandler]]
  class N43 queryhandler
  N44[[ListVideoPostProcessingVariantsForEncryptMasterQryHandler]]
  class N44 queryhandler
  N45[[UniqueVideoPostProcessingFileQryHandler]]
  class N45 queryhandler
  N46[[UniqueVideoPostProcessingQryHandler]]
  class N46 queryhandler
  N47[[UniqueVideoPostProcessingVariantQryHandler]]
  class N47 queryhandler
  N48[[UniqueVideoQualityPolicyQryHandler]]
  class N48 queryhandler
  N49[[GetUploadSessionTempPathQryHandler]]
  class N49 queryhandler
  N50[[FinalizeCategoryAfterCreateCmd.Handler]]
  class N50 commandhandler
  N51{{FinalizeCategoryAfterCreateCmd.Request}}
  class N51 command
  N52[[SendCollectMessageCmd.Handler]]
  class N52 commandhandler
  N53{{SendCollectMessageCmd.Request}}
  class N53 command
  N54[[SendCommentMessageCmd.Handler]]
  class N54 commandhandler
  N55{{SendCommentMessageCmd.Request}}
  class N55 command
  N56[[SendLikeMessageCmd.Handler]]
  class N56 commandhandler
  N57{{SendLikeMessageCmd.Request}}
  class N57 command
  N58[[SendReplyMessageCmd.Handler]]
  class N58 commandhandler
  N59{{SendReplyMessageCmd.Request}}
  class N59 command
  N60[[SendVideoAuditFailedMessageCmd.Handler]]
  class N60 commandhandler
  N61{{SendVideoAuditFailedMessageCmd.Request}}
  class N61 command
  N62[[SendVideoAuditPassedMessageCmd.Handler]]
  class N62 commandhandler
  N63{{SendVideoAuditPassedMessageCmd.Request}}
  class N63 command
  N64[[AdjustAuthorCoinAfterDeleteCmd.Handler]]
  class N64 commandhandler
  N65{{AdjustAuthorCoinAfterDeleteCmd.Request}}
  class N65 command
  N66[[CreateCustomerProfileCmd.Handler]]
  class N66 commandhandler
  N67{{CreateCustomerProfileCmd.Request}}
  class N67 command
  N68[[RewardUserForVideoCmd.Handler]]
  class N68 commandhandler
  N69{{RewardUserForVideoCmd.Request}}
  class N69 command
  N70[[SpendCoinsForNicknameChangeCmd.Handler]]
  class N70 commandhandler
  N71{{SpendCoinsForNicknameChangeCmd.Request}}
  class N71 command
  N72[[TransferCoinCmd.Handler]]
  class N72 commandhandler
  N73{{TransferCoinCmd.Request}}
  class N73 command
  N74[[UpdateStatisticsInfoCmd.Handler]]
  class N74 commandhandler
  N75{{UpdateStatisticsInfoCmd.Request}}
  class N75 command
  N76[[ChangeUserPhoneCmd.Handler]]
  class N76 commandhandler
  N77{{ChangeUserPhoneCmd.Request}}
  class N77 command
  N78[[RelationProfileCmd.Handler]]
  class N78 commandhandler
  N79{{RelationProfileCmd.Request}}
  class N79 command
  N80[[RecordAbnormalOperationCmd.Handler]]
  class N80 commandhandler
  N81{{RecordAbnormalOperationCmd.Request}}
  class N81 command
  N82[[ApplyVideoCoinCountDeltaCmd.Handler]]
  class N82 commandhandler
  N83{{ApplyVideoCoinCountDeltaCmd.Request}}
  class N83 command
  N84[[ApplyVideoCollectCountDeltaCmd.Handler]]
  class N84 commandhandler
  N85{{ApplyVideoCollectCountDeltaCmd.Request}}
  class N85 command
  N86[[ApplyVideoCommentCountDeltaCmd.Handler]]
  class N86 commandhandler
  N87{{ApplyVideoCommentCountDeltaCmd.Request}}
  class N87 command
  N88[[ApplyVideoDanmukuCountDeltaCmd.Handler]]
  class N88 commandhandler
  N89{{ApplyVideoDanmukuCountDeltaCmd.Request}}
  class N89 command
  N90[[ApplyVideoLikeCountDeltaCmd.Handler]]
  class N90 commandhandler
  N91{{ApplyVideoLikeCountDeltaCmd.Request}}
  class N91 command
  N92[[ApplyVideoPlayCountDeltaCmd.Handler]]
  class N92 commandhandler
  N93{{ApplyVideoPlayCountDeltaCmd.Request}}
  class N93 command
  N94[[ChangeVideoInteractionCmd.Handler]]
  class N94 commandhandler
  N95{{ChangeVideoInteractionCmd.Request}}
  class N95 command
  N96[[DeleteVideoCmd.Handler]]
  class N96 commandhandler
  N97{{DeleteVideoCmd.Request}}
  class N97 command
  N98[[TransferVideoToProductionCmd.Handler]]
  class N98 commandhandler
  N99{{TransferVideoToProductionCmd.Request}}
  class N99 command
  N100[[ApplyCustomerDislikedCommentCmd.Handler]]
  class N100 commandhandler
  N101{{ApplyCustomerDislikedCommentCmd.Request}}
  class N101 command
  N102[[ApplyCustomerLikedCommentCmd.Handler]]
  class N102 commandhandler
  N103{{ApplyCustomerLikedCommentCmd.Request}}
  class N103 command
  N104[[ApplyCustomerUndislikedCommentCmd.Handler]]
  class N104 commandhandler
  N105{{ApplyCustomerUndislikedCommentCmd.Request}}
  class N105 command
  N106[[ApplyCustomerUnlikedCommentCmd.Handler]]
  class N106 commandhandler
  N107{{ApplyCustomerUnlikedCommentCmd.Request}}
  class N107 command
  N108[[BatchDeleteCommentCmd.Handler]]
  class N108 commandhandler
  N109{{BatchDeleteCommentCmd.Request}}
  class N109 command
  N110[[BatchDeleteDanmukuCmd.Handler]]
  class N110 commandhandler
  N111{{BatchDeleteDanmukuCmd.Request}}
  class N111 command
  N112[[BindVideoHlsEncryptKeyToVideoCmd.Handler]]
  class N112 commandhandler
  N113{{BindVideoHlsEncryptKeyToVideoCmd.Request}}
  class N113 command
  N114[[BindVideoHlsKeyTokenToVideoCmd.Handler]]
  class N114 commandhandler
  N115{{BindVideoHlsKeyTokenToVideoCmd.Request}}
  class N115 command
  N116[[GenerateVideoPostQualityKeyCmd.Handler]]
  class N116 commandhandler
  N117{{GenerateVideoPostQualityKeyCmd.Request}}
  class N117 command
  N118[[InitTempAndStartUploadingCmd.Handler]]
  class N118 commandhandler
  N119{{InitTempAndStartUploadingCmd.Request}}
  class N119 command
  N120[[AddPlayHistoryCmd.Handler]]
  class N120 commandhandler
  N121{{AddPlayHistoryCmd.Request}}
  class N121 command
  N122[[AuditVideoPostCmd.Handler]]
  class N122 commandhandler
  N123{{AuditVideoPostCmd.Request}}
  class N123 command
  N124[[SyncVideoPostProcessStatusCmd.Handler]]
  class N124 commandhandler
  N125{{SyncVideoPostProcessStatusCmd.Request}}
  class N125 command
  N126[[ApplyVideoPostProcessingEncryptResultCmd.Handler]]
  class N126 commandhandler
  N127{{ApplyVideoPostProcessingEncryptResultCmd.Request}}
  class N127 command
  N128[[ApplyVideoPostProcessingTranscodeResultCmd.Handler]]
  class N128 commandhandler
  N129{{ApplyVideoPostProcessingTranscodeResultCmd.Request}}
  class N129 command
  N130[[ApplyVideoPostProcessingVariantEncryptResultCmd.Handler]]
  class N130 commandhandler
  N131{{ApplyVideoPostProcessingVariantEncryptResultCmd.Request}}
  class N131 command
  N132[[PrepareVideoPostProcessingEncryptContextCmd.Handler]]
  class N132 commandhandler
  N133{{PrepareVideoPostProcessingEncryptContextCmd.Request}}
  class N133 command
  N134[[StartVideoPostProcessingCmd.Handler]]
  class N134 commandhandler
  N135{{StartVideoPostProcessingCmd.Request}}
  class N135 command
  N136[[SetVideoQualityPolicyCmd.Handler]]
  class N136 commandhandler
  N137{{SetVideoQualityPolicyCmd.Request}}
  class N137 command
  N138{{CleanTempFilesCli.Request}}
  class N138 cli
  N139{{DeleteVideoFileResourcesCli.Request}}
  class N139 cli
  N140{{RefreshLoginSessionCli.Request}}
  class N140 cli
  N141{{RemoveVideoSearchIndexCli.Request}}
  class N141 cli
  N142{{CreateUploadSessionTempDirCli.Request}}
  class N142 cli
  N143{{DeleteUploadSessionTempDirCli.Request}}
  class N143 cli
  N144{{EncryptHlsVariantWithKeyCli.Request}}
  class N144 cli
  N145{{GenerateEncryptedMasterByVariantsCli.Request}}
  class N145 cli
  N146{{GenerateVideoAbrMasterCli.Request}}
  class N146 cli
  N147{{MergeUploadToMp4ByPathCli.Request}}
  class N147 cli
  N148{{TranscodeVideoFileToAbrByPathCli.Request}}
  class N148 cli
  N149{{UploadVideoAbrOutputCli.Request}}
  class N149 cli
  N150{{UniqueCategoryCodeQry.Request}}
  class N150 query
  N151{{GetUserActionsByVideoIdQry.Request}}
  class N151 query
  N152{{UniqueCustomerActionTypeQry.Request}}
  class N152 query
  N153{{CheckFocusStatusQry.Request}}
  class N153 query
  N154{{GetCustomerProfileQry.Request}}
  class N154 query
  N155{{UniqueCustomerProfileEmailQry.Request}}
  class N155 query
  N156{{UniqueCustomerProfileNickNameQry.Request}}
  class N156 query
  N157{{UniqueCustomerProfilePhoneQry.Request}}
  class N157 query
  N158{{GetCustomerVideoSeriesInfoQry.Request}}
  class N158 query
  N159{{CheckNicknameExistsQry.Request}}
  class N159 query
  N160{{CheckUserExistsQry.Request}}
  class N160 query
  N161{{UniqueUserEmailQry.Request}}
  class N161 query
  N162{{UniqueUserPhoneQry.Request}}
  class N162 query
  N163{{GetRecentPasswordFailureCountQry.Request}}
  class N163 query
  N164{{GetVideoInfoQry.Request}}
  class N164 query
  N165{{UniqueVideoFileVariantQry.Request}}
  class N165 query
  N166{{GetCommentByIdQry.Request}}
  class N166 query
  N167{{CheckDanmukuExistsQry.Request}}
  class N167 query
  N168{{GetDanmukuOwnerQry.Request}}
  class N168 query
  N169{{GetVideoPostInfoQry.Request}}
  class N169 query
  N170{{ListVideoHlsEncryptKeysByPostFileQry.Request}}
  class N170 query
  N171{{ListVideoHlsKeyTokensByPostFileQry.Request}}
  class N171 query
  N172{{GetUploadedTempPathsQry.Request}}
  class N172 query
  N173{{UniqueVideoHlsEncryptKeyQry.Request}}
  class N173 query
  N174{{UniqueVideoHlsKeyTokenQry.Request}}
  class N174 query
  N175{{UniqueVideoFilePostQry.Request}}
  class N175 query
  N176{{UniqueVideoFilePostUploadIdQry.Request}}
  class N176 query
  N177{{UniqueVideoFilePostVariantQry.Request}}
  class N177 query
  N178{{GetVideoPostProcessingEncryptContextQry.Request}}
  class N178 query
  N179{{ListVideoPostProcessingFilesForSyncQry.Request}}
  class N179 query
  N180{{ListVideoPostProcessingVariantsForEncryptMasterQry.Request}}
  class N180 query
  N181{{UniqueVideoPostProcessingFileQry.Request}}
  class N181 query
  N182{{UniqueVideoPostProcessingQry.Request}}
  class N182 query
  N183{{UniqueVideoPostProcessingVariantQry.Request}}
  class N183 query
  N184{{UniqueVideoQualityPolicyQry.Request}}
  class N184 query
  N185{{GetUploadSessionTempPathQry.Request}}
  class N185 query
  N186[[CategoryBasicInfoUpdatedDomainEventSubscriber::on]]
  class N186 domaineventhandler
  N187[[CategoryCodeChangedDomainEventSubscriber::on]]
  class N187 domaineventhandler
  N188[[CategoryCreatedDomainEventSubscriber::on1]]
  class N188 domaineventhandler
  N189[[CategoryDeletedDomainEventSubscriber::on]]
  class N189 domaineventhandler
  N190[[CategoryNodePathUpdatedDomainEventSubscriber::on]]
  class N190 domaineventhandler
  N191[[CategoryParentChangedDomainEventSubscriber::on]]
  class N191 domaineventhandler
  N192[[CategorySortChangedDomainEventSubscriber::on]]
  class N192 domaineventhandler
  N193[[CustomerCoinGivenDomainEventSubscriber::on1]]
  class N193 domaineventhandler
  N194[[CustomerCoinGivenDomainEventSubscriber::on2]]
  class N194 domaineventhandler
  N195[[CustomerCollectedVideoDomainEventSubscriber::on]]
  class N195 domaineventhandler
  N196[[CustomerCollectedVideoDomainEventSubscriber::onSendMessage]]
  class N196 domaineventhandler
  N197[[CustomerDislikedCommentDomainEventSubscriber::on]]
  class N197 domaineventhandler
  N198[[CustomerLikedCommentDomainEventSubscriber::on]]
  class N198 domaineventhandler
  N199[[CustomerLikedVideoDomainEventSubscriber::on]]
  class N199 domaineventhandler
  N200[[CustomerLikedVideoDomainEventSubscriber::onSendMessage]]
  class N200 domaineventhandler
  N201[[CustomerUncollectedVideoDomainEventSubscriber::on]]
  class N201 domaineventhandler
  N202[[CustomerUndislikedCommentDomainEventSubscriber::on]]
  class N202 domaineventhandler
  N203[[CustomerUnlikedCommentDomainEventSubscriber::on]]
  class N203 domaineventhandler
  N204[[CustomerUnlikedVideoDomainEventSubscriber::on]]
  class N204 domaineventhandler
  N205[[UserFocusedDomainEventSubscriber::on]]
  class N205 domaineventhandler
  N206[[UserUnfocusedDomainEventSubscriber::on]]
  class N206 domaineventhandler
  N207[[CustomerMessageCollectionCreatedDomainEventSubscriber::on]]
  class N207 domaineventhandler
  N208[[CustomerMessageCommentMentionCreatedDomainEventSubscriber::on]]
  class N208 domaineventhandler
  N209[[CustomerMessageLikeCreatedDomainEventSubscriber::on]]
  class N209 domaineventhandler
  N210[[CustomerMessagePrivateCreatedDomainEventSubscriber::on]]
  class N210 domaineventhandler
  N211[[CustomerMessageSystemCreatedDomainEventSubscriber::on]]
  class N211 domaineventhandler
  N212[[CustomerAvatarUpdatedDomainEventSubscriber::on]]
  class N212 domaineventhandler
  N213[[CustomerNicknameUpdatedDomainEventSubscriber::on]]
  class N213 domaineventhandler
  N214[[CustomerProfileCoinsRewardedDomainEventSubscriber::on]]
  class N214 domaineventhandler
  N215[[CustomerProfileCreatedDomainEventSubscriber::on1]]
  class N215 domaineventhandler
  N216[[CustomerProfilePhoneChangedDomainEventSubscriber::on]]
  class N216 domaineventhandler
  N217[[CustomerProfileRewardCoinsReclaimedDomainEventSubscriber::on]]
  class N217 domaineventhandler
  N218[[CustomerProfileUpdatedDomainEventSubscriber::on]]
  class N218 domaineventhandler
  N219[[StatisticsCountUpdatedDomainEventSubscriber::on]]
  class N219 domaineventhandler
  N220[[AccountDisabledDomainEventSubscriber::on]]
  class N220 domaineventhandler
  N221[[AccountEnabledDomainEventSubscriber::on]]
  class N221 domaineventhandler
  N222[[LoginInfoUpdatedDomainEventSubscriber::on]]
  class N222 domaineventhandler
  N223[[PasswordChangedDomainEventSubscriber::on]]
  class N223 domaineventhandler
  N224[[RelationshipBoundDomainEventSubscriber::on]]
  class N224 domaineventhandler
  N225[[UserCreatedDomainEventSubscriber::on]]
  class N225 domaineventhandler
  N226[[UserPhoneChangedDomainEventSubscriber::on]]
  class N226 domaineventhandler
  N227[[PasswordInputFailedDomainEventSubscriber::on]]
  class N227 domaineventhandler
  N228[[VideoBasicsSyncedDomainEventSubscriber::on]]
  class N228 domaineventhandler
  N229[[VideoCoinCountDeltaAppliedDomainEventSubscriber::on]]
  class N229 domaineventhandler
  N230[[VideoCollectCountDeltaAppliedDomainEventSubscriber::on]]
  class N230 domaineventhandler
  N231[[VideoCommentCountDeltaAppliedDomainEventSubscriber::on]]
  class N231 domaineventhandler
  N232[[VideoCreatedDomainEventSubscriber::on]]
  class N232 domaineventhandler
  N233[[VideoDanmukuCountDeltaAppliedDomainEventSubscriber::on]]
  class N233 domaineventhandler
  N234[[VideoDeletedDomainEventSubscriber::cleanupComments]]
  class N234 domaineventhandler
  N235[[VideoDeletedDomainEventSubscriber::cleanupDanmaku]]
  class N235 domaineventhandler
  N236[[VideoDeletedDomainEventSubscriber::removeSearchIndex]]
  class N236 domaineventhandler
  N237[[VideoInteractionChangedDomainEventSubscriber::on]]
  class N237 domaineventhandler
  N238[[VideoLastPlayTimeAttachedDomainEventSubscriber::on]]
  class N238 domaineventhandler
  N239[[VideoLikeCountDeltaAppliedDomainEventSubscriber::on]]
  class N239 domaineventhandler
  N240[[VideoPlayCountDeltaAppliedDomainEventSubscriber::on]]
  class N240 domaineventhandler
  N241[[VideoPostDeletedDomainEventSubscriber::adjustAuthorCoin]]
  class N241 domaineventhandler
  N242[[VideoPostDeletedDomainEventSubscriber::deletePhysicalFiles]]
  class N242 domaineventhandler
  N243[[VideoPostDeletedDomainEventSubscriber::removeVideo]]
  class N243 domaineventhandler
  N244[[VideoRecommendedDomainEventSubscriber::on]]
  class N244 domaineventhandler
  N245[[VideoUnrecommendedDomainEventSubscriber::on]]
  class N245 domaineventhandler
  N246[[VideoAuditTraceRecordedDomainEventSubscriber::sendAuditMessage]]
  class N246 domaineventhandler
  N247[[VideoAuditTraceRecordedDomainEventSubscriber::updateVideoStatus]]
  class N247 domaineventhandler
  N248[[CommentDeletedDomainEventSubscriber::on]]
  class N248 domaineventhandler
  N249[[CommentDeletedDomainEventSubscriber::on1]]
  class N249 domaineventhandler
  N250[[CommentPostedDomainEventSubscriber::on]]
  class N250 domaineventhandler
  N251[[CommentPostedDomainEventSubscriber::on1]]
  class N251 domaineventhandler
  N252[[CommentPostedDomainEventSubscriber::on2]]
  class N252 domaineventhandler
  N253[[CommentToppedDomainEventSubscriber::on]]
  class N253 domaineventhandler
  N254[[CommentUntoppedDomainEventSubscriber::on]]
  class N254 domaineventhandler
  N255[[DanmukuDeletedDomainEventSubscriber::on]]
  class N255 domaineventhandler
  N256[[DanmukuPostedDomainEventSubscriber::on]]
  class N256 domaineventhandler
  N257[[VideoPostQualityKeyGeneratedDomainEventSubscriber::on]]
  class N257 domaineventhandler
  N258[[UploadSessionAbortedDomainEventSubscriber::on]]
  class N258 domaineventhandler
  N259[[UploadSessionCreatedDomainEventSubscriber::on]]
  class N259 domaineventhandler
  N260[[VideoFileUploadSessionChunkUploadedDomainEventSubscriber::on]]
  class N260 domaineventhandler
  N261[[VideoFileUploadSessionMarkedDoneDomainEventSubscriber::on]]
  class N261 domaineventhandler
  N262[[VideoHlsKeyTokenIssuedDomainEventSubscriber::addPlayHistoryCmd]]
  class N262 domaineventhandler
  N263[[VideoHlsKeyTokenIssuedDomainEventSubscriber::applyVideoPlayCountDelta]]
  class N263 domaineventhandler
  N264[[VideoPlayHistoryCreatedDomainEventSubscriber::on]]
  class N264 domaineventhandler
  N265[[VideoPlayHistoryProgressUpdatedDomainEventSubscriber::on]]
  class N265 domaineventhandler
  N266[[VideoAuditFailedDomainEventSubscriber::on]]
  class N266 domaineventhandler
  N267[[VideoAuditPassedDomainEventSubscriber::bindVideoHlsEncryptKeyToVideo]]
  class N267 domaineventhandler
  N268[[VideoAuditPassedDomainEventSubscriber::bindVideoHlsKeyTokenToVideo]]
  class N268 domaineventhandler
  N269[[VideoAuditPassedDomainEventSubscriber::on2]]
  class N269 domaineventhandler
  N270[[VideoAuditPassedDomainEventSubscriber::rewardUserForVideo]]
  class N270 domaineventhandler
  N271[[VideoAuditPassedDomainEventSubscriber::setVideoQualityPolicy]]
  class N271 domaineventhandler
  N272[[VideoAuditPassedDomainEventSubscriber::transferVideoToProduction]]
  class N272 domaineventhandler
  N273[[VideoPostCreatedDomainEventSubscriber::on]]
  class N273 domaineventhandler
  N274[[VideoPostInteractionChangedDomainEventSubscriber::on]]
  class N274 domaineventhandler
  N275[[VideoPostTranscodingRequestedDomainEventSubscriber::on]]
  class N275 domaineventhandler
  N276[[VideoPostProcessingCompletedDomainEventSubscriber::on]]
  class N276 domaineventhandler
  N277[[VideoPostProcessingEncryptContextPreparedDomainEventSubscriber::on]]
  class N277 domaineventhandler
  N278[[VideoPostProcessingFileEncryptCompletedDomainEventSubscriber::on]]
  class N278 domaineventhandler
  N279[[VideoPostProcessingStartedDomainEventSubscriber::on]]
  class N279 domaineventhandler
  N280[[VideoPostProcessingTranscodeCompletedDomainEventSubscriber::on]]
  class N280 domaineventhandler
  N281(Category::&lt;get-id&gt;)
  class N281 entitymethod
  N282(Category::&lt;get-nodePath&gt;)
  class N282 entitymethod
  N283(Category::&lt;get-parentId&gt;)
  class N283 entitymethod
  N284(Category::&lt;get-sort&gt;)
  class N284 entitymethod
  N285(Category::addSort)
  class N285 entitymethod
  N286(Category::changeSort)
  class N286 entitymethod
  N287(Category::updateNodePath)
  class N287 entitymethod
  N288((CategoryBasicInfoUpdatedDomainEvent))
  class N288 domainevent
  N289((CategoryCodeChangedDomainEvent))
  class N289 domainevent
  N290((CategoryCreatedDomainEvent))
  class N290 domainevent
  N291((CategoryDeletedDomainEvent))
  class N291 domainevent
  N292((CategoryNodePathUpdatedDomainEvent))
  class N292 domainevent
  N293((CategoryParentChangedDomainEvent))
  class N293 domainevent
  N294((CategorySortChangedDomainEvent))
  class N294 domainevent
  N295((CustomerCoinGivenDomainEvent))
  class N295 domainevent
  N296((CustomerCollectedVideoDomainEvent))
  class N296 domainevent
  N297((CustomerDislikedCommentDomainEvent))
  class N297 domainevent
  N298((CustomerLikedCommentDomainEvent))
  class N298 domainevent
  N299((CustomerLikedVideoDomainEvent))
  class N299 domainevent
  N300((CustomerUncollectedVideoDomainEvent))
  class N300 domainevent
  N301((CustomerUndislikedCommentDomainEvent))
  class N301 domainevent
  N302((CustomerUnlikedCommentDomainEvent))
  class N302 domainevent
  N303((CustomerUnlikedVideoDomainEvent))
  class N303 domainevent
  N304((UserFocusedDomainEvent))
  class N304 domainevent
  N305((UserUnfocusedDomainEvent))
  class N305 domainevent
  N306(CustomerMessage::onCreate)
  class N306 entitymethod
  N307((CustomerMessageCollectionCreatedDomainEvent))
  class N307 domainevent
  N308((CustomerMessageCommentMentionCreatedDomainEvent))
  class N308 domainevent
  N309((CustomerMessageLikeCreatedDomainEvent))
  class N309 domainevent
  N310((CustomerMessagePrivateCreatedDomainEvent))
  class N310 domainevent
  N311((CustomerMessageSystemCreatedDomainEvent))
  class N311 domainevent
  N312(CustomerProfile::onCreate)
  class N312 entitymethod
  N313(CustomerProfile::reclaimRewardCoins)
  class N313 entitymethod
  N314(CustomerProfile::rewardCoins)
  class N314 entitymethod
  N315(CustomerProfile::spendCoins)
  class N315 entitymethod
  N316(CustomerProfile::transferCoin)
  class N316 entitymethod
  N317((CustomerAvatarUpdatedDomainEvent))
  class N317 domainevent
  N318((CustomerNicknameUpdatedDomainEvent))
  class N318 domainevent
  N319((CustomerProfileCoinsRewardedDomainEvent))
  class N319 domainevent
  N320((CustomerProfileCreatedDomainEvent))
  class N320 domainevent
  N321((CustomerProfilePhoneChangedDomainEvent))
  class N321 domainevent
  N322((CustomerProfileRewardCoinsReclaimedDomainEvent))
  class N322 domainevent
  N323((CustomerProfileUpdatedDomainEvent))
  class N323 domainevent
  N324(Statistics::onCreate)
  class N324 entitymethod
  N325(Statistics::updateCount)
  class N325 entitymethod
  N326((StatisticsCountUpdatedDomainEvent))
  class N326 domainevent
  N327(User::bindPhone)
  class N327 entitymethod
  N328(User::bindingRelationship)
  class N328 entitymethod
  N329((AccountDisabledDomainEvent))
  class N329 domainevent
  N330((AccountEnabledDomainEvent))
  class N330 domainevent
  N331((LoginInfoUpdatedDomainEvent))
  class N331 domainevent
  N332((PasswordChangedDomainEvent))
  class N332 domainevent
  N333((RelationshipBoundDomainEvent))
  class N333 domainevent
  N334((UserCreatedDomainEvent))
  class N334 domainevent
  N335((UserPhoneChangedDomainEvent))
  class N335 domainevent
  N336(UserAbnormalOperationLog::&lt;get-id&gt;)
  class N336 entitymethod
  N337(UserAbnormalOperationLog::onCreate)
  class N337 entitymethod
  N338((PasswordInputFailedDomainEvent))
  class N338 domainevent
  N339(Video::&lt;get-coinCount&gt;)
  class N339 entitymethod
  N340(Video::&lt;get-collectCount&gt;)
  class N340 entitymethod
  N341(Video::&lt;get-commentCount&gt;)
  class N341 entitymethod
  N342(Video::&lt;get-customerId&gt;)
  class N342 entitymethod
  N343(Video::&lt;get-danmukuCount&gt;)
  class N343 entitymethod
  N344(Video::&lt;get-id&gt;)
  class N344 entitymethod
  N345(Video::&lt;get-likeCount&gt;)
  class N345 entitymethod
  N346(Video::&lt;get-playCount&gt;)
  class N346 entitymethod
  N347(Video::applyCoinCountDelta)
  class N347 entitymethod
  N348(Video::applyCollectCountDelta)
  class N348 entitymethod
  N349(Video::applyCommentCountDelta)
  class N349 entitymethod
  N350(Video::applyDanmukuCountDelta)
  class N350 entitymethod
  N351(Video::applyLikeCountDelta)
  class N351 entitymethod
  N352(Video::applyPlayCountDelta)
  class N352 entitymethod
  N353(Video::changeInteraction)
  class N353 entitymethod
  N354(Video::onCreate)
  class N354 entitymethod
  N355(Video::onDelete)
  class N355 entitymethod
  N356(Video::syncFromBasics)
  class N356 entitymethod
  N357((VideoBasicsSyncedDomainEvent))
  class N357 domainevent
  N358((VideoCoinCountDeltaAppliedDomainEvent))
  class N358 domainevent
  N359((VideoCollectCountDeltaAppliedDomainEvent))
  class N359 domainevent
  N360((VideoCommentCountDeltaAppliedDomainEvent))
  class N360 domainevent
  N361((VideoCreatedDomainEvent))
  class N361 domainevent
  N362((VideoDanmukuCountDeltaAppliedDomainEvent))
  class N362 domainevent
  N363((VideoDeletedDomainEvent))
  class N363 domainevent
  N364((VideoInteractionChangedDomainEvent))
  class N364 domainevent
  N365((VideoLastPlayTimeAttachedDomainEvent))
  class N365 domainevent
  N366((VideoLikeCountDeltaAppliedDomainEvent))
  class N366 domainevent
  N367((VideoPlayCountDeltaAppliedDomainEvent))
  class N367 domainevent
  N368((VideoRecommendedDomainEvent))
  class N368 domainevent
  N369((VideoUnrecommendedDomainEvent))
  class N369 domainevent
  N370((VideoAuditTraceRecordedDomainEvent))
  class N370 domainevent
  N371(VideoComment::&lt;get-customerId&gt;)
  class N371 entitymethod
  N372(VideoComment::onDelete)
  class N372 entitymethod
  N373(VideoComment::updateStatistics)
  class N373 entitymethod
  N374((CommentDeletedDomainEvent))
  class N374 domainevent
  N375((CommentPostedDomainEvent))
  class N375 domainevent
  N376((CommentToppedDomainEvent))
  class N376 domainevent
  N377((CommentUntoppedDomainEvent))
  class N377 domainevent
  N378(VideoDanmuku::onDelete)
  class N378 entitymethod
  N379((DanmukuDeletedDomainEvent))
  class N379 domainevent
  N380((DanmukuPostedDomainEvent))
  class N380 domainevent
  N381(VideoFileUploadSession::initTempAndStartUploading)
  class N381 entitymethod
  N382((UploadSessionAbortedDomainEvent))
  class N382 domainevent
  N383((UploadSessionCreatedDomainEvent))
  class N383 domainevent
  N384((VideoFileUploadSessionChunkUploadedDomainEvent))
  class N384 domainevent
  N385((VideoFileUploadSessionMarkedDoneDomainEvent))
  class N385 domainevent
  N386(VideoHlsEncryptKey::bindVideoId)
  class N386 entitymethod
  N387(VideoHlsEncryptKey::onCreate)
  class N387 entitymethod
  N388((VideoHlsEncryptKeyCreatedDomainEvent))
  class N388 domainevent
  N389(VideoHlsKeyToken::bindVideoId)
  class N389 entitymethod
  N390((VideoHlsKeyTokenIssuedDomainEvent))
  class N390 domainevent
  N391(VideoPlayHistory::onCreate)
  class N391 entitymethod
  N392(VideoPlayHistory::updatePlayProgress)
  class N392 entitymethod
  N393((VideoPlayHistoryCreatedDomainEvent))
  class N393 domainevent
  N394((VideoPlayHistoryProgressUpdatedDomainEvent))
  class N394 domainevent
  N395(VideoFilePost::&lt;get-customerId&gt;)
  class N395 entitymethod
  N396(VideoFilePost::&lt;get-duration&gt;)
  class N396 entitymethod
  N397(VideoFilePost::&lt;get-fileIndex&gt;)
  class N397 entitymethod
  N398(VideoFilePost::&lt;get-fileName&gt;)
  class N398 entitymethod
  N399(VideoFilePost::&lt;get-fileSize&gt;)
  class N399 entitymethod
  N400(VideoFilePost::&lt;get-id&gt;)
  class N400 entitymethod
  N401(VideoFilePost::&lt;get-videoFilePostVariants&gt;)
  class N401 entitymethod
  N402(VideoFilePost::applyEncryptResult)
  class N402 entitymethod
  N403(VideoFilePost::applyTranscodeResult)
  class N403 entitymethod
  N404(VideoFilePost::syncVariants)
  class N404 entitymethod
  N405(VideoFilePostVariant::&lt;get-audioBitrateKbps&gt;)
  class N405 entitymethod
  N406(VideoFilePostVariant::&lt;get-bandwidthBps&gt;)
  class N406 entitymethod
  N407(VideoFilePostVariant::&lt;get-height&gt;)
  class N407 entitymethod
  N408(VideoFilePostVariant::&lt;get-playlistPath&gt;)
  class N408 entitymethod
  N409(VideoFilePostVariant::&lt;get-quality&gt;)
  class N409 entitymethod
  N410(VideoFilePostVariant::&lt;get-segmentDuration&gt;)
  class N410 entitymethod
  N411(VideoFilePostVariant::&lt;get-segmentPrefix&gt;)
  class N411 entitymethod
  N412(VideoFilePostVariant::&lt;get-videoBitrateKbps&gt;)
  class N412 entitymethod
  N413(VideoFilePostVariant::&lt;get-width&gt;)
  class N413 entitymethod
  N414(VideoPost::&lt;get-customerId&gt;)
  class N414 entitymethod
  N415(VideoPost::&lt;get-videoFilePosts&gt;)
  class N415 entitymethod
  N416(VideoPost::applyProcessStatus)
  class N416 entitymethod
  N417(VideoPost::reviewFail)
  class N417 entitymethod
  N418(VideoPost::reviewPass)
  class N418 entitymethod
  N419(VideoPost::updateDuration)
  class N419 entitymethod
  N420((VideoAuditFailedDomainEvent))
  class N420 domainevent
  N421((VideoAuditPassedDomainEvent))
  class N421 domainevent
  N422((VideoPostCreatedDomainEvent))
  class N422 domainevent
  N423((VideoPostDeletedDomainEvent))
  class N423 domainevent
  N424((VideoPostInteractionChangedDomainEvent))
  class N424 domainevent
  N425((VideoPostTranscodingRequestedDomainEvent))
  class N425 domainevent
  N426(VideoPostProcessing::&lt;get-videoPostProcessingFiles&gt;)
  class N426 entitymethod
  N427(VideoPostProcessing::appendFiles)
  class N427 entitymethod
  N428(VideoPostProcessing::applyEncryptResult)
  class N428 entitymethod
  N429(VideoPostProcessing::applyTranscodeResult)
  class N429 entitymethod
  N430(VideoPostProcessing::applyVariantEncryptResult)
  class N430 entitymethod
  N431(VideoPostProcessing::onCreate)
  class N431 entitymethod
  N432(VideoPostProcessing::prepareEncryptContext)
  class N432 entitymethod
  N433(VideoPostProcessingFile::&lt;get-encryptKeyVersion&gt;)
  class N433 entitymethod
  N434(VideoPostProcessingFile::&lt;get-fileIndex&gt;)
  class N434 entitymethod
  N435((VideoPostProcessingCompletedDomainEvent))
  class N435 domainevent
  N436((VideoPostProcessingEncryptContextPreparedDomainEvent))
  class N436 domainevent
  N437((VideoPostProcessingFileEncryptCompletedDomainEvent))
  class N437 domainevent
  N438((VideoPostProcessingStartedDomainEvent))
  class N438 domainevent
  N439((VideoPostProcessingTranscodeCompletedDomainEvent))
  class N439 domainevent
  N440(VideoQualityPolicy::applyPolicy)
  class N440 entitymethod
  N441(VideoQualityPolicy::onCreate)
  class N441 entitymethod
  N1 -->|CommandSenderMethodToCommand| N113
  N1 -->|CommandSenderMethodToCommand| N115
  N1 -->|CommandSenderMethodToCommand| N117
  N1 -->|CommandSenderMethodToCommand| N129
  N1 -->|CommandSenderMethodToCommand| N137
  N1 -->|CliSenderMethodToCli| N143
  N1 -->|CliSenderMethodToCli| N146
  N1 -->|CliSenderMethodToCli| N147
  N1 -->|CliSenderMethodToCli| N148
  N1 -->|CliSenderMethodToCli| N149
  N1 -->|QuerySenderMethodToQuery| N150
  N1 -->|QuerySenderMethodToQuery| N151
  N1 -->|QuerySenderMethodToQuery| N152
  N1 -->|QuerySenderMethodToQuery| N153
  N1 -->|QuerySenderMethodToQuery| N154
  N1 -->|QuerySenderMethodToQuery| N155
  N1 -->|QuerySenderMethodToQuery| N156
  N1 -->|QuerySenderMethodToQuery| N157
  N1 -->|QuerySenderMethodToQuery| N158
  N1 -->|QuerySenderMethodToQuery| N159
  N1 -->|QuerySenderMethodToQuery| N160
  N1 -->|QuerySenderMethodToQuery| N161
  N1 -->|QuerySenderMethodToQuery| N162
  N1 -->|QuerySenderMethodToQuery| N164
  N1 -->|QuerySenderMethodToQuery| N165
  N1 -->|QuerySenderMethodToQuery| N166
  N1 -->|QuerySenderMethodToQuery| N167
  N1 -->|QuerySenderMethodToQuery| N168
  N1 -->|QuerySenderMethodToQuery| N169
  N1 -->|QuerySenderMethodToQuery| N170
  N1 -->|QuerySenderMethodToQuery| N171
  N1 -->|QuerySenderMethodToQuery| N173
  N1 -->|QuerySenderMethodToQuery| N174
  N1 -->|QuerySenderMethodToQuery| N175
  N1 -->|QuerySenderMethodToQuery| N176
  N1 -->|QuerySenderMethodToQuery| N177
  N1 -->|QuerySenderMethodToQuery| N181
  N1 -->|QuerySenderMethodToQuery| N182
  N1 -->|QuerySenderMethodToQuery| N183
  N1 -->|QuerySenderMethodToQuery| N184
  N1 -->|QuerySenderMethodToQuery| N185
  N1 -->|EntityMethodToDomainEvent| N288
  N1 -->|EntityMethodToDomainEvent| N289
  N1 -->|EntityMethodToDomainEvent| N290
  N1 -->|EntityMethodToDomainEvent| N291
  N1 -->|EntityMethodToDomainEvent| N292
  N1 -->|EntityMethodToDomainEvent| N293
  N1 -->|EntityMethodToDomainEvent| N294
  N1 -->|EntityMethodToDomainEvent| N295
  N1 -->|EntityMethodToDomainEvent| N296
  N1 -->|EntityMethodToDomainEvent| N297
  N1 -->|EntityMethodToDomainEvent| N298
  N1 -->|EntityMethodToDomainEvent| N299
  N1 -->|EntityMethodToDomainEvent| N300
  N1 -->|EntityMethodToDomainEvent| N301
  N1 -->|EntityMethodToDomainEvent| N302
  N1 -->|EntityMethodToDomainEvent| N303
  N1 -->|EntityMethodToDomainEvent| N304
  N1 -->|EntityMethodToDomainEvent| N305
  N1 -->|EntityMethodToDomainEvent| N307
  N1 -->|EntityMethodToDomainEvent| N308
  N1 -->|EntityMethodToDomainEvent| N309
  N1 -->|EntityMethodToDomainEvent| N310
  N1 -->|EntityMethodToDomainEvent| N311
  N1 -->|EntityMethodToDomainEvent| N317
  N1 -->|EntityMethodToDomainEvent| N318
  N1 -->|EntityMethodToDomainEvent| N319
  N1 -->|EntityMethodToDomainEvent| N320
  N1 -->|EntityMethodToDomainEvent| N321
  N1 -->|EntityMethodToDomainEvent| N322
  N1 -->|EntityMethodToDomainEvent| N323
  N1 -->|EntityMethodToDomainEvent| N326
  N1 -->|EntityMethodToDomainEvent| N329
  N1 -->|EntityMethodToDomainEvent| N330
  N1 -->|EntityMethodToDomainEvent| N331
  N1 -->|EntityMethodToDomainEvent| N332
  N1 -->|EntityMethodToDomainEvent| N333
  N1 -->|EntityMethodToDomainEvent| N334
  N1 -->|EntityMethodToDomainEvent| N335
  N1 -->|EntityMethodToDomainEvent| N338
  N1 -->|EntityMethodToDomainEvent| N357
  N1 -->|EntityMethodToDomainEvent| N358
  N1 -->|EntityMethodToDomainEvent| N359
  N1 -->|EntityMethodToDomainEvent| N360
  N1 -->|EntityMethodToDomainEvent| N361
  N1 -->|EntityMethodToDomainEvent| N362
  N1 -->|EntityMethodToDomainEvent| N363
  N1 -->|EntityMethodToDomainEvent| N364
  N1 -->|EntityMethodToDomainEvent| N365
  N1 -->|EntityMethodToDomainEvent| N366
  N1 -->|EntityMethodToDomainEvent| N367
  N1 -->|EntityMethodToDomainEvent| N368
  N1 -->|EntityMethodToDomainEvent| N369
  N1 -->|EntityMethodToDomainEvent| N370
  N1 -->|EntityMethodToDomainEvent| N374
  N1 -->|EntityMethodToDomainEvent| N375
  N1 -->|EntityMethodToDomainEvent| N376
  N1 -->|EntityMethodToDomainEvent| N377
  N1 -->|EntityMethodToDomainEvent| N379
  N1 -->|EntityMethodToDomainEvent| N380
  N1 -->|EntityMethodToDomainEvent| N382
  N1 -->|EntityMethodToDomainEvent| N383
  N1 -->|EntityMethodToDomainEvent| N384
  N1 -->|EntityMethodToDomainEvent| N385
  N1 -->|EntityMethodToDomainEvent| N388
  N1 -->|EntityMethodToDomainEvent| N390
  N1 -->|EntityMethodToDomainEvent| N393
  N1 -->|EntityMethodToDomainEvent| N394
  N1 -->|EntityMethodToDomainEvent| N420
  N1 -->|EntityMethodToDomainEvent| N421
  N1 -->|EntityMethodToDomainEvent| N422
  N1 -->|EntityMethodToDomainEvent| N423
  N1 -->|EntityMethodToDomainEvent| N424
  N1 -->|EntityMethodToDomainEvent| N425
  N1 -->|EntityMethodToDomainEvent| N435
  N1 -->|EntityMethodToDomainEvent| N436
  N1 -->|EntityMethodToDomainEvent| N437
  N1 -->|EntityMethodToDomainEvent| N438
  N1 -->|EntityMethodToDomainEvent| N439
  N50 -->|CommandHandlerToEntityMethod| N281
  N50 -->|CommandHandlerToEntityMethod| N282
  N50 -->|CommandHandlerToEntityMethod| N283
  N50 -->|CommandHandlerToEntityMethod| N284
  N50 -->|CommandHandlerToEntityMethod| N285
  N50 -->|CommandHandlerToEntityMethod| N286
  N50 -->|CommandHandlerToEntityMethod| N287
  N51 -->|CommandToCommandHandler| N50
  N52 -->|CommandHandlerToEntityMethod| N306
  N52 -->|CommandHandlerToEntityMethod| N342
  N53 -->|CommandToCommandHandler| N52
  N54 -->|CommandHandlerToEntityMethod| N306
  N54 -->|CommandHandlerToEntityMethod| N342
  N55 -->|CommandToCommandHandler| N54
  N56 -->|CommandHandlerToEntityMethod| N306
  N56 -->|CommandHandlerToEntityMethod| N342
  N57 -->|CommandToCommandHandler| N56
  N58 -->|CommandHandlerToEntityMethod| N306
  N58 -->|CommandHandlerToEntityMethod| N371
  N59 -->|CommandToCommandHandler| N58
  N60 -->|CommandHandlerToEntityMethod| N306
  N60 -->|CommandHandlerToEntityMethod| N414
  N61 -->|CommandToCommandHandler| N60
  N62 -->|CommandHandlerToEntityMethod| N306
  N62 -->|CommandHandlerToEntityMethod| N414
  N63 -->|CommandToCommandHandler| N62
  N64 -->|CommandHandlerToEntityMethod| N313
  N65 -->|CommandToCommandHandler| N64
  N66 -->|CommandHandlerToEntityMethod| N312
  N67 -->|CommandToCommandHandler| N66
  N68 -->|CommandHandlerToEntityMethod| N314
  N69 -->|CommandToCommandHandler| N68
  N70 -->|CommandHandlerToEntityMethod| N315
  N71 -->|CommandToCommandHandler| N70
  N72 -->|CommandHandlerToEntityMethod| N316
  N73 -->|CommandToCommandHandler| N72
  N74 -->|CommandHandlerToEntityMethod| N324
  N74 -->|CommandHandlerToEntityMethod| N325
  N75 -->|CommandToCommandHandler| N74
  N76 -->|CommandHandlerToEntityMethod| N327
  N77 -->|CommandToCommandHandler| N76
  N78 -->|CommandHandlerToEntityMethod| N328
  N79 -->|CommandToCommandHandler| N78
  N80 -->|CommandHandlerToEntityMethod| N336
  N80 -->|CommandHandlerToEntityMethod| N337
  N81 -->|CommandToCommandHandler| N80
  N82 -->|CommandHandlerToEntityMethod| N339
  N82 -->|CommandHandlerToEntityMethod| N344
  N82 -->|CommandHandlerToEntityMethod| N347
  N83 -->|CommandToCommandHandler| N82
  N84 -->|CommandHandlerToEntityMethod| N340
  N84 -->|CommandHandlerToEntityMethod| N344
  N84 -->|CommandHandlerToEntityMethod| N348
  N85 -->|CommandToCommandHandler| N84
  N86 -->|CommandHandlerToEntityMethod| N341
  N86 -->|CommandHandlerToEntityMethod| N344
  N86 -->|CommandHandlerToEntityMethod| N349
  N87 -->|CommandToCommandHandler| N86
  N88 -->|CommandHandlerToEntityMethod| N343
  N88 -->|CommandHandlerToEntityMethod| N344
  N88 -->|CommandHandlerToEntityMethod| N350
  N89 -->|CommandToCommandHandler| N88
  N90 -->|CommandHandlerToEntityMethod| N344
  N90 -->|CommandHandlerToEntityMethod| N345
  N90 -->|CommandHandlerToEntityMethod| N351
  N91 -->|CommandToCommandHandler| N90
  N92 -->|CommandHandlerToEntityMethod| N344
  N92 -->|CommandHandlerToEntityMethod| N346
  N92 -->|CommandHandlerToEntityMethod| N352
  N93 -->|CommandToCommandHandler| N92
  N94 -->|CommandHandlerToEntityMethod| N342
  N94 -->|CommandHandlerToEntityMethod| N353
  N95 -->|CommandToCommandHandler| N94
  N96 -->|CommandHandlerToEntityMethod| N355
  N97 -->|CommandToCommandHandler| N96
  N98 -->|CommandHandlerToEntityMethod| N344
  N98 -->|CommandHandlerToEntityMethod| N354
  N98 -->|CommandHandlerToEntityMethod| N356
  N98 -->|CommandHandlerToEntityMethod| N395
  N98 -->|CommandHandlerToEntityMethod| N396
  N98 -->|CommandHandlerToEntityMethod| N397
  N98 -->|CommandHandlerToEntityMethod| N398
  N98 -->|CommandHandlerToEntityMethod| N399
  N98 -->|CommandHandlerToEntityMethod| N400
  N98 -->|CommandHandlerToEntityMethod| N401
  N98 -->|CommandHandlerToEntityMethod| N405
  N98 -->|CommandHandlerToEntityMethod| N406
  N98 -->|CommandHandlerToEntityMethod| N407
  N98 -->|CommandHandlerToEntityMethod| N408
  N98 -->|CommandHandlerToEntityMethod| N409
  N98 -->|CommandHandlerToEntityMethod| N410
  N98 -->|CommandHandlerToEntityMethod| N411
  N98 -->|CommandHandlerToEntityMethod| N412
  N98 -->|CommandHandlerToEntityMethod| N413
  N98 -->|CommandHandlerToEntityMethod| N415
  N99 -->|CommandToCommandHandler| N98
  N100 -->|CommandHandlerToEntityMethod| N373
  N101 -->|CommandToCommandHandler| N100
  N102 -->|CommandHandlerToEntityMethod| N373
  N103 -->|CommandToCommandHandler| N102
  N104 -->|CommandHandlerToEntityMethod| N373
  N105 -->|CommandToCommandHandler| N104
  N106 -->|CommandHandlerToEntityMethod| N373
  N107 -->|CommandToCommandHandler| N106
  N108 -->|CommandHandlerToEntityMethod| N372
  N109 -->|CommandToCommandHandler| N108
  N110 -->|CommandHandlerToEntityMethod| N378
  N111 -->|CommandToCommandHandler| N110
  N112 -->|CommandHandlerToEntityMethod| N386
  N113 -->|CommandToCommandHandler| N112
  N114 -->|CommandHandlerToEntityMethod| N389
  N115 -->|CommandToCommandHandler| N114
  N116 -->|CommandHandlerToEntityMethod| N387
  N117 -->|CommandToCommandHandler| N116
  N118 -->|CommandHandlerToEntityMethod| N381
  N119 -->|CommandToCommandHandler| N118
  N120 -->|CommandHandlerToEntityMethod| N391
  N120 -->|CommandHandlerToEntityMethod| N392
  N121 -->|CommandToCommandHandler| N120
  N122 -->|CommandHandlerToEntityMethod| N417
  N122 -->|CommandHandlerToEntityMethod| N418
  N123 -->|CommandToCommandHandler| N122
  N124 -->|CommandHandlerToEntityMethod| N397
  N124 -->|CommandHandlerToEntityMethod| N402
  N124 -->|CommandHandlerToEntityMethod| N403
  N124 -->|CommandHandlerToEntityMethod| N404
  N124 -->|CommandHandlerToEntityMethod| N415
  N124 -->|CommandHandlerToEntityMethod| N416
  N124 -->|CommandHandlerToEntityMethod| N419
  N125 -->|CommandToCommandHandler| N124
  N126 -->|CommandHandlerToEntityMethod| N428
  N127 -->|CommandToCommandHandler| N126
  N128 -->|CommandHandlerToEntityMethod| N429
  N129 -->|CommandToCommandHandler| N128
  N130 -->|CommandHandlerToEntityMethod| N430
  N131 -->|CommandToCommandHandler| N130
  N132 -->|CommandHandlerToEntityMethod| N426
  N132 -->|CommandHandlerToEntityMethod| N432
  N132 -->|CommandHandlerToEntityMethod| N433
  N132 -->|CommandHandlerToEntityMethod| N434
  N133 -->|CommandToCommandHandler| N132
  N134 -->|CommandHandlerToEntityMethod| N427
  N134 -->|CommandHandlerToEntityMethod| N431
  N135 -->|CommandToCommandHandler| N134
  N136 -->|CommandHandlerToEntityMethod| N440
  N136 -->|CommandHandlerToEntityMethod| N441
  N137 -->|CommandToCommandHandler| N136
  N138 -->|CliToCliHandler| N2
  N139 -->|CliToCliHandler| N3
  N140 -->|CliToCliHandler| N4
  N141 -->|CliToCliHandler| N5
  N142 -->|CliToCliHandler| N6
  N143 -->|CliToCliHandler| N7
  N144 -->|CliToCliHandler| N8
  N145 -->|CliToCliHandler| N9
  N146 -->|CliToCliHandler| N10
  N147 -->|CliToCliHandler| N11
  N148 -->|CliToCliHandler| N12
  N149 -->|CliToCliHandler| N13
  N150 -->|QueryToQueryHandler| N14
  N151 -->|QueryToQueryHandler| N15
  N152 -->|QueryToQueryHandler| N16
  N153 -->|QueryToQueryHandler| N17
  N154 -->|QueryToQueryHandler| N18
  N155 -->|QueryToQueryHandler| N19
  N156 -->|QueryToQueryHandler| N20
  N157 -->|QueryToQueryHandler| N21
  N158 -->|QueryToQueryHandler| N22
  N159 -->|QueryToQueryHandler| N23
  N160 -->|QueryToQueryHandler| N24
  N161 -->|QueryToQueryHandler| N25
  N162 -->|QueryToQueryHandler| N26
  N163 -->|QueryToQueryHandler| N27
  N164 -->|QueryToQueryHandler| N28
  N165 -->|QueryToQueryHandler| N29
  N166 -->|QueryToQueryHandler| N30
  N167 -->|QueryToQueryHandler| N31
  N168 -->|QueryToQueryHandler| N32
  N169 -->|QueryToQueryHandler| N33
  N170 -->|QueryToQueryHandler| N34
  N171 -->|QueryToQueryHandler| N35
  N172 -->|QueryToQueryHandler| N36
  N173 -->|QueryToQueryHandler| N37
  N174 -->|QueryToQueryHandler| N38
  N175 -->|QueryToQueryHandler| N39
  N176 -->|QueryToQueryHandler| N40
  N177 -->|QueryToQueryHandler| N41
  N178 -->|QueryToQueryHandler| N42
  N179 -->|QueryToQueryHandler| N43
  N180 -->|QueryToQueryHandler| N44
  N181 -->|QueryToQueryHandler| N45
  N182 -->|QueryToQueryHandler| N46
  N183 -->|QueryToQueryHandler| N47
  N184 -->|QueryToQueryHandler| N48
  N185 -->|QueryToQueryHandler| N49
  N188 -->|DomainEventHandlerToCommand| N51
  N193 -->|DomainEventHandlerToCommand| N73
  N194 -->|DomainEventHandlerToCommand| N83
  N195 -->|DomainEventHandlerToCommand| N85
  N196 -->|DomainEventHandlerToCommand| N53
  N197 -->|DomainEventHandlerToCommand| N101
  N198 -->|DomainEventHandlerToCommand| N103
  N199 -->|DomainEventHandlerToCommand| N91
  N200 -->|DomainEventHandlerToCommand| N57
  N201 -->|DomainEventHandlerToCommand| N85
  N202 -->|DomainEventHandlerToCommand| N105
  N203 -->|DomainEventHandlerToCommand| N107
  N204 -->|DomainEventHandlerToCommand| N91
  N205 -->|DomainEventHandlerToCommand| N75
  N206 -->|DomainEventHandlerToCommand| N75
  N212 -->|DomainEventHandlerToCli| N140
  N213 -->|DomainEventHandlerToCommand| N71
  N213 -->|DomainEventHandlerToCli| N140
  N215 -->|DomainEventHandlerToCommand| N79
  N216 -->|DomainEventHandlerToCommand| N77
  N225 -->|DomainEventHandlerToCommand| N67
  N227 -->|DomainEventHandlerToCommand| N81
  N227 -->|DomainEventHandlerToQuery| N163
  N229 -->|DomainEventHandlerToCommand| N75
  N230 -->|DomainEventHandlerToCommand| N75
  N231 -->|DomainEventHandlerToCommand| N75
  N233 -->|DomainEventHandlerToCommand| N75
  N234 -->|DomainEventHandlerToCommand| N109
  N235 -->|DomainEventHandlerToCommand| N111
  N236 -->|DomainEventHandlerToCli| N141
  N239 -->|DomainEventHandlerToCommand| N75
  N240 -->|DomainEventHandlerToCommand| N75
  N241 -->|DomainEventHandlerToCommand| N65
  N242 -->|DomainEventHandlerToCli| N139
  N243 -->|DomainEventHandlerToCommand| N97
  N246 -->|DomainEventHandlerToCommand| N61
  N246 -->|DomainEventHandlerToCommand| N63
  N247 -->|DomainEventHandlerToCommand| N123
  N248 -->|DomainEventHandlerToCommand| N87
  N250 -->|DomainEventHandlerToCommand| N87
  N251 -->|DomainEventHandlerToCommand| N55
  N252 -->|DomainEventHandlerToCommand| N59
  N252 -->|DomainEventHandlerToQuery| N166
  N255 -->|DomainEventHandlerToCommand| N89
  N256 -->|DomainEventHandlerToCommand| N89
  N257 -->|DomainEventHandlerToCommand| N131
  N257 -->|DomainEventHandlerToCli| N144
  N257 -->|DomainEventHandlerToQuery| N178
  N258 -->|DomainEventHandlerToCli| N143
  N259 -->|DomainEventHandlerToCommand| N119
  N259 -->|DomainEventHandlerToCli| N142
  N262 -->|DomainEventHandlerToCommand| N121
  N263 -->|DomainEventHandlerToCommand| N93
  N267 -->|DomainEventHandlerToCommand| N113
  N267 -->|DomainEventHandlerToQuery| N170
  N268 -->|DomainEventHandlerToCommand| N115
  N268 -->|DomainEventHandlerToQuery| N171
  N269 -->|DomainEventHandlerToCli| N138
  N269 -->|DomainEventHandlerToQuery| N172
  N270 -->|DomainEventHandlerToCommand| N69
  N271 -->|DomainEventHandlerToCommand| N137
  N272 -->|DomainEventHandlerToCommand| N99
  N274 -->|DomainEventHandlerToCommand| N95
  N275 -->|DomainEventHandlerToCommand| N135
  N276 -->|DomainEventHandlerToCommand| N125
  N276 -->|DomainEventHandlerToQuery| N179
  N277 -->|DomainEventHandlerToCommand| N117
  N277 -->|DomainEventHandlerToCommand| N127
  N278 -->|DomainEventHandlerToCommand| N127
  N278 -->|DomainEventHandlerToCli| N145
  N278 -->|DomainEventHandlerToQuery| N178
  N278 -->|DomainEventHandlerToQuery| N180
  N279 -->|DomainEventHandlerToCommand| N129
  N279 -->|DomainEventHandlerToCli| N146
  N279 -->|DomainEventHandlerToCli| N147
  N279 -->|DomainEventHandlerToCli| N148
  N279 -->|DomainEventHandlerToCli| N149
  N279 -->|DomainEventHandlerToQuery| N185
  N280 -->|DomainEventHandlerToCommand| N133
  N286 -->|EntityMethodToDomainEvent| N294
  N287 -->|EntityMethodToDomainEvent| N292
  N288 -->|DomainEventToHandler| N186
  N289 -->|DomainEventToHandler| N187
  N290 -->|DomainEventToHandler| N188
  N291 -->|DomainEventToHandler| N189
  N292 -->|DomainEventToHandler| N190
  N293 -->|DomainEventToHandler| N191
  N294 -->|DomainEventToHandler| N192
  N295 -->|DomainEventToHandler| N193
  N295 -->|DomainEventToHandler| N194
  N296 -->|DomainEventToHandler| N195
  N296 -->|DomainEventToHandler| N196
  N297 -->|DomainEventToHandler| N197
  N298 -->|DomainEventToHandler| N198
  N299 -->|DomainEventToHandler| N199
  N299 -->|DomainEventToHandler| N200
  N300 -->|DomainEventToHandler| N201
  N301 -->|DomainEventToHandler| N202
  N302 -->|DomainEventToHandler| N203
  N303 -->|DomainEventToHandler| N204
  N304 -->|DomainEventToHandler| N205
  N305 -->|DomainEventToHandler| N206
  N306 -->|EntityMethodToDomainEvent| N307
  N306 -->|EntityMethodToDomainEvent| N308
  N306 -->|EntityMethodToDomainEvent| N309
  N306 -->|EntityMethodToDomainEvent| N310
  N306 -->|EntityMethodToDomainEvent| N311
  N307 -->|DomainEventToHandler| N207
  N308 -->|DomainEventToHandler| N208
  N309 -->|DomainEventToHandler| N209
  N310 -->|DomainEventToHandler| N210
  N311 -->|DomainEventToHandler| N211
  N312 -->|EntityMethodToDomainEvent| N320
  N313 -->|EntityMethodToDomainEvent| N322
  N314 -->|EntityMethodToDomainEvent| N319
  N317 -->|DomainEventToHandler| N212
  N318 -->|DomainEventToHandler| N213
  N319 -->|DomainEventToHandler| N214
  N320 -->|DomainEventToHandler| N215
  N321 -->|DomainEventToHandler| N216
  N322 -->|DomainEventToHandler| N217
  N323 -->|DomainEventToHandler| N218
  N325 -->|EntityMethodToDomainEvent| N326
  N326 -->|DomainEventToHandler| N219
  N327 -->|EntityMethodToDomainEvent| N335
  N328 -->|EntityMethodToDomainEvent| N333
  N329 -->|DomainEventToHandler| N220
  N330 -->|DomainEventToHandler| N221
  N331 -->|DomainEventToHandler| N222
  N332 -->|DomainEventToHandler| N223
  N333 -->|DomainEventToHandler| N224
  N334 -->|DomainEventToHandler| N225
  N335 -->|DomainEventToHandler| N226
  N338 -->|DomainEventToHandler| N227
  N347 -->|EntityMethodToDomainEvent| N358
  N348 -->|EntityMethodToDomainEvent| N359
  N349 -->|EntityMethodToDomainEvent| N360
  N350 -->|EntityMethodToDomainEvent| N362
  N351 -->|EntityMethodToDomainEvent| N366
  N352 -->|EntityMethodToDomainEvent| N367
  N353 -->|EntityMethodToDomainEvent| N364
  N354 -->|EntityMethodToDomainEvent| N361
  N355 -->|EntityMethodToDomainEvent| N363
  N356 -->|EntityMethodToDomainEvent| N357
  N357 -->|DomainEventToHandler| N228
  N358 -->|DomainEventToHandler| N229
  N359 -->|DomainEventToHandler| N230
  N360 -->|DomainEventToHandler| N231
  N361 -->|DomainEventToHandler| N232
  N362 -->|DomainEventToHandler| N233
  N363 -->|DomainEventToHandler| N234
  N363 -->|DomainEventToHandler| N235
  N363 -->|DomainEventToHandler| N236
  N364 -->|DomainEventToHandler| N237
  N365 -->|DomainEventToHandler| N238
  N366 -->|DomainEventToHandler| N239
  N367 -->|DomainEventToHandler| N240
  N368 -->|DomainEventToHandler| N244
  N369 -->|DomainEventToHandler| N245
  N370 -->|DomainEventToHandler| N246
  N370 -->|DomainEventToHandler| N247
  N372 -->|EntityMethodToDomainEvent| N374
  N374 -->|DomainEventToHandler| N248
  N374 -->|DomainEventToHandler| N249
  N375 -->|DomainEventToHandler| N250
  N375 -->|DomainEventToHandler| N251
  N375 -->|DomainEventToHandler| N252
  N376 -->|DomainEventToHandler| N253
  N377 -->|DomainEventToHandler| N254
  N378 -->|EntityMethodToDomainEvent| N379
  N379 -->|DomainEventToHandler| N255
  N380 -->|DomainEventToHandler| N256
  N382 -->|DomainEventToHandler| N258
  N383 -->|DomainEventToHandler| N259
  N384 -->|DomainEventToHandler| N260
  N385 -->|DomainEventToHandler| N261
  N387 -->|EntityMethodToDomainEvent| N388
  N388 -->|DomainEventToHandler| N257
  N390 -->|DomainEventToHandler| N262
  N390 -->|DomainEventToHandler| N263
  N391 -->|EntityMethodToDomainEvent| N393
  N392 -->|EntityMethodToDomainEvent| N394
  N393 -->|DomainEventToHandler| N264
  N394 -->|DomainEventToHandler| N265
  N417 -->|EntityMethodToDomainEvent| N420
  N418 -->|EntityMethodToDomainEvent| N421
  N420 -->|DomainEventToHandler| N266
  N421 -->|DomainEventToHandler| N267
  N421 -->|DomainEventToHandler| N268
  N421 -->|DomainEventToHandler| N269
  N421 -->|DomainEventToHandler| N270
  N421 -->|DomainEventToHandler| N271
  N421 -->|DomainEventToHandler| N272
  N422 -->|DomainEventToHandler| N273
  N423 -->|DomainEventToHandler| N241
  N423 -->|DomainEventToHandler| N242
  N423 -->|DomainEventToHandler| N243
  N424 -->|DomainEventToHandler| N274
  N425 -->|DomainEventToHandler| N275
  N427 -->|EntityMethodToDomainEvent| N438
  N428 -->|EntityMethodToDomainEvent| N435
  N429 -->|EntityMethodToDomainEvent| N439
  N430 -->|EntityMethodToDomainEvent| N437
  N432 -->|EntityMethodToDomainEvent| N436
  N435 -->|DomainEventToHandler| N276
  N436 -->|DomainEventToHandler| N277
  N437 -->|DomainEventToHandler| N278
  N438 -->|DomainEventToHandler| N279
  N439 -->|DomainEventToHandler| N280
  classDef cli fill:#86EFAC,stroke:#15803D,color:#0F172A
  classDef clihandler fill:#22C55E,stroke:#166534,color:#F0FDF4
  classDef command fill:#FDBA74,stroke:#C2410C,color:#111827
  classDef commandhandler fill:#F97316,stroke:#9A3412,color:#111827
  classDef domainevent fill:#FECACA,stroke:#B91C1C,color:#111827
  classDef domaineventhandler fill:#F87171,stroke:#991B1B,color:#111827
  classDef entitymethod fill:#F3F4F6,stroke:#6B7280,color:#111827
  classDef query fill:#93C5FD,stroke:#1D4ED8,color:#0F172A
  classDef queryhandler fill:#3B82F6,stroke:#1E40AF,color:#F8FAFC
  classDef querysendermethod fill:#BFDBFE,stroke:#1D4ED8,color:#0F172A
