flowchart TD
  N1[/&lt;anonymous&gt;/]
  class N1 querysendermethod
  N2[[CleanTempFilesCliHandler]]
  class N2 clihandler
  N3[[DeleteVideoFileResourcesCliHandler]]
  class N3 clihandler
  N4[[RefreshLoginSessionCliHandler]]
  class N4 clihandler
  N5[[RemoveVideoSearchIndexCliHandler]]
  class N5 clihandler
  N6[[CreateUploadSessionTempDirCliHandler]]
  class N6 clihandler
  N7[[DeleteUploadSessionTempDirCliHandler]]
  class N7 clihandler
  N8[[EncryptHlsVariantWithKeyCliHandler]]
  class N8 clihandler
  N9[[GenerateEncryptedMasterByVariantsCliHandler]]
  class N9 clihandler
  N10[[GenerateVideoAbrMasterCliHandler]]
  class N10 clihandler
  N11[[MergeUploadToMp4ByPathCliHandler]]
  class N11 clihandler
  N12[[TranscodeVideoFileToAbrByPathCliHandler]]
  class N12 clihandler
  N13[[UploadVideoAbrOutputCliHandler]]
  class N13 clihandler
  N14[[UniqueCategoryCodeQryHandler]]
  class N14 queryhandler
  N15[[GetUserActionsByVideoIdQryHandler]]
  class N15 queryhandler
  N16[[UniqueCustomerActionTypeQryHandler]]
  class N16 queryhandler
  N17[[CheckFocusStatusQryHandler]]
  class N17 queryhandler
  N18[[GetCustomerProfileQryHandler]]
  class N18 queryhandler
  N19[[UniqueCustomerProfileEmailQryHandler]]
  class N19 queryhandler
  N20[[UniqueCustomerProfileNickNameQryHandler]]
  class N20 queryhandler
  N21[[UniqueCustomerProfilePhoneQryHandler]]
  class N21 queryhandler
  N22[[GetCustomerVideoSeriesInfoQryHandler]]
  class N22 queryhandler
  N23[[CheckNicknameExistsQryHandler]]
  class N23 queryhandler
  N24[[CheckUserExistsQryHandler]]
  class N24 queryhandler
  N25[[UniqueUserEmailQryHandler]]
  class N25 queryhandler
  N26[[UniqueUserPhoneQryHandler]]
  class N26 queryhandler
  N27[[GetRecentPasswordFailureCountQryHandler]]
  class N27 queryhandler
  N28[[GetVideoInfoQryHandler]]
  class N28 queryhandler
  N29[[UniqueVideoFileVariantQryHandler]]
  class N29 queryhandler
  N30[[GetCommentByIdQryHandler]]
  class N30 queryhandler
  N31[[CheckDanmukuExistsQryHandler]]
  class N31 queryhandler
  N32[[GetDanmukuOwnerQryHandler]]
  class N32 queryhandler
  N33[[GetVideoPostInfoQryHandler]]
  class N33 queryhandler
  N34[[UniqueVideoHlsEncryptKeyQryHandler]]
  class N34 queryhandler
  N35[[UniqueVideoHlsKeyTokenQryHandler]]
  class N35 queryhandler
  N36[[UniqueVideoFilePostQryHandler]]
  class N36 queryhandler
  N37[[UniqueVideoFilePostUploadIdQryHandler]]
  class N37 queryhandler
  N38[[UniqueVideoFilePostVariantQryHandler]]
  class N38 queryhandler
  N39[[GetVideoPostProcessingEncryptContextQryHandler]]
  class N39 queryhandler
  N40[[UniqueVideoPostProcessingFileQryHandler]]
  class N40 queryhandler
  N41[[UniqueVideoPostProcessingQryHandler]]
  class N41 queryhandler
  N42[[UniqueVideoPostProcessingVariantQryHandler]]
  class N42 queryhandler
  N43[[UniqueVideoQualityPolicyQryHandler]]
  class N43 queryhandler
  N44[[GetUploadSessionTempPathQryHandler]]
  class N44 queryhandler
  N45[[FinalizeCategoryAfterCreateCmd.Handler]]
  class N45 commandhandler
  N46{{FinalizeCategoryAfterCreateCmd.Request}}
  class N46 command
  N47[[SendCollectMessageCmd.Handler]]
  class N47 commandhandler
  N48{{SendCollectMessageCmd.Request}}
  class N48 command
  N49[[SendCommentMessageCmd.Handler]]
  class N49 commandhandler
  N50{{SendCommentMessageCmd.Request}}
  class N50 command
  N51[[SendLikeMessageCmd.Handler]]
  class N51 commandhandler
  N52{{SendLikeMessageCmd.Request}}
  class N52 command
  N53[[SendReplyMessageCmd.Handler]]
  class N53 commandhandler
  N54{{SendReplyMessageCmd.Request}}
  class N54 command
  N55[[SendVideoAuditFailedMessageCmd.Handler]]
  class N55 commandhandler
  N56{{SendVideoAuditFailedMessageCmd.Request}}
  class N56 command
  N57[[SendVideoAuditPassedMessageCmd.Handler]]
  class N57 commandhandler
  N58{{SendVideoAuditPassedMessageCmd.Request}}
  class N58 command
  N59[[AdjustAuthorCoinAfterDeleteCmd.Handler]]
  class N59 commandhandler
  N60{{AdjustAuthorCoinAfterDeleteCmd.Request}}
  class N60 command
  N61[[CreateCustomerProfileCmd.Handler]]
  class N61 commandhandler
  N62{{CreateCustomerProfileCmd.Request}}
  class N62 command
  N63[[RewardUserForVideoCmd.Handler]]
  class N63 commandhandler
  N64{{RewardUserForVideoCmd.Request}}
  class N64 command
  N65[[SpendCoinsForNicknameChangeCmd.Handler]]
  class N65 commandhandler
  N66{{SpendCoinsForNicknameChangeCmd.Request}}
  class N66 command
  N67[[TransferCoinCmd.Handler]]
  class N67 commandhandler
  N68{{TransferCoinCmd.Request}}
  class N68 command
  N69[[UpdateStatisticsInfoCmd.Handler]]
  class N69 commandhandler
  N70{{UpdateStatisticsInfoCmd.Request}}
  class N70 command
  N71[[ChangeUserPhoneCmd.Handler]]
  class N71 commandhandler
  N72{{ChangeUserPhoneCmd.Request}}
  class N72 command
  N73[[RelationProfileCmd.Handler]]
  class N73 commandhandler
  N74{{RelationProfileCmd.Request}}
  class N74 command
  N75[[RecordAbnormalOperationCmd.Handler]]
  class N75 commandhandler
  N76{{RecordAbnormalOperationCmd.Request}}
  class N76 command
  N77[[ApplyVideoCoinCountDeltaCmd.Handler]]
  class N77 commandhandler
  N78{{ApplyVideoCoinCountDeltaCmd.Request}}
  class N78 command
  N79[[ApplyVideoCollectCountDeltaCmd.Handler]]
  class N79 commandhandler
  N80{{ApplyVideoCollectCountDeltaCmd.Request}}
  class N80 command
  N81[[ApplyVideoCommentCountDeltaCmd.Handler]]
  class N81 commandhandler
  N82{{ApplyVideoCommentCountDeltaCmd.Request}}
  class N82 command
  N83[[ApplyVideoDanmukuCountDeltaCmd.Handler]]
  class N83 commandhandler
  N84{{ApplyVideoDanmukuCountDeltaCmd.Request}}
  class N84 command
  N85[[ApplyVideoLikeCountDeltaCmd.Handler]]
  class N85 commandhandler
  N86{{ApplyVideoLikeCountDeltaCmd.Request}}
  class N86 command
  N87[[ApplyVideoPlayCountDeltaCmd.Handler]]
  class N87 commandhandler
  N88{{ApplyVideoPlayCountDeltaCmd.Request}}
  class N88 command
  N89[[ChangeVideoInteractionCmd.Handler]]
  class N89 commandhandler
  N90{{ChangeVideoInteractionCmd.Request}}
  class N90 command
  N91[[DeleteVideoCmd.Handler]]
  class N91 commandhandler
  N92{{DeleteVideoCmd.Request}}
  class N92 command
  N93[[TransferVideoToProductionCmd.Handler]]
  class N93 commandhandler
  N94{{TransferVideoToProductionCmd.Request}}
  class N94 command
  N95[[ApplyCustomerDislikedCommentCmd.Handler]]
  class N95 commandhandler
  N96{{ApplyCustomerDislikedCommentCmd.Request}}
  class N96 command
  N97[[ApplyCustomerLikedCommentCmd.Handler]]
  class N97 commandhandler
  N98{{ApplyCustomerLikedCommentCmd.Request}}
  class N98 command
  N99[[ApplyCustomerUndislikedCommentCmd.Handler]]
  class N99 commandhandler
  N100{{ApplyCustomerUndislikedCommentCmd.Request}}
  class N100 command
  N101[[ApplyCustomerUnlikedCommentCmd.Handler]]
  class N101 commandhandler
  N102{{ApplyCustomerUnlikedCommentCmd.Request}}
  class N102 command
  N103[[BatchDeleteCommentCmd.Handler]]
  class N103 commandhandler
  N104{{BatchDeleteCommentCmd.Request}}
  class N104 command
  N105[[BatchDeleteDanmukuCmd.Handler]]
  class N105 commandhandler
  N106{{BatchDeleteDanmukuCmd.Request}}
  class N106 command
  N107[[BindVideoHlsEncryptKeyToVideoCmd.Handler]]
  class N107 commandhandler
  N108{{BindVideoHlsEncryptKeyToVideoCmd.Request}}
  class N108 command
  N109[[BindVideoHlsKeyTokenToVideoCmd.Handler]]
  class N109 commandhandler
  N110{{BindVideoHlsKeyTokenToVideoCmd.Request}}
  class N110 command
  N111[[GenerateVideoPostQualityKeyCmd.Handler]]
  class N111 commandhandler
  N112{{GenerateVideoPostQualityKeyCmd.Request}}
  class N112 command
  N113[[InitTempAndStartUploadingCmd.Handler]]
  class N113 commandhandler
  N114{{InitTempAndStartUploadingCmd.Request}}
  class N114 command
  N115[[AddPlayHistoryCmd.Handler]]
  class N115 commandhandler
  N116{{AddPlayHistoryCmd.Request}}
  class N116 command
  N117[[AuditVideoPostCmd.Handler]]
  class N117 commandhandler
  N118{{AuditVideoPostCmd.Request}}
  class N118 command
  N119[[SyncVideoPostProcessStatusCmd.Handler]]
  class N119 commandhandler
  N120{{SyncVideoPostProcessStatusCmd.Request}}
  class N120 command
  N121[[ApplyVideoPostProcessingEncryptResultCmd.Handler]]
  class N121 commandhandler
  N122{{ApplyVideoPostProcessingEncryptResultCmd.Request}}
  class N122 command
  N123[[ApplyVideoPostProcessingTranscodeResultCmd.Handler]]
  class N123 commandhandler
  N124{{ApplyVideoPostProcessingTranscodeResultCmd.Request}}
  class N124 command
  N125[[ApplyVideoPostProcessingVariantEncryptResultCmd.Handler]]
  class N125 commandhandler
  N126{{ApplyVideoPostProcessingVariantEncryptResultCmd.Request}}
  class N126 command
  N127[[PrepareVideoPostProcessingEncryptContextCmd.Handler]]
  class N127 commandhandler
  N128{{PrepareVideoPostProcessingEncryptContextCmd.Request}}
  class N128 command
  N129[[StartVideoPostProcessingCmd.Handler]]
  class N129 commandhandler
  N130{{StartVideoPostProcessingCmd.Request}}
  class N130 command
  N131[[SetVideoQualityPolicyCmd.Handler]]
  class N131 commandhandler
  N132{{SetVideoQualityPolicyCmd.Request}}
  class N132 command
  N133{{CleanTempFilesCli.Request}}
  class N133 cli
  N134{{DeleteVideoFileResourcesCli.Request}}
  class N134 cli
  N135{{RefreshLoginSessionCli.Request}}
  class N135 cli
  N136{{RemoveVideoSearchIndexCli.Request}}
  class N136 cli
  N137{{CreateUploadSessionTempDirCli.Request}}
  class N137 cli
  N138{{DeleteUploadSessionTempDirCli.Request}}
  class N138 cli
  N139{{EncryptHlsVariantWithKeyCli.Request}}
  class N139 cli
  N140{{GenerateEncryptedMasterByVariantsCli.Request}}
  class N140 cli
  N141{{GenerateVideoAbrMasterCli.Request}}
  class N141 cli
  N142{{MergeUploadToMp4ByPathCli.Request}}
  class N142 cli
  N143{{TranscodeVideoFileToAbrByPathCli.Request}}
  class N143 cli
  N144{{UploadVideoAbrOutputCli.Request}}
  class N144 cli
  N145{{UniqueCategoryCodeQry.Request}}
  class N145 query
  N146{{GetUserActionsByVideoIdQry.Request}}
  class N146 query
  N147{{UniqueCustomerActionTypeQry.Request}}
  class N147 query
  N148{{CheckFocusStatusQry.Request}}
  class N148 query
  N149{{GetCustomerProfileQry.Request}}
  class N149 query
  N150{{UniqueCustomerProfileEmailQry.Request}}
  class N150 query
  N151{{UniqueCustomerProfileNickNameQry.Request}}
  class N151 query
  N152{{UniqueCustomerProfilePhoneQry.Request}}
  class N152 query
  N153{{GetCustomerVideoSeriesInfoQry.Request}}
  class N153 query
  N154{{CheckNicknameExistsQry.Request}}
  class N154 query
  N155{{CheckUserExistsQry.Request}}
  class N155 query
  N156{{UniqueUserEmailQry.Request}}
  class N156 query
  N157{{UniqueUserPhoneQry.Request}}
  class N157 query
  N158{{GetRecentPasswordFailureCountQry.Request}}
  class N158 query
  N159{{GetVideoInfoQry.Request}}
  class N159 query
  N160{{UniqueVideoFileVariantQry.Request}}
  class N160 query
  N161{{GetCommentByIdQry.Request}}
  class N161 query
  N162{{CheckDanmukuExistsQry.Request}}
  class N162 query
  N163{{GetDanmukuOwnerQry.Request}}
  class N163 query
  N164{{GetVideoPostInfoQry.Request}}
  class N164 query
  N165{{UniqueVideoHlsEncryptKeyQry.Request}}
  class N165 query
  N166{{UniqueVideoHlsKeyTokenQry.Request}}
  class N166 query
  N167{{UniqueVideoFilePostQry.Request}}
  class N167 query
  N168{{UniqueVideoFilePostUploadIdQry.Request}}
  class N168 query
  N169{{UniqueVideoFilePostVariantQry.Request}}
  class N169 query
  N170{{GetVideoPostProcessingEncryptContextQry.Request}}
  class N170 query
  N171{{UniqueVideoPostProcessingFileQry.Request}}
  class N171 query
  N172{{UniqueVideoPostProcessingQry.Request}}
  class N172 query
  N173{{UniqueVideoPostProcessingVariantQry.Request}}
  class N173 query
  N174{{UniqueVideoQualityPolicyQry.Request}}
  class N174 query
  N175{{GetUploadSessionTempPathQry.Request}}
  class N175 query
  N176[[CategoryBasicInfoUpdatedDomainEventSubscriber::on]]
  class N176 domaineventhandler
  N177[[CategoryCodeChangedDomainEventSubscriber::on]]
  class N177 domaineventhandler
  N178[[CategoryCreatedDomainEventSubscriber::on1]]
  class N178 domaineventhandler
  N179[[CategoryDeletedDomainEventSubscriber::on]]
  class N179 domaineventhandler
  N180[[CategoryNodePathUpdatedDomainEventSubscriber::on]]
  class N180 domaineventhandler
  N181[[CategoryParentChangedDomainEventSubscriber::on]]
  class N181 domaineventhandler
  N182[[CategorySortChangedDomainEventSubscriber::on]]
  class N182 domaineventhandler
  N183[[CustomerCoinGivenDomainEventSubscriber::on1]]
  class N183 domaineventhandler
  N184[[CustomerCoinGivenDomainEventSubscriber::on2]]
  class N184 domaineventhandler
  N185[[CustomerCollectedVideoDomainEventSubscriber::on]]
  class N185 domaineventhandler
  N186[[CustomerCollectedVideoDomainEventSubscriber::onSendMessage]]
  class N186 domaineventhandler
  N187[[CustomerDislikedCommentDomainEventSubscriber::on]]
  class N187 domaineventhandler
  N188[[CustomerLikedCommentDomainEventSubscriber::on]]
  class N188 domaineventhandler
  N189[[CustomerLikedVideoDomainEventSubscriber::on]]
  class N189 domaineventhandler
  N190[[CustomerLikedVideoDomainEventSubscriber::onSendMessage]]
  class N190 domaineventhandler
  N191[[CustomerUncollectedVideoDomainEventSubscriber::on]]
  class N191 domaineventhandler
  N192[[CustomerUndislikedCommentDomainEventSubscriber::on]]
  class N192 domaineventhandler
  N193[[CustomerUnlikedCommentDomainEventSubscriber::on]]
  class N193 domaineventhandler
  N194[[CustomerUnlikedVideoDomainEventSubscriber::on]]
  class N194 domaineventhandler
  N195[[UserFocusedDomainEventSubscriber::on]]
  class N195 domaineventhandler
  N196[[UserUnfocusedDomainEventSubscriber::on]]
  class N196 domaineventhandler
  N197[[CustomerMessageCollectionCreatedDomainEventSubscriber::on]]
  class N197 domaineventhandler
  N198[[CustomerMessageCommentMentionCreatedDomainEventSubscriber::on]]
  class N198 domaineventhandler
  N199[[CustomerMessageLikeCreatedDomainEventSubscriber::on]]
  class N199 domaineventhandler
  N200[[CustomerMessagePrivateCreatedDomainEventSubscriber::on]]
  class N200 domaineventhandler
  N201[[CustomerMessageSystemCreatedDomainEventSubscriber::on]]
  class N201 domaineventhandler
  N202[[CustomerAvatarUpdatedDomainEventSubscriber::on]]
  class N202 domaineventhandler
  N203[[CustomerNicknameUpdatedDomainEventSubscriber::on]]
  class N203 domaineventhandler
  N204[[CustomerProfileCoinsRewardedDomainEventSubscriber::on]]
  class N204 domaineventhandler
  N205[[CustomerProfileCreatedDomainEventSubscriber::on1]]
  class N205 domaineventhandler
  N206[[CustomerProfilePhoneChangedDomainEventSubscriber::on]]
  class N206 domaineventhandler
  N207[[CustomerProfileRewardCoinsReclaimedDomainEventSubscriber::on]]
  class N207 domaineventhandler
  N208[[CustomerProfileUpdatedDomainEventSubscriber::on]]
  class N208 domaineventhandler
  N209[[StatisticsCountUpdatedDomainEventSubscriber::on]]
  class N209 domaineventhandler
  N210[[AccountDisabledDomainEventSubscriber::on]]
  class N210 domaineventhandler
  N211[[AccountEnabledDomainEventSubscriber::on]]
  class N211 domaineventhandler
  N212[[LoginInfoUpdatedDomainEventSubscriber::on]]
  class N212 domaineventhandler
  N213[[PasswordChangedDomainEventSubscriber::on]]
  class N213 domaineventhandler
  N214[[RelationshipBoundDomainEventSubscriber::on]]
  class N214 domaineventhandler
  N215[[UserCreatedDomainEventSubscriber::on]]
  class N215 domaineventhandler
  N216[[UserPhoneChangedDomainEventSubscriber::on]]
  class N216 domaineventhandler
  N217[[PasswordInputFailedDomainEventSubscriber::on]]
  class N217 domaineventhandler
  N218[[VideoBasicsSyncedDomainEventSubscriber::on]]
  class N218 domaineventhandler
  N219[[VideoCoinCountDeltaAppliedDomainEventSubscriber::on]]
  class N219 domaineventhandler
  N220[[VideoCollectCountDeltaAppliedDomainEventSubscriber::on]]
  class N220 domaineventhandler
  N221[[VideoCommentCountDeltaAppliedDomainEventSubscriber::on]]
  class N221 domaineventhandler
  N222[[VideoCreatedDomainEventSubscriber::on]]
  class N222 domaineventhandler
  N223[[VideoDanmukuCountDeltaAppliedDomainEventSubscriber::on]]
  class N223 domaineventhandler
  N224[[VideoDeletedDomainEventSubscriber::cleanupComments]]
  class N224 domaineventhandler
  N225[[VideoDeletedDomainEventSubscriber::cleanupDanmaku]]
  class N225 domaineventhandler
  N226[[VideoDeletedDomainEventSubscriber::removeSearchIndex]]
  class N226 domaineventhandler
  N227[[VideoInteractionChangedDomainEventSubscriber::on]]
  class N227 domaineventhandler
  N228[[VideoLastPlayTimeAttachedDomainEventSubscriber::on]]
  class N228 domaineventhandler
  N229[[VideoLikeCountDeltaAppliedDomainEventSubscriber::on]]
  class N229 domaineventhandler
  N230[[VideoPlayCountDeltaAppliedDomainEventSubscriber::on]]
  class N230 domaineventhandler
  N231[[VideoPostDeletedDomainEventSubscriber::adjustAuthorCoin]]
  class N231 domaineventhandler
  N232[[VideoPostDeletedDomainEventSubscriber::deletePhysicalFiles]]
  class N232 domaineventhandler
  N233[[VideoPostDeletedDomainEventSubscriber::removeVideo]]
  class N233 domaineventhandler
  N234[[VideoRecommendedDomainEventSubscriber::on]]
  class N234 domaineventhandler
  N235[[VideoUnrecommendedDomainEventSubscriber::on]]
  class N235 domaineventhandler
  N236[[VideoAuditTraceRecordedDomainEventSubscriber::sendAuditMessage]]
  class N236 domaineventhandler
  N237[[VideoAuditTraceRecordedDomainEventSubscriber::updateVideoStatus]]
  class N237 domaineventhandler
  N238[[CommentDeletedDomainEventSubscriber::on]]
  class N238 domaineventhandler
  N239[[CommentDeletedDomainEventSubscriber::on1]]
  class N239 domaineventhandler
  N240[[CommentPostedDomainEventSubscriber::on]]
  class N240 domaineventhandler
  N241[[CommentPostedDomainEventSubscriber::on1]]
  class N241 domaineventhandler
  N242[[CommentPostedDomainEventSubscriber::on2]]
  class N242 domaineventhandler
  N243[[CommentToppedDomainEventSubscriber::on]]
  class N243 domaineventhandler
  N244[[CommentUntoppedDomainEventSubscriber::on]]
  class N244 domaineventhandler
  N245[[DanmukuDeletedDomainEventSubscriber::on]]
  class N245 domaineventhandler
  N246[[DanmukuPostedDomainEventSubscriber::on]]
  class N246 domaineventhandler
  N247[[VideoPostQualityKeyGeneratedDomainEventSubscriber::on]]
  class N247 domaineventhandler
  N248[[UploadSessionAbortedDomainEventSubscriber::on]]
  class N248 domaineventhandler
  N249[[UploadSessionCreatedDomainEventSubscriber::on]]
  class N249 domaineventhandler
  N250[[VideoFileUploadSessionChunkUploadedDomainEventSubscriber::on]]
  class N250 domaineventhandler
  N251[[VideoFileUploadSessionMarkedDoneDomainEventSubscriber::on]]
  class N251 domaineventhandler
  N252[[VideoHlsKeyTokenIssuedDomainEventSubscriber::addPlayHistoryCmd]]
  class N252 domaineventhandler
  N253[[VideoHlsKeyTokenIssuedDomainEventSubscriber::applyVideoPlayCountDelta]]
  class N253 domaineventhandler
  N254[[VideoPlayHistoryCreatedDomainEventSubscriber::on]]
  class N254 domaineventhandler
  N255[[VideoPlayHistoryProgressUpdatedDomainEventSubscriber::on]]
  class N255 domaineventhandler
  N256[[VideoAuditFailedDomainEventSubscriber::on]]
  class N256 domaineventhandler
  N257[[VideoAuditPassedDomainEventSubscriber::on]]
  class N257 domaineventhandler
  N258[[VideoAuditPassedDomainEventSubscriber::on1]]
  class N258 domaineventhandler
  N259[[VideoAuditPassedDomainEventSubscriber::on2]]
  class N259 domaineventhandler
  N260[[VideoAuditPassedDomainEventSubscriber::on3]]
  class N260 domaineventhandler
  N261[[VideoPostCreatedDomainEventSubscriber::on]]
  class N261 domaineventhandler
  N262[[VideoPostInteractionChangedDomainEventSubscriber::on]]
  class N262 domaineventhandler
  N263[[VideoPostTranscodingRequestedDomainEventSubscriber::on]]
  class N263 domaineventhandler
  N264[[VideoPostProcessingCompletedDomainEventSubscriber::on]]
  class N264 domaineventhandler
  N265[[VideoPostProcessingEncryptContextPreparedDomainEventSubscriber::on]]
  class N265 domaineventhandler
  N266[[VideoPostProcessingFileEncryptCompletedDomainEventSubscriber::on]]
  class N266 domaineventhandler
  N267[[VideoPostProcessingStartedDomainEventSubscriber::on]]
  class N267 domaineventhandler
  N268[[VideoPostProcessingTranscodeCompletedDomainEventSubscriber::on]]
  class N268 domaineventhandler
  N269(Category::&lt;get-id&gt;)
  class N269 entitymethod
  N270(Category::&lt;get-nodePath&gt;)
  class N270 entitymethod
  N271(Category::&lt;get-parentId&gt;)
  class N271 entitymethod
  N272(Category::&lt;get-sort&gt;)
  class N272 entitymethod
  N273(Category::addSort)
  class N273 entitymethod
  N274(Category::changeSort)
  class N274 entitymethod
  N275(Category::updateNodePath)
  class N275 entitymethod
  N276((CategoryBasicInfoUpdatedDomainEvent))
  class N276 domainevent
  N277((CategoryCodeChangedDomainEvent))
  class N277 domainevent
  N278((CategoryCreatedDomainEvent))
  class N278 domainevent
  N279((CategoryDeletedDomainEvent))
  class N279 domainevent
  N280((CategoryNodePathUpdatedDomainEvent))
  class N280 domainevent
  N281((CategoryParentChangedDomainEvent))
  class N281 domainevent
  N282((CategorySortChangedDomainEvent))
  class N282 domainevent
  N283((CustomerCoinGivenDomainEvent))
  class N283 domainevent
  N284((CustomerCollectedVideoDomainEvent))
  class N284 domainevent
  N285((CustomerDislikedCommentDomainEvent))
  class N285 domainevent
  N286((CustomerLikedCommentDomainEvent))
  class N286 domainevent
  N287((CustomerLikedVideoDomainEvent))
  class N287 domainevent
  N288((CustomerUncollectedVideoDomainEvent))
  class N288 domainevent
  N289((CustomerUndislikedCommentDomainEvent))
  class N289 domainevent
  N290((CustomerUnlikedCommentDomainEvent))
  class N290 domainevent
  N291((CustomerUnlikedVideoDomainEvent))
  class N291 domainevent
  N292((UserFocusedDomainEvent))
  class N292 domainevent
  N293((UserUnfocusedDomainEvent))
  class N293 domainevent
  N294(CustomerMessage::onCreate)
  class N294 entitymethod
  N295((CustomerMessageCollectionCreatedDomainEvent))
  class N295 domainevent
  N296((CustomerMessageCommentMentionCreatedDomainEvent))
  class N296 domainevent
  N297((CustomerMessageLikeCreatedDomainEvent))
  class N297 domainevent
  N298((CustomerMessagePrivateCreatedDomainEvent))
  class N298 domainevent
  N299((CustomerMessageSystemCreatedDomainEvent))
  class N299 domainevent
  N300(CustomerProfile::onCreate)
  class N300 entitymethod
  N301(CustomerProfile::reclaimRewardCoins)
  class N301 entitymethod
  N302(CustomerProfile::rewardCoins)
  class N302 entitymethod
  N303(CustomerProfile::spendCoins)
  class N303 entitymethod
  N304(CustomerProfile::transferCoin)
  class N304 entitymethod
  N305((CustomerAvatarUpdatedDomainEvent))
  class N305 domainevent
  N306((CustomerNicknameUpdatedDomainEvent))
  class N306 domainevent
  N307((CustomerProfileCoinsRewardedDomainEvent))
  class N307 domainevent
  N308((CustomerProfileCreatedDomainEvent))
  class N308 domainevent
  N309((CustomerProfilePhoneChangedDomainEvent))
  class N309 domainevent
  N310((CustomerProfileRewardCoinsReclaimedDomainEvent))
  class N310 domainevent
  N311((CustomerProfileUpdatedDomainEvent))
  class N311 domainevent
  N312(Statistics::onCreate)
  class N312 entitymethod
  N313(Statistics::updateCount)
  class N313 entitymethod
  N314((StatisticsCountUpdatedDomainEvent))
  class N314 domainevent
  N315(User::bindPhone)
  class N315 entitymethod
  N316(User::bindingRelationship)
  class N316 entitymethod
  N317((AccountDisabledDomainEvent))
  class N317 domainevent
  N318((AccountEnabledDomainEvent))
  class N318 domainevent
  N319((LoginInfoUpdatedDomainEvent))
  class N319 domainevent
  N320((PasswordChangedDomainEvent))
  class N320 domainevent
  N321((RelationshipBoundDomainEvent))
  class N321 domainevent
  N322((UserCreatedDomainEvent))
  class N322 domainevent
  N323((UserPhoneChangedDomainEvent))
  class N323 domainevent
  N324(UserAbnormalOperationLog::&lt;get-id&gt;)
  class N324 entitymethod
  N325(UserAbnormalOperationLog::onCreate)
  class N325 entitymethod
  N326((PasswordInputFailedDomainEvent))
  class N326 domainevent
  N327(Video::&lt;get-coinCount&gt;)
  class N327 entitymethod
  N328(Video::&lt;get-collectCount&gt;)
  class N328 entitymethod
  N329(Video::&lt;get-commentCount&gt;)
  class N329 entitymethod
  N330(Video::&lt;get-customerId&gt;)
  class N330 entitymethod
  N331(Video::&lt;get-danmukuCount&gt;)
  class N331 entitymethod
  N332(Video::&lt;get-id&gt;)
  class N332 entitymethod
  N333(Video::&lt;get-likeCount&gt;)
  class N333 entitymethod
  N334(Video::&lt;get-playCount&gt;)
  class N334 entitymethod
  N335(Video::applyCoinCountDelta)
  class N335 entitymethod
  N336(Video::applyCollectCountDelta)
  class N336 entitymethod
  N337(Video::applyCommentCountDelta)
  class N337 entitymethod
  N338(Video::applyDanmukuCountDelta)
  class N338 entitymethod
  N339(Video::applyLikeCountDelta)
  class N339 entitymethod
  N340(Video::applyPlayCountDelta)
  class N340 entitymethod
  N341(Video::changeInteraction)
  class N341 entitymethod
  N342(Video::onCreate)
  class N342 entitymethod
  N343(Video::onDelete)
  class N343 entitymethod
  N344(Video::syncFromBasics)
  class N344 entitymethod
  N345((VideoBasicsSyncedDomainEvent))
  class N345 domainevent
  N346((VideoCoinCountDeltaAppliedDomainEvent))
  class N346 domainevent
  N347((VideoCollectCountDeltaAppliedDomainEvent))
  class N347 domainevent
  N348((VideoCommentCountDeltaAppliedDomainEvent))
  class N348 domainevent
  N349((VideoCreatedDomainEvent))
  class N349 domainevent
  N350((VideoDanmukuCountDeltaAppliedDomainEvent))
  class N350 domainevent
  N351((VideoDeletedDomainEvent))
  class N351 domainevent
  N352((VideoInteractionChangedDomainEvent))
  class N352 domainevent
  N353((VideoLastPlayTimeAttachedDomainEvent))
  class N353 domainevent
  N354((VideoLikeCountDeltaAppliedDomainEvent))
  class N354 domainevent
  N355((VideoPlayCountDeltaAppliedDomainEvent))
  class N355 domainevent
  N356((VideoRecommendedDomainEvent))
  class N356 domainevent
  N357((VideoUnrecommendedDomainEvent))
  class N357 domainevent
  N358((VideoAuditTraceRecordedDomainEvent))
  class N358 domainevent
  N359(VideoComment::&lt;get-customerId&gt;)
  class N359 entitymethod
  N360(VideoComment::onDelete)
  class N360 entitymethod
  N361(VideoComment::updateStatistics)
  class N361 entitymethod
  N362((CommentDeletedDomainEvent))
  class N362 domainevent
  N363((CommentPostedDomainEvent))
  class N363 domainevent
  N364((CommentToppedDomainEvent))
  class N364 domainevent
  N365((CommentUntoppedDomainEvent))
  class N365 domainevent
  N366(VideoDanmuku::onDelete)
  class N366 entitymethod
  N367((DanmukuDeletedDomainEvent))
  class N367 domainevent
  N368((DanmukuPostedDomainEvent))
  class N368 domainevent
  N369(VideoFileUploadSession::initTempAndStartUploading)
  class N369 entitymethod
  N370((UploadSessionAbortedDomainEvent))
  class N370 domainevent
  N371((UploadSessionCreatedDomainEvent))
  class N371 domainevent
  N372((VideoFileUploadSessionChunkUploadedDomainEvent))
  class N372 domainevent
  N373((VideoFileUploadSessionMarkedDoneDomainEvent))
  class N373 domainevent
  N374(VideoHlsEncryptKey::bindVideoId)
  class N374 entitymethod
  N375(VideoHlsEncryptKey::onCreate)
  class N375 entitymethod
  N376((VideoHlsEncryptKeyCreatedDomainEvent))
  class N376 domainevent
  N377(VideoHlsKeyToken::bindVideoId)
  class N377 entitymethod
  N378((VideoHlsKeyTokenIssuedDomainEvent))
  class N378 domainevent
  N379(VideoPlayHistory::onCreate)
  class N379 entitymethod
  N380(VideoPlayHistory::updatePlayProgress)
  class N380 entitymethod
  N381((VideoPlayHistoryCreatedDomainEvent))
  class N381 domainevent
  N382((VideoPlayHistoryProgressUpdatedDomainEvent))
  class N382 domainevent
  N383(VideoFilePost::&lt;get-customerId&gt;)
  class N383 entitymethod
  N384(VideoFilePost::&lt;get-duration&gt;)
  class N384 entitymethod
  N385(VideoFilePost::&lt;get-fileIndex&gt;)
  class N385 entitymethod
  N386(VideoFilePost::&lt;get-fileName&gt;)
  class N386 entitymethod
  N387(VideoFilePost::&lt;get-fileSize&gt;)
  class N387 entitymethod
  N388(VideoFilePost::&lt;get-id&gt;)
  class N388 entitymethod
  N389(VideoFilePost::&lt;get-videoFilePostVariants&gt;)
  class N389 entitymethod
  N390(VideoFilePost::applyEncryptResult)
  class N390 entitymethod
  N391(VideoFilePost::applyTranscodeResult)
  class N391 entitymethod
  N392(VideoFilePost::syncVariants)
  class N392 entitymethod
  N393(VideoFilePostVariant::&lt;get-audioBitrateKbps&gt;)
  class N393 entitymethod
  N394(VideoFilePostVariant::&lt;get-bandwidthBps&gt;)
  class N394 entitymethod
  N395(VideoFilePostVariant::&lt;get-height&gt;)
  class N395 entitymethod
  N396(VideoFilePostVariant::&lt;get-playlistPath&gt;)
  class N396 entitymethod
  N397(VideoFilePostVariant::&lt;get-quality&gt;)
  class N397 entitymethod
  N398(VideoFilePostVariant::&lt;get-segmentDuration&gt;)
  class N398 entitymethod
  N399(VideoFilePostVariant::&lt;get-segmentPrefix&gt;)
  class N399 entitymethod
  N400(VideoFilePostVariant::&lt;get-videoBitrateKbps&gt;)
  class N400 entitymethod
  N401(VideoFilePostVariant::&lt;get-width&gt;)
  class N401 entitymethod
  N402(VideoPost::&lt;get-customerId&gt;)
  class N402 entitymethod
  N403(VideoPost::&lt;get-videoFilePosts&gt;)
  class N403 entitymethod
  N404(VideoPost::applyProcessStatus)
  class N404 entitymethod
  N405(VideoPost::reviewFail)
  class N405 entitymethod
  N406(VideoPost::reviewPass)
  class N406 entitymethod
  N407(VideoPost::updateDuration)
  class N407 entitymethod
  N408((VideoAuditFailedDomainEvent))
  class N408 domainevent
  N409((VideoAuditPassedDomainEvent))
  class N409 domainevent
  N410((VideoPostCreatedDomainEvent))
  class N410 domainevent
  N411((VideoPostDeletedDomainEvent))
  class N411 domainevent
  N412((VideoPostInteractionChangedDomainEvent))
  class N412 domainevent
  N413((VideoPostTranscodingRequestedDomainEvent))
  class N413 domainevent
  N414(VideoPostProcessing::&lt;get-videoPostProcessingFiles&gt;)
  class N414 entitymethod
  N415(VideoPostProcessing::appendFiles)
  class N415 entitymethod
  N416(VideoPostProcessing::applyEncryptResult)
  class N416 entitymethod
  N417(VideoPostProcessing::applyTranscodeResult)
  class N417 entitymethod
  N418(VideoPostProcessing::applyVariantEncryptResult)
  class N418 entitymethod
  N419(VideoPostProcessing::onCreate)
  class N419 entitymethod
  N420(VideoPostProcessing::prepareEncryptContext)
  class N420 entitymethod
  N421(VideoPostProcessingFile::&lt;get-encryptKeyVersion&gt;)
  class N421 entitymethod
  N422(VideoPostProcessingFile::&lt;get-fileIndex&gt;)
  class N422 entitymethod
  N423((VideoPostProcessingCompletedDomainEvent))
  class N423 domainevent
  N424((VideoPostProcessingEncryptContextPreparedDomainEvent))
  class N424 domainevent
  N425((VideoPostProcessingFileEncryptCompletedDomainEvent))
  class N425 domainevent
  N426((VideoPostProcessingStartedDomainEvent))
  class N426 domainevent
  N427((VideoPostProcessingTranscodeCompletedDomainEvent))
  class N427 domainevent
  N428(VideoQualityPolicy::applyPolicy)
  class N428 entitymethod
  N429(VideoQualityPolicy::onCreate)
  class N429 entitymethod
  N1 -->|CommandSenderMethodToCommand| N108
  N1 -->|CommandSenderMethodToCommand| N110
  N1 -->|CommandSenderMethodToCommand| N112
  N1 -->|CommandSenderMethodToCommand| N124
  N1 -->|CommandSenderMethodToCommand| N132
  N1 -->|CliSenderMethodToCli| N138
  N1 -->|CliSenderMethodToCli| N141
  N1 -->|CliSenderMethodToCli| N142
  N1 -->|CliSenderMethodToCli| N143
  N1 -->|CliSenderMethodToCli| N144
  N1 -->|QuerySenderMethodToQuery| N145
  N1 -->|QuerySenderMethodToQuery| N146
  N1 -->|QuerySenderMethodToQuery| N147
  N1 -->|QuerySenderMethodToQuery| N148
  N1 -->|QuerySenderMethodToQuery| N149
  N1 -->|QuerySenderMethodToQuery| N150
  N1 -->|QuerySenderMethodToQuery| N151
  N1 -->|QuerySenderMethodToQuery| N152
  N1 -->|QuerySenderMethodToQuery| N153
  N1 -->|QuerySenderMethodToQuery| N154
  N1 -->|QuerySenderMethodToQuery| N155
  N1 -->|QuerySenderMethodToQuery| N156
  N1 -->|QuerySenderMethodToQuery| N157
  N1 -->|QuerySenderMethodToQuery| N159
  N1 -->|QuerySenderMethodToQuery| N160
  N1 -->|QuerySenderMethodToQuery| N161
  N1 -->|QuerySenderMethodToQuery| N162
  N1 -->|QuerySenderMethodToQuery| N163
  N1 -->|QuerySenderMethodToQuery| N164
  N1 -->|QuerySenderMethodToQuery| N165
  N1 -->|QuerySenderMethodToQuery| N166
  N1 -->|QuerySenderMethodToQuery| N167
  N1 -->|QuerySenderMethodToQuery| N168
  N1 -->|QuerySenderMethodToQuery| N169
  N1 -->|QuerySenderMethodToQuery| N171
  N1 -->|QuerySenderMethodToQuery| N172
  N1 -->|QuerySenderMethodToQuery| N173
  N1 -->|QuerySenderMethodToQuery| N174
  N1 -->|QuerySenderMethodToQuery| N175
  N1 -->|EntityMethodToDomainEvent| N276
  N1 -->|EntityMethodToDomainEvent| N277
  N1 -->|EntityMethodToDomainEvent| N278
  N1 -->|EntityMethodToDomainEvent| N279
  N1 -->|EntityMethodToDomainEvent| N280
  N1 -->|EntityMethodToDomainEvent| N281
  N1 -->|EntityMethodToDomainEvent| N282
  N1 -->|EntityMethodToDomainEvent| N283
  N1 -->|EntityMethodToDomainEvent| N284
  N1 -->|EntityMethodToDomainEvent| N285
  N1 -->|EntityMethodToDomainEvent| N286
  N1 -->|EntityMethodToDomainEvent| N287
  N1 -->|EntityMethodToDomainEvent| N288
  N1 -->|EntityMethodToDomainEvent| N289
  N1 -->|EntityMethodToDomainEvent| N290
  N1 -->|EntityMethodToDomainEvent| N291
  N1 -->|EntityMethodToDomainEvent| N292
  N1 -->|EntityMethodToDomainEvent| N293
  N1 -->|EntityMethodToDomainEvent| N295
  N1 -->|EntityMethodToDomainEvent| N296
  N1 -->|EntityMethodToDomainEvent| N297
  N1 -->|EntityMethodToDomainEvent| N298
  N1 -->|EntityMethodToDomainEvent| N299
  N1 -->|EntityMethodToDomainEvent| N305
  N1 -->|EntityMethodToDomainEvent| N306
  N1 -->|EntityMethodToDomainEvent| N307
  N1 -->|EntityMethodToDomainEvent| N308
  N1 -->|EntityMethodToDomainEvent| N309
  N1 -->|EntityMethodToDomainEvent| N310
  N1 -->|EntityMethodToDomainEvent| N311
  N1 -->|EntityMethodToDomainEvent| N314
  N1 -->|EntityMethodToDomainEvent| N317
  N1 -->|EntityMethodToDomainEvent| N318
  N1 -->|EntityMethodToDomainEvent| N319
  N1 -->|EntityMethodToDomainEvent| N320
  N1 -->|EntityMethodToDomainEvent| N321
  N1 -->|EntityMethodToDomainEvent| N322
  N1 -->|EntityMethodToDomainEvent| N323
  N1 -->|EntityMethodToDomainEvent| N326
  N1 -->|EntityMethodToDomainEvent| N345
  N1 -->|EntityMethodToDomainEvent| N346
  N1 -->|EntityMethodToDomainEvent| N347
  N1 -->|EntityMethodToDomainEvent| N348
  N1 -->|EntityMethodToDomainEvent| N349
  N1 -->|EntityMethodToDomainEvent| N350
  N1 -->|EntityMethodToDomainEvent| N351
  N1 -->|EntityMethodToDomainEvent| N352
  N1 -->|EntityMethodToDomainEvent| N353
  N1 -->|EntityMethodToDomainEvent| N354
  N1 -->|EntityMethodToDomainEvent| N355
  N1 -->|EntityMethodToDomainEvent| N356
  N1 -->|EntityMethodToDomainEvent| N357
  N1 -->|EntityMethodToDomainEvent| N358
  N1 -->|EntityMethodToDomainEvent| N362
  N1 -->|EntityMethodToDomainEvent| N363
  N1 -->|EntityMethodToDomainEvent| N364
  N1 -->|EntityMethodToDomainEvent| N365
  N1 -->|EntityMethodToDomainEvent| N367
  N1 -->|EntityMethodToDomainEvent| N368
  N1 -->|EntityMethodToDomainEvent| N370
  N1 -->|EntityMethodToDomainEvent| N371
  N1 -->|EntityMethodToDomainEvent| N372
  N1 -->|EntityMethodToDomainEvent| N373
  N1 -->|EntityMethodToDomainEvent| N376
  N1 -->|EntityMethodToDomainEvent| N378
  N1 -->|EntityMethodToDomainEvent| N381
  N1 -->|EntityMethodToDomainEvent| N382
  N1 -->|EntityMethodToDomainEvent| N408
  N1 -->|EntityMethodToDomainEvent| N409
  N1 -->|EntityMethodToDomainEvent| N410
  N1 -->|EntityMethodToDomainEvent| N411
  N1 -->|EntityMethodToDomainEvent| N412
  N1 -->|EntityMethodToDomainEvent| N413
  N1 -->|EntityMethodToDomainEvent| N423
  N1 -->|EntityMethodToDomainEvent| N424
  N1 -->|EntityMethodToDomainEvent| N425
  N1 -->|EntityMethodToDomainEvent| N426
  N1 -->|EntityMethodToDomainEvent| N427
  N45 -->|CommandHandlerToEntityMethod| N269
  N45 -->|CommandHandlerToEntityMethod| N270
  N45 -->|CommandHandlerToEntityMethod| N271
  N45 -->|CommandHandlerToEntityMethod| N272
  N45 -->|CommandHandlerToEntityMethod| N273
  N45 -->|CommandHandlerToEntityMethod| N274
  N45 -->|CommandHandlerToEntityMethod| N275
  N46 -->|CommandToCommandHandler| N45
  N47 -->|CommandHandlerToEntityMethod| N294
  N47 -->|CommandHandlerToEntityMethod| N330
  N48 -->|CommandToCommandHandler| N47
  N49 -->|CommandHandlerToEntityMethod| N294
  N49 -->|CommandHandlerToEntityMethod| N330
  N50 -->|CommandToCommandHandler| N49
  N51 -->|CommandHandlerToEntityMethod| N294
  N51 -->|CommandHandlerToEntityMethod| N330
  N52 -->|CommandToCommandHandler| N51
  N53 -->|CommandHandlerToEntityMethod| N294
  N53 -->|CommandHandlerToEntityMethod| N359
  N54 -->|CommandToCommandHandler| N53
  N55 -->|CommandHandlerToEntityMethod| N294
  N55 -->|CommandHandlerToEntityMethod| N402
  N56 -->|CommandToCommandHandler| N55
  N57 -->|CommandHandlerToEntityMethod| N294
  N57 -->|CommandHandlerToEntityMethod| N402
  N58 -->|CommandToCommandHandler| N57
  N59 -->|CommandHandlerToEntityMethod| N301
  N60 -->|CommandToCommandHandler| N59
  N61 -->|CommandHandlerToEntityMethod| N300
  N62 -->|CommandToCommandHandler| N61
  N63 -->|CommandHandlerToEntityMethod| N302
  N64 -->|CommandToCommandHandler| N63
  N65 -->|CommandHandlerToEntityMethod| N303
  N66 -->|CommandToCommandHandler| N65
  N67 -->|CommandHandlerToEntityMethod| N304
  N68 -->|CommandToCommandHandler| N67
  N69 -->|CommandHandlerToEntityMethod| N312
  N69 -->|CommandHandlerToEntityMethod| N313
  N70 -->|CommandToCommandHandler| N69
  N71 -->|CommandHandlerToEntityMethod| N315
  N72 -->|CommandToCommandHandler| N71
  N73 -->|CommandHandlerToEntityMethod| N316
  N74 -->|CommandToCommandHandler| N73
  N75 -->|CommandHandlerToEntityMethod| N324
  N75 -->|CommandHandlerToEntityMethod| N325
  N76 -->|CommandToCommandHandler| N75
  N77 -->|CommandHandlerToEntityMethod| N327
  N77 -->|CommandHandlerToEntityMethod| N332
  N77 -->|CommandHandlerToEntityMethod| N335
  N78 -->|CommandToCommandHandler| N77
  N79 -->|CommandHandlerToEntityMethod| N328
  N79 -->|CommandHandlerToEntityMethod| N332
  N79 -->|CommandHandlerToEntityMethod| N336
  N80 -->|CommandToCommandHandler| N79
  N81 -->|CommandHandlerToEntityMethod| N329
  N81 -->|CommandHandlerToEntityMethod| N332
  N81 -->|CommandHandlerToEntityMethod| N337
  N82 -->|CommandToCommandHandler| N81
  N83 -->|CommandHandlerToEntityMethod| N331
  N83 -->|CommandHandlerToEntityMethod| N332
  N83 -->|CommandHandlerToEntityMethod| N338
  N84 -->|CommandToCommandHandler| N83
  N85 -->|CommandHandlerToEntityMethod| N332
  N85 -->|CommandHandlerToEntityMethod| N333
  N85 -->|CommandHandlerToEntityMethod| N339
  N86 -->|CommandToCommandHandler| N85
  N87 -->|CommandHandlerToEntityMethod| N332
  N87 -->|CommandHandlerToEntityMethod| N334
  N87 -->|CommandHandlerToEntityMethod| N340
  N88 -->|CommandToCommandHandler| N87
  N89 -->|CommandHandlerToEntityMethod| N330
  N89 -->|CommandHandlerToEntityMethod| N341
  N90 -->|CommandToCommandHandler| N89
  N91 -->|CommandHandlerToEntityMethod| N343
  N92 -->|CommandToCommandHandler| N91
  N93 -->|CommandHandlerToEntityMethod| N332
  N93 -->|CommandHandlerToEntityMethod| N342
  N93 -->|CommandHandlerToEntityMethod| N344
  N93 -->|CommandHandlerToEntityMethod| N383
  N93 -->|CommandHandlerToEntityMethod| N384
  N93 -->|CommandHandlerToEntityMethod| N385
  N93 -->|CommandHandlerToEntityMethod| N386
  N93 -->|CommandHandlerToEntityMethod| N387
  N93 -->|CommandHandlerToEntityMethod| N388
  N93 -->|CommandHandlerToEntityMethod| N389
  N93 -->|CommandHandlerToEntityMethod| N393
  N93 -->|CommandHandlerToEntityMethod| N394
  N93 -->|CommandHandlerToEntityMethod| N395
  N93 -->|CommandHandlerToEntityMethod| N396
  N93 -->|CommandHandlerToEntityMethod| N397
  N93 -->|CommandHandlerToEntityMethod| N398
  N93 -->|CommandHandlerToEntityMethod| N399
  N93 -->|CommandHandlerToEntityMethod| N400
  N93 -->|CommandHandlerToEntityMethod| N401
  N93 -->|CommandHandlerToEntityMethod| N403
  N94 -->|CommandToCommandHandler| N93
  N95 -->|CommandHandlerToEntityMethod| N361
  N96 -->|CommandToCommandHandler| N95
  N97 -->|CommandHandlerToEntityMethod| N361
  N98 -->|CommandToCommandHandler| N97
  N99 -->|CommandHandlerToEntityMethod| N361
  N100 -->|CommandToCommandHandler| N99
  N101 -->|CommandHandlerToEntityMethod| N361
  N102 -->|CommandToCommandHandler| N101
  N103 -->|CommandHandlerToEntityMethod| N360
  N104 -->|CommandToCommandHandler| N103
  N105 -->|CommandHandlerToEntityMethod| N366
  N106 -->|CommandToCommandHandler| N105
  N107 -->|CommandHandlerToEntityMethod| N374
  N108 -->|CommandToCommandHandler| N107
  N109 -->|CommandHandlerToEntityMethod| N377
  N110 -->|CommandToCommandHandler| N109
  N111 -->|CommandHandlerToEntityMethod| N375
  N112 -->|CommandToCommandHandler| N111
  N113 -->|CommandHandlerToEntityMethod| N369
  N114 -->|CommandToCommandHandler| N113
  N115 -->|CommandHandlerToEntityMethod| N379
  N115 -->|CommandHandlerToEntityMethod| N380
  N116 -->|CommandToCommandHandler| N115
  N117 -->|CommandHandlerToEntityMethod| N405
  N117 -->|CommandHandlerToEntityMethod| N406
  N118 -->|CommandToCommandHandler| N117
  N119 -->|CommandHandlerToEntityMethod| N385
  N119 -->|CommandHandlerToEntityMethod| N390
  N119 -->|CommandHandlerToEntityMethod| N391
  N119 -->|CommandHandlerToEntityMethod| N392
  N119 -->|CommandHandlerToEntityMethod| N403
  N119 -->|CommandHandlerToEntityMethod| N404
  N119 -->|CommandHandlerToEntityMethod| N407
  N120 -->|CommandToCommandHandler| N119
  N121 -->|CommandHandlerToEntityMethod| N416
  N122 -->|CommandToCommandHandler| N121
  N123 -->|CommandHandlerToEntityMethod| N417
  N124 -->|CommandToCommandHandler| N123
  N125 -->|CommandHandlerToEntityMethod| N418
  N126 -->|CommandToCommandHandler| N125
  N127 -->|CommandHandlerToEntityMethod| N414
  N127 -->|CommandHandlerToEntityMethod| N420
  N127 -->|CommandHandlerToEntityMethod| N421
  N127 -->|CommandHandlerToEntityMethod| N422
  N128 -->|CommandToCommandHandler| N127
  N129 -->|CommandHandlerToEntityMethod| N415
  N129 -->|CommandHandlerToEntityMethod| N419
  N130 -->|CommandToCommandHandler| N129
  N131 -->|CommandHandlerToEntityMethod| N428
  N131 -->|CommandHandlerToEntityMethod| N429
  N132 -->|CommandToCommandHandler| N131
  N133 -->|CliToCliHandler| N2
  N134 -->|CliToCliHandler| N3
  N135 -->|CliToCliHandler| N4
  N136 -->|CliToCliHandler| N5
  N137 -->|CliToCliHandler| N6
  N138 -->|CliToCliHandler| N7
  N139 -->|CliToCliHandler| N8
  N140 -->|CliToCliHandler| N9
  N141 -->|CliToCliHandler| N10
  N142 -->|CliToCliHandler| N11
  N143 -->|CliToCliHandler| N12
  N144 -->|CliToCliHandler| N13
  N145 -->|QueryToQueryHandler| N14
  N146 -->|QueryToQueryHandler| N15
  N147 -->|QueryToQueryHandler| N16
  N148 -->|QueryToQueryHandler| N17
  N149 -->|QueryToQueryHandler| N18
  N150 -->|QueryToQueryHandler| N19
  N151 -->|QueryToQueryHandler| N20
  N152 -->|QueryToQueryHandler| N21
  N153 -->|QueryToQueryHandler| N22
  N154 -->|QueryToQueryHandler| N23
  N155 -->|QueryToQueryHandler| N24
  N156 -->|QueryToQueryHandler| N25
  N157 -->|QueryToQueryHandler| N26
  N158 -->|QueryToQueryHandler| N27
  N159 -->|QueryToQueryHandler| N28
  N160 -->|QueryToQueryHandler| N29
  N161 -->|QueryToQueryHandler| N30
  N162 -->|QueryToQueryHandler| N31
  N163 -->|QueryToQueryHandler| N32
  N164 -->|QueryToQueryHandler| N33
  N165 -->|QueryToQueryHandler| N34
  N166 -->|QueryToQueryHandler| N35
  N167 -->|QueryToQueryHandler| N36
  N168 -->|QueryToQueryHandler| N37
  N169 -->|QueryToQueryHandler| N38
  N170 -->|QueryToQueryHandler| N39
  N171 -->|QueryToQueryHandler| N40
  N172 -->|QueryToQueryHandler| N41
  N173 -->|QueryToQueryHandler| N42
  N174 -->|QueryToQueryHandler| N43
  N175 -->|QueryToQueryHandler| N44
  N178 -->|DomainEventHandlerToCommand| N46
  N183 -->|DomainEventHandlerToCommand| N68
  N184 -->|DomainEventHandlerToCommand| N78
  N185 -->|DomainEventHandlerToCommand| N80
  N186 -->|DomainEventHandlerToCommand| N48
  N187 -->|DomainEventHandlerToCommand| N96
  N188 -->|DomainEventHandlerToCommand| N98
  N189 -->|DomainEventHandlerToCommand| N86
  N190 -->|DomainEventHandlerToCommand| N52
  N191 -->|DomainEventHandlerToCommand| N80
  N192 -->|DomainEventHandlerToCommand| N100
  N193 -->|DomainEventHandlerToCommand| N102
  N194 -->|DomainEventHandlerToCommand| N86
  N195 -->|DomainEventHandlerToCommand| N70
  N196 -->|DomainEventHandlerToCommand| N70
  N202 -->|DomainEventHandlerToCli| N135
  N203 -->|DomainEventHandlerToCommand| N66
  N203 -->|DomainEventHandlerToCli| N135
  N205 -->|DomainEventHandlerToCommand| N74
  N206 -->|DomainEventHandlerToCommand| N72
  N215 -->|DomainEventHandlerToCommand| N62
  N217 -->|DomainEventHandlerToCommand| N76
  N217 -->|DomainEventHandlerToQuery| N158
  N219 -->|DomainEventHandlerToCommand| N70
  N220 -->|DomainEventHandlerToCommand| N70
  N221 -->|DomainEventHandlerToCommand| N70
  N223 -->|DomainEventHandlerToCommand| N70
  N224 -->|DomainEventHandlerToCommand| N104
  N225 -->|DomainEventHandlerToCommand| N106
  N226 -->|DomainEventHandlerToCli| N136
  N229 -->|DomainEventHandlerToCommand| N70
  N230 -->|DomainEventHandlerToCommand| N70
  N231 -->|DomainEventHandlerToCommand| N60
  N232 -->|DomainEventHandlerToCli| N134
  N233 -->|DomainEventHandlerToCommand| N92
  N236 -->|DomainEventHandlerToCommand| N56
  N236 -->|DomainEventHandlerToCommand| N58
  N237 -->|DomainEventHandlerToCommand| N118
  N238 -->|DomainEventHandlerToCommand| N82
  N240 -->|DomainEventHandlerToCommand| N82
  N241 -->|DomainEventHandlerToCommand| N50
  N242 -->|DomainEventHandlerToCommand| N54
  N242 -->|DomainEventHandlerToQuery| N161
  N245 -->|DomainEventHandlerToCommand| N84
  N246 -->|DomainEventHandlerToCommand| N84
  N247 -->|DomainEventHandlerToCommand| N126
  N247 -->|DomainEventHandlerToCli| N139
  N247 -->|DomainEventHandlerToQuery| N170
  N248 -->|DomainEventHandlerToCli| N138
  N249 -->|DomainEventHandlerToCommand| N114
  N249 -->|DomainEventHandlerToCli| N137
  N252 -->|DomainEventHandlerToCommand| N116
  N253 -->|DomainEventHandlerToCommand| N88
  N257 -->|DomainEventHandlerToCommand| N64
  N258 -->|DomainEventHandlerToCommand| N94
  N259 -->|DomainEventHandlerToCli| N133
  N260 -->|DomainEventHandlerToCommand| N108
  N260 -->|DomainEventHandlerToCommand| N110
  N260 -->|DomainEventHandlerToCommand| N132
  N262 -->|DomainEventHandlerToCommand| N90
  N263 -->|DomainEventHandlerToCommand| N130
  N264 -->|DomainEventHandlerToCommand| N120
  N265 -->|DomainEventHandlerToCommand| N112
  N265 -->|DomainEventHandlerToCommand| N122
  N266 -->|DomainEventHandlerToCommand| N122
  N266 -->|DomainEventHandlerToCli| N140
  N266 -->|DomainEventHandlerToQuery| N170
  N267 -->|DomainEventHandlerToCommand| N124
  N267 -->|DomainEventHandlerToCli| N141
  N267 -->|DomainEventHandlerToCli| N142
  N267 -->|DomainEventHandlerToCli| N143
  N267 -->|DomainEventHandlerToCli| N144
  N267 -->|DomainEventHandlerToQuery| N175
  N268 -->|DomainEventHandlerToCommand| N128
  N274 -->|EntityMethodToDomainEvent| N282
  N275 -->|EntityMethodToDomainEvent| N280
  N276 -->|DomainEventToHandler| N176
  N277 -->|DomainEventToHandler| N177
  N278 -->|DomainEventToHandler| N178
  N279 -->|DomainEventToHandler| N179
  N280 -->|DomainEventToHandler| N180
  N281 -->|DomainEventToHandler| N181
  N282 -->|DomainEventToHandler| N182
  N283 -->|DomainEventToHandler| N183
  N283 -->|DomainEventToHandler| N184
  N284 -->|DomainEventToHandler| N185
  N284 -->|DomainEventToHandler| N186
  N285 -->|DomainEventToHandler| N187
  N286 -->|DomainEventToHandler| N188
  N287 -->|DomainEventToHandler| N189
  N287 -->|DomainEventToHandler| N190
  N288 -->|DomainEventToHandler| N191
  N289 -->|DomainEventToHandler| N192
  N290 -->|DomainEventToHandler| N193
  N291 -->|DomainEventToHandler| N194
  N292 -->|DomainEventToHandler| N195
  N293 -->|DomainEventToHandler| N196
  N294 -->|EntityMethodToDomainEvent| N295
  N294 -->|EntityMethodToDomainEvent| N296
  N294 -->|EntityMethodToDomainEvent| N297
  N294 -->|EntityMethodToDomainEvent| N298
  N294 -->|EntityMethodToDomainEvent| N299
  N295 -->|DomainEventToHandler| N197
  N296 -->|DomainEventToHandler| N198
  N297 -->|DomainEventToHandler| N199
  N298 -->|DomainEventToHandler| N200
  N299 -->|DomainEventToHandler| N201
  N300 -->|EntityMethodToDomainEvent| N308
  N301 -->|EntityMethodToDomainEvent| N310
  N302 -->|EntityMethodToDomainEvent| N307
  N305 -->|DomainEventToHandler| N202
  N306 -->|DomainEventToHandler| N203
  N307 -->|DomainEventToHandler| N204
  N308 -->|DomainEventToHandler| N205
  N309 -->|DomainEventToHandler| N206
  N310 -->|DomainEventToHandler| N207
  N311 -->|DomainEventToHandler| N208
  N313 -->|EntityMethodToDomainEvent| N314
  N314 -->|DomainEventToHandler| N209
  N315 -->|EntityMethodToDomainEvent| N323
  N316 -->|EntityMethodToDomainEvent| N321
  N317 -->|DomainEventToHandler| N210
  N318 -->|DomainEventToHandler| N211
  N319 -->|DomainEventToHandler| N212
  N320 -->|DomainEventToHandler| N213
  N321 -->|DomainEventToHandler| N214
  N322 -->|DomainEventToHandler| N215
  N323 -->|DomainEventToHandler| N216
  N326 -->|DomainEventToHandler| N217
  N335 -->|EntityMethodToDomainEvent| N346
  N336 -->|EntityMethodToDomainEvent| N347
  N337 -->|EntityMethodToDomainEvent| N348
  N338 -->|EntityMethodToDomainEvent| N350
  N339 -->|EntityMethodToDomainEvent| N354
  N340 -->|EntityMethodToDomainEvent| N355
  N341 -->|EntityMethodToDomainEvent| N352
  N342 -->|EntityMethodToDomainEvent| N349
  N343 -->|EntityMethodToDomainEvent| N351
  N344 -->|EntityMethodToDomainEvent| N345
  N345 -->|DomainEventToHandler| N218
  N346 -->|DomainEventToHandler| N219
  N347 -->|DomainEventToHandler| N220
  N348 -->|DomainEventToHandler| N221
  N349 -->|DomainEventToHandler| N222
  N350 -->|DomainEventToHandler| N223
  N351 -->|DomainEventToHandler| N224
  N351 -->|DomainEventToHandler| N225
  N351 -->|DomainEventToHandler| N226
  N352 -->|DomainEventToHandler| N227
  N353 -->|DomainEventToHandler| N228
  N354 -->|DomainEventToHandler| N229
  N355 -->|DomainEventToHandler| N230
  N356 -->|DomainEventToHandler| N234
  N357 -->|DomainEventToHandler| N235
  N358 -->|DomainEventToHandler| N236
  N358 -->|DomainEventToHandler| N237
  N360 -->|EntityMethodToDomainEvent| N362
  N362 -->|DomainEventToHandler| N238
  N362 -->|DomainEventToHandler| N239
  N363 -->|DomainEventToHandler| N240
  N363 -->|DomainEventToHandler| N241
  N363 -->|DomainEventToHandler| N242
  N364 -->|DomainEventToHandler| N243
  N365 -->|DomainEventToHandler| N244
  N366 -->|EntityMethodToDomainEvent| N367
  N367 -->|DomainEventToHandler| N245
  N368 -->|DomainEventToHandler| N246
  N370 -->|DomainEventToHandler| N248
  N371 -->|DomainEventToHandler| N249
  N372 -->|DomainEventToHandler| N250
  N373 -->|DomainEventToHandler| N251
  N375 -->|EntityMethodToDomainEvent| N376
  N376 -->|DomainEventToHandler| N247
  N378 -->|DomainEventToHandler| N252
  N378 -->|DomainEventToHandler| N253
  N379 -->|EntityMethodToDomainEvent| N381
  N380 -->|EntityMethodToDomainEvent| N382
  N381 -->|DomainEventToHandler| N254
  N382 -->|DomainEventToHandler| N255
  N405 -->|EntityMethodToDomainEvent| N408
  N406 -->|EntityMethodToDomainEvent| N409
  N408 -->|DomainEventToHandler| N256
  N409 -->|DomainEventToHandler| N257
  N409 -->|DomainEventToHandler| N258
  N409 -->|DomainEventToHandler| N259
  N409 -->|DomainEventToHandler| N260
  N410 -->|DomainEventToHandler| N261
  N411 -->|DomainEventToHandler| N231
  N411 -->|DomainEventToHandler| N232
  N411 -->|DomainEventToHandler| N233
  N412 -->|DomainEventToHandler| N262
  N413 -->|DomainEventToHandler| N263
  N415 -->|EntityMethodToDomainEvent| N426
  N416 -->|EntityMethodToDomainEvent| N423
  N417 -->|EntityMethodToDomainEvent| N427
  N418 -->|EntityMethodToDomainEvent| N425
  N420 -->|EntityMethodToDomainEvent| N424
  N423 -->|DomainEventToHandler| N264
  N424 -->|DomainEventToHandler| N265
  N425 -->|DomainEventToHandler| N266
  N426 -->|DomainEventToHandler| N267
  N427 -->|DomainEventToHandler| N268
  classDef cli fill:#86EFAC,stroke:#15803D,color:#0F172A
  classDef clihandler fill:#22C55E,stroke:#166534,color:#F0FDF4
  classDef command fill:#FDBA74,stroke:#C2410C,color:#111827
  classDef commandhandler fill:#F97316,stroke:#9A3412,color:#111827
  classDef domainevent fill:#FECACA,stroke:#B91C1C,color:#111827
  classDef domaineventhandler fill:#F87171,stroke:#991B1B,color:#111827
  classDef entitymethod fill:#F3F4F6,stroke:#6B7280,color:#111827
  classDef query fill:#93C5FD,stroke:#1D4ED8,color:#0F172A
  classDef queryhandler fill:#3B82F6,stroke:#1E40AF,color:#F8FAFC
  classDef querysendermethod fill:#BFDBFE,stroke:#1D4ED8,color:#0F172A
