flowchart TD
  N1[[RefreshLoginSessionCliHandler]]
  class N1 clihandler
  N2{{RefreshLoginSessionCli.Request}}
  class N2 cli
  N3[/CustomerAvatarUpdatedDomainEventSubscriber::on/]
  class N3 clisendermethod
  N2 -->|CliToCliHandler| N1
  N3 -->|CliSenderMethodToCli| N2
  classDef cli fill:#86EFAC,stroke:#15803D,color:#0F172A
  classDef clihandler fill:#22C55E,stroke:#166534,color:#F0FDF4
  classDef clisendermethod fill:#BBF7D0,stroke:#15803D,color:#0F172A
