flowchart TD
  N1([VideoCommentController::top])
  class N1 controllermethod
  N2{{TopCommentCmd.Request}}
  class N2 command
  N1 -->|ControllerMethodToCommand| N2
  classDef command fill:#FDBA74,stroke:#C2410C,color:#111827
  classDef controllermethod fill:#FDE68A,stroke:#B45309,color:#111827
