flowchart TD
  N1[[ReadObjectAsTextCliHandler]]
  class N1 clihandler
  N2[[GetVideoFilePostPathQryHandler]]
  class N2 queryhandler
  N3([AdminVideoAbrController::playlist])
  class N3 controllermethod
  N4{{ReadObjectAsTextCli.Request}}
  class N4 cli
  N5{{GetVideoFilePostPathQry.Request}}
  class N5 query
  N3 -->|ControllerMethodToCli| N4
  N3 -->|ControllerMethodToQuery| N5
  N4 -->|CliToCliHandler| N1
  N5 -->|QueryToQueryHandler| N2
  classDef cli fill:#86EFAC,stroke:#15803D,color:#0F172A
  classDef clihandler fill:#22C55E,stroke:#166534,color:#F0FDF4
  classDef controllermethod fill:#FDE68A,stroke:#B45309,color:#111827
  classDef query fill:#93C5FD,stroke:#1D4ED8,color:#0F172A
  classDef queryhandler fill:#3B82F6,stroke:#1E40AF,color:#F8FAFC
