flowchart TD
  N1[[CaptchaValidCliHandler]]
  class N1 clihandler
  N2[[GetCustomerProfileQryHandler]]
  class N2 queryhandler
  N3[[GetAccountInfoByEmailQryHandler]]
  class N3 queryhandler
  N4[[GetRecentPasswordFailureCountQryHandler]]
  class N4 queryhandler
  N5([AccountController::login])
  class N5 controllermethod
  N6[[UpdateLoginInfoCmd.Handler]]
  class N6 commandhandler
  N7{{UpdateLoginInfoCmd.Request}}
  class N7 command
  N8[[RecordAbnormalOperationCmd.Handler]]
  class N8 commandhandler
  N9{{RecordAbnormalOperationCmd.Request}}
  class N9 command
  N10[[RecordLoginLogCmd.Handler]]
  class N10 commandhandler
  N11{{RecordLoginLogCmd.Request}}
  class N11 command
  N12{{CaptchaValidCli.Request}}
  class N12 cli
  N13{{GetCustomerProfileQry.Request}}
  class N13 query
  N14{{GetAccountInfoByEmailQry.Request}}
  class N14 query
  N15{{GetRecentPasswordFailureCountQry.Request}}
  class N15 query
  N16[[LoginInfoUpdatedDomainEventSubscriber::on]]
  class N16 domaineventhandler
  N17[[PasswordInputFailedDomainEventSubscriber::on]]
  class N17 domaineventhandler
  N18(User::updateLoginInfo)
  class N18 entitymethod
  N19((LoginInfoUpdatedDomainEvent))
  class N19 domainevent
  N20(UserAbnormalOperationLog::&lt;get-id&gt;)
  class N20 entitymethod
  N21(UserAbnormalOperationLog::onCreate)
  class N21 entitymethod
  N22(UserLoginLog::&lt;get-id&gt;)
  class N22 entitymethod
  N23(UserLoginLog::onCreate)
  class N23 entitymethod
  N24((PasswordInputFailedDomainEvent))
  class N24 domainevent
  N5 -->|ControllerMethodToCommand| N7
  N5 -->|ControllerMethodToCommand| N11
  N5 -->|ControllerMethodToCli| N12
  N5 -->|ControllerMethodToQuery| N13
  N5 -->|ControllerMethodToQuery| N14
  N6 -->|CommandHandlerToEntityMethod| N18
  N7 -->|CommandToCommandHandler| N6
  N8 -->|CommandHandlerToEntityMethod| N20
  N8 -->|CommandHandlerToEntityMethod| N21
  N9 -->|CommandToCommandHandler| N8
  N10 -->|CommandHandlerToEntityMethod| N22
  N10 -->|CommandHandlerToEntityMethod| N23
  N11 -->|CommandToCommandHandler| N10
  N12 -->|CliToCliHandler| N1
  N13 -->|QueryToQueryHandler| N2
  N14 -->|QueryToQueryHandler| N3
  N15 -->|QueryToQueryHandler| N4
  N17 -->|DomainEventHandlerToCommand| N9
  N17 -->|DomainEventHandlerToQuery| N15
  N18 -->|EntityMethodToDomainEvent| N19
  N19 -->|DomainEventToHandler| N16
  N23 -->|EntityMethodToDomainEvent| N24
  N24 -->|DomainEventToHandler| N17
  classDef cli fill:#86EFAC,stroke:#15803D,color:#0F172A
  classDef clihandler fill:#22C55E,stroke:#166534,color:#F0FDF4
  classDef command fill:#FDBA74,stroke:#C2410C,color:#111827
  classDef commandhandler fill:#F97316,stroke:#9A3412,color:#111827
  classDef controllermethod fill:#FDE68A,stroke:#B45309,color:#111827
  classDef domainevent fill:#FECACA,stroke:#B91C1C,color:#111827
  classDef domaineventhandler fill:#F87171,stroke:#991B1B,color:#111827
  classDef entitymethod fill:#F3F4F6,stroke:#6B7280,color:#111827
  classDef query fill:#93C5FD,stroke:#1D4ED8,color:#0F172A
  classDef queryhandler fill:#3B82F6,stroke:#1E40AF,color:#F8FAFC
