flowchart TD
  N1[[CommentExistsByIdQryHandler]]
  class N1 queryhandler
  N2[[GetCommentByIdQryHandler]]
  class N2 queryhandler
  N3{{CommentExistsByIdQry.Request}}
  class N3 query
  N4{{GetCommentByIdQry.Request}}
  class N4 query
  N5[/CommentDeletePermission.Validator::isValid/]
  class N5 validator
  N3 -->|QueryToQueryHandler| N1
  N4 -->|QueryToQueryHandler| N2
  N5 -->|ValidatorToQuery| N3
  N5 -->|ValidatorToQuery| N4
  classDef query fill:#93C5FD,stroke:#1D4ED8,color:#0F172A
  classDef queryhandler fill:#3B82F6,stroke:#1E40AF,color:#F8FAFC
  classDef validator fill:#FEF3C7,stroke:#B45309,color:#111827
