flowchart TD
  N1[[CaptchaValidCliHandler]]
  class N1 clihandler
  N2[[IssueTokenCliHandler]]
  class N2 clihandler
  N3[[GetAccountInfoByEmailQryHandler]]
  class N3 queryhandler
  N4[[GetRecentPasswordFailureCountQryHandler]]
  class N4 queryhandler
  N5([AdminAccountController::login])
  class N5 controllermethod
  N6[[RecordAbnormalOperationCmd.Handler]]
  class N6 commandhandler
  N7{{RecordAbnormalOperationCmd.Request}}
  class N7 command
  N8[[RecordLoginLogCmd.Handler]]
  class N8 commandhandler
  N9{{RecordLoginLogCmd.Request}}
  class N9 command
  N10{{CaptchaValidCli.Request}}
  class N10 cli
  N11{{IssueTokenCli.Request}}
  class N11 cli
  N12{{GetAccountInfoByEmailQry.Request}}
  class N12 query
  N13{{GetRecentPasswordFailureCountQry.Request}}
  class N13 query
  N14[[PasswordInputFailedDomainEventSubscriber::on]]
  class N14 domaineventhandler
  N15(UserAbnormalOperationLog::&lt;get-id&gt;)
  class N15 entitymethod
  N16(UserAbnormalOperationLog::onCreate)
  class N16 entitymethod
  N17(UserLoginLog::&lt;get-id&gt;)
  class N17 entitymethod
  N18(UserLoginLog::onCreate)
  class N18 entitymethod
  N19((PasswordInputFailedDomainEvent))
  class N19 domainevent
  N5 -->|ControllerMethodToCommand| N9
  N5 -->|ControllerMethodToCli| N10
  N5 -->|ControllerMethodToCli| N11
  N5 -->|ControllerMethodToQuery| N12
  N6 -->|CommandHandlerToEntityMethod| N15
  N6 -->|CommandHandlerToEntityMethod| N16
  N7 -->|CommandToCommandHandler| N6
  N8 -->|CommandHandlerToEntityMethod| N17
  N8 -->|CommandHandlerToEntityMethod| N18
  N9 -->|CommandToCommandHandler| N8
  N10 -->|CliToCliHandler| N1
  N11 -->|CliToCliHandler| N2
  N12 -->|QueryToQueryHandler| N3
  N13 -->|QueryToQueryHandler| N4
  N14 -->|DomainEventHandlerToCommand| N7
  N14 -->|DomainEventHandlerToQuery| N13
  N18 -->|EntityMethodToDomainEvent| N19
  N19 -->|DomainEventToHandler| N14
  classDef cli fill:#86EFAC,stroke:#15803D,color:#0F172A
  classDef clihandler fill:#22C55E,stroke:#166534,color:#F0FDF4
  classDef command fill:#FDBA74,stroke:#C2410C,color:#111827
  classDef commandhandler fill:#F97316,stroke:#9A3412,color:#111827
  classDef controllermethod fill:#FDE68A,stroke:#B45309,color:#111827
  classDef domainevent fill:#FECACA,stroke:#B91C1C,color:#111827
  classDef domaineventhandler fill:#F87171,stroke:#991B1B,color:#111827
  classDef entitymethod fill:#F3F4F6,stroke:#6B7280,color:#111827
  classDef query fill:#93C5FD,stroke:#1D4ED8,color:#0F172A
  classDef queryhandler fill:#3B82F6,stroke:#1E40AF,color:#F8FAFC
