flowchart TD
  N1[[GetCustomerVideoSeriesInfoQryHandler]]
  class N1 queryhandler
  N2{{GetCustomerVideoSeriesInfoQry.Request}}
  class N2 query
  N3[/SeriesOwnership.Validator::isValid/]
  class N3 validator
  N2 -->|QueryToQueryHandler| N1
  N3 -->|ValidatorToQuery| N2
  classDef query fill:#93C5FD,stroke:#1D4ED8,color:#0F172A
  classDef queryhandler fill:#3B82F6,stroke:#1E40AF,color:#F8FAFC
  classDef validator fill:#FEF3C7,stroke:#B45309,color:#111827
