flowchart TD
  N1[[CaptchaValidCliHandler]]
  class N1 clihandler
  N2([AccountController::register])
  class N2 controllermethod
  N3{{RegisterAccountCmd.Request}}
  class N3 command
  N4{{CaptchaValidCli.Request}}
  class N4 cli
  N2 -->|ControllerMethodToCommand| N3
  N2 -->|ControllerMethodToCli| N4
  N4 -->|CliToCliHandler| N1
  classDef cli fill:#86EFAC,stroke:#15803D,color:#0F172A
  classDef clihandler fill:#22C55E,stroke:#166534,color:#F0FDF4
  classDef command fill:#FDBA74,stroke:#C2410C,color:#111827
  classDef controllermethod fill:#FDE68A,stroke:#B45309,color:#111827
