flowchart TD
  N1[[GetRecentPasswordFailureCountQryHandler]]
  class N1 queryhandler
  N2([AccountController::logout])
  class N2 controllermethod
  N3[[RecordAbnormalOperationCmd.Handler]]
  class N3 commandhandler
  N4{{RecordAbnormalOperationCmd.Request}}
  class N4 command
  N5[[RecordLoginLogCmd.Handler]]
  class N5 commandhandler
  N6{{RecordLoginLogCmd.Request}}
  class N6 command
  N7{{GetRecentPasswordFailureCountQry.Request}}
  class N7 query
  N8[[PasswordInputFailedDomainEventSubscriber::on]]
  class N8 domaineventhandler
  N9(UserAbnormalOperationLog::&lt;get-id&gt;)
  class N9 entitymethod
  N10(UserAbnormalOperationLog::onCreate)
  class N10 entitymethod
  N11(UserLoginLog::&lt;get-id&gt;)
  class N11 entitymethod
  N12(UserLoginLog::onCreate)
  class N12 entitymethod
  N13((PasswordInputFailedDomainEvent))
  class N13 domainevent
  N2 -->|ControllerMethodToCommand| N6
  N3 -->|CommandHandlerToEntityMethod| N9
  N3 -->|CommandHandlerToEntityMethod| N10
  N4 -->|CommandToCommandHandler| N3
  N5 -->|CommandHandlerToEntityMethod| N11
  N5 -->|CommandHandlerToEntityMethod| N12
  N6 -->|CommandToCommandHandler| N5
  N7 -->|QueryToQueryHandler| N1
  N8 -->|DomainEventHandlerToCommand| N4
  N8 -->|DomainEventHandlerToQuery| N7
  N12 -->|EntityMethodToDomainEvent| N13
  N13 -->|DomainEventToHandler| N8
  classDef command fill:#FDBA74,stroke:#C2410C,color:#111827
  classDef commandhandler fill:#F97316,stroke:#9A3412,color:#111827
  classDef controllermethod fill:#FDE68A,stroke:#B45309,color:#111827
  classDef domainevent fill:#FECACA,stroke:#B91C1C,color:#111827
  classDef domaineventhandler fill:#F87171,stroke:#991B1B,color:#111827
  classDef entitymethod fill:#F3F4F6,stroke:#6B7280,color:#111827
  classDef query fill:#93C5FD,stroke:#1D4ED8,color:#0F172A
  classDef queryhandler fill:#3B82F6,stroke:#1E40AF,color:#F8FAFC
